-- ICICI admission payments — run in phpMyAdmin if migrations are not used

CREATE TABLE IF NOT EXISTS `admission_payments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_txn_no` varchar(40) NOT NULL,
  `payable_type` varchar(255) NOT NULL,
  `payable_id` bigint unsigned NOT NULL,
  `form_type` varchar(60) NOT NULL,
  `registration_number` varchar(40) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency_code` varchar(5) NOT NULL DEFAULT '356',
  `customer_name` varchar(255) NOT NULL,
  `customer_email` varchar(255) NOT NULL,
  `customer_mobile` varchar(20) NOT NULL,
  `addl_param1` varchar(120) DEFAULT NULL,
  `addl_param2` varchar(120) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'pending',
  `response_code` varchar(30) DEFAULT NULL,
  `response_description` varchar(255) DEFAULT NULL,
  `payment_mode` varchar(40) DEFAULT NULL,
  `payment_sub_inst_type` varchar(255) DEFAULT NULL,
  `payment_id` varchar(40) DEFAULT NULL,
  `txn_id` varchar(40) DEFAULT NULL,
  `tran_ctx` varchar(255) DEFAULT NULL,
  `redirect_uri` varchar(500) DEFAULT NULL,
  `payment_datetime` varchar(20) DEFAULT NULL,
  `initiate_request` json DEFAULT NULL,
  `initiate_response` json DEFAULT NULL,
  `callback_response` json DEFAULT NULL,
  `status_response` json DEFAULT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `admission_payments_merchant_txn_no_unique` (`merchant_txn_no`),
  KEY `admission_payments_registration_number_index` (`registration_number`),
  KEY `admission_payments_status_index` (`status`),
  KEY `admission_payments_payable_type_payable_id_index` (`payable_type`,`payable_id`),
  KEY `admission_payments_payment_id_index` (`payment_id`),
  KEY `admission_payments_txn_id_index` (`txn_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
