-- Contact Us page (admin: /controlpanel/contact-page)

CREATE TABLE IF NOT EXISTS `contact_pages` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `page_title` varchar(255) NOT NULL,
  `page_subtitle` varchar(255) DEFAULT NULL,
  `page_intro` text NOT NULL,
  `page_intro_2` text DEFAULT NULL,
  `office_title` varchar(255) DEFAULT NULL,
  `office_brand` varchar(255) DEFAULT NULL,
  `office_tagline` varchar(255) DEFAULT NULL,
  `office_head_label` varchar(255) DEFAULT NULL,
  `address_line` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `pin_code` varchar(20) DEFAULT NULL,
  `phone_helpline` varchar(30) DEFAULT NULL,
  `phone_whatsapp` varchar(30) DEFAULT NULL,
  `phone_office` varchar(30) DEFAULT NULL,
  `email_admissions` varchar(255) DEFAULT NULL,
  `email_general` varchar(255) DEFAULT NULL,
  `email_media` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `office_hours` json DEFAULT NULL,
  `admission_support_title` varchar(255) DEFAULT NULL,
  `admission_support_intro` text DEFAULT NULL,
  `admission_support_items` json DEFAULT NULL,
  `partnership_title` varchar(255) DEFAULT NULL,
  `partnership_intro` text DEFAULT NULL,
  `partnership_items` json DEFAULT NULL,
  `faculty_cta_title` varchar(255) DEFAULT NULL,
  `faculty_cta_text` text DEFAULT NULL,
  `faculty_cta_url` varchar(500) DEFAULT NULL,
  `media_title` varchar(255) DEFAULT NULL,
  `media_text` text DEFAULT NULL,
  `social_links` json DEFAULT NULL,
  `maps_embed_url` text DEFAULT NULL,
  `form_categories` json DEFAULT NULL,
  `immediate_title` varchar(255) DEFAULT NULL,
  `immediate_call` varchar(30) DEFAULT NULL,
  `immediate_whatsapp` varchar(30) DEFAULT NULL,
  `immediate_intro_url` varchar(500) DEFAULT NULL,
  `immediate_apply_url` varchar(500) DEFAULT NULL,
  `tagline_brand` varchar(255) DEFAULT NULL,
  `tagline_text` varchar(255) DEFAULT NULL,
  `tagline_subtext` varchar(255) DEFAULT NULL,
  `tagline_hindi` varchar(255) DEFAULT NULL,
  `hero_image` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `contact_inquiries` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `registration_number` varchar(255) DEFAULT NULL,
  `full_name` varchar(255) NOT NULL,
  `mobile` varchar(30) NOT NULL,
  `whatsapp` varchar(30) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `date_of_birth` date DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `pin_code` varchar(20) DEFAULT NULL,
  `country` varchar(100) DEFAULT 'India',
  `interested_program` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `educational_qualification` varchar(255) DEFAULT NULL,
  `occupation` varchar(255) DEFAULT NULL,
  `organization_name` varchar(255) DEFAULT NULL,
  `preferred_centre` varchar(255) DEFAULT NULL,
  `preferred_batch` varchar(50) DEFAULT NULL,
  `preferred_language` varchar(50) DEFAULT NULL,
  `hear_about` varchar(255) DEFAULT NULL,
  `purpose_of_joining` json DEFAULT NULL,
  `expectations` text DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `documents` json DEFAULT NULL,
  `agreed_to_contact` tinyint(1) NOT NULL DEFAULT 0,
  `agreed_info_correct` tinyint(1) NOT NULL DEFAULT 0,
  `agreed_privacy` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `contact_inquiries_registration_number_unique` (`registration_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `migrations` (`migration`, `batch`)
SELECT t.migration, IFNULL((SELECT MAX(batch) FROM `migrations` m), 0) + 1
FROM (
  SELECT '2026_06_29_000016_create_contact_pages_table' AS migration UNION ALL
  SELECT '2026_06_29_000017_create_contact_inquiries_table' UNION ALL
  SELECT '2026_06_29_000018_expand_contact_inquiries_table'
) AS t
WHERE NOT EXISTS (SELECT 1 FROM `migrations` m WHERE m.migration = t.migration);
