<?php

return [

    'menu' => [
        ['label' => 'Apply Now', 'slug' => 'apply-now'],
        ['label' => 'Online Admission', 'slug' => 'online-admission'],
        ['label' => 'Admission Process', 'slug' => 'admission-process'],
        ['label' => 'Eligibility Criteria', 'slug' => 'eligibility-criteria'],
        ['label' => 'Programs', 'slug' => 'programs'],
        ['label' => 'Course Duration', 'slug' => 'course-duration'],
        ['label' => 'Program Fees', 'slug' => 'program-fees'],
        ['label' => 'Scholarships', 'slug' => 'scholarships'],
        ['label' => 'Batch Timings', 'slug' => 'batch-timings'],
        ['label' => 'Academic Calendar', 'slug' => 'academic-calendar'],
        ['label' => 'Introduction Session', 'slug' => 'introduction-session'],
        ['label' => 'Book Counselling', 'slug' => 'book-counselling'],
        ['label' => 'Download Brochure', 'slug' => 'download-brochure'],
        ['label' => 'Download Prospectus', 'slug' => 'download-prospectus'],
        ['label' => 'Required Documents', 'slug' => 'required-documents'],
        ['label' => 'Fee Payment', 'slug' => 'fee-payment'],
        ['label' => 'EMI Options', 'slug' => 'emi-options'],
        ['label' => 'Refund Policy', 'slug' => 'refund-policy'],
        ['label' => 'FAQs', 'slug' => 'faqs'],
        ['label' => 'Contact Admission Office', 'slug' => 'contact-admission-office'],
    ],

    'categories' => [
        'School Students',
        'College Students',
        'Women Entrepreneurs',
        'Job Professionals',
        'Business Owners',
    ],

    'programs' => [
        'School Students Program',
        'College Students Program',
        'Women Entrepreneurs Program',
        'Job Professionals Program',
        'Business Owners & Business Professionals Program',
    ],

    'year_levels' => ['Std. 6–8', 'Std. 9–11', 'Diploma', 'Undergraduate', 'Postgraduate', 'Working Professional', 'Business Owner'],
    'batches' => ['Morning', 'Afternoon', 'Evening', 'Weekend'],
    'cities' => ['Rajkot', 'Ahmedabad', 'Surat', 'Vadodara', 'Other'],
    'centres' => ['BNS Rajkot Main Centre', 'BNS Ahmedabad Centre', 'BNS Surat Centre', 'Online Learning Centre'],

    'trust' => [
        'title' => 'Why Trust BNS Admissions',
        'items' => [
            'Academic Collaboration with Faculties of IIM',
            'Participation & Appreciation Certificates by Faculties of IIM (for eligible participants)',
            'Weekly Business School',
            'Practical Business Education',
            'Industry Expert Mentors',
            'Digital Learning Platform',
        ],
    ],

    'ctas' => [
        ['label' => 'Apply Now', 'url' => '/admissions/apply-now', 'icon' => 'fas fa-rocket', 'style' => 'primary'],
        ['label' => 'Book Free Introduction Session', 'url' => '/admissions/introduction-session', 'icon' => 'fas fa-calendar-check', 'style' => 'blue'],
        ['label' => 'Download Brochure', 'url' => '/admissions/download-brochure', 'icon' => 'fas fa-book', 'style' => 'green'],
        ['label' => 'Talk to Admission Counselor', 'url' => '/admissions/book-counselling', 'icon' => 'fas fa-user-tie', 'style' => 'dark'],
        ['label' => 'WhatsApp Now', 'url' => '/whatsapp-support', 'icon' => 'fab fa-whatsapp', 'style' => 'whatsapp'],
        ['label' => 'Pay Registration Fee', 'url' => '/admissions/fee-payment', 'icon' => 'fas fa-credit-card', 'style' => 'orange'],
        ['label' => 'Start Your Business Learning Journey', 'url' => '/admissions/apply-now', 'icon' => 'fas fa-graduation-cap', 'style' => 'primary'],
    ],

    'after_admission' => [
        'title' => 'After Admission',
        'items' => [
            'Admission Confirmation',
            'Welcome Letter',
            'Student ID',
            'Receipt',
            'Batch Allotment',
            'Class Schedule',
            'WhatsApp Community Join',
            'Student Portal Login',
            'Learning App Access',
        ],
    ],

    'student_dashboard' => [
        'title' => 'Student Dashboard',
        'items' => [
            'My Profile', 'My Program', 'Attendance', 'Assignments', 'Projects',
            'Certificates', 'Fee Status', 'Timetable', 'Notices', 'Download Resources',
        ],
    ],

    'office' => [
        'counselor' => 'BNS Admission Counselor',
        'phone' => '+91 98250 98250',
        'whatsapp' => '+91 98250 98250',
        'email' => 'admissions@businessnavacharschool.com',
        'address' => 'Rajkot, Gujarat - 360005',
        'maps_embed_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3691.0!2d70.8022!3d22.3039!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjLCsDE4JzE0LjAiTiA3MMKwNDgnMDguMCJF!5e0!3m2!1sen!2sin!4v1',
    ],

    'pages' => [
        'online-admission' => [
            'title' => 'Online Admission',
            'subtitle' => 'Apply to Business Navachar School from anywhere in India',
            'intro' => 'BNS offers a complete online direct admission system. Select your program, complete your application, upload documents, and pay fees — all in one guided flow.',
            'items' => [
                'Choose your student category and program',
                'Complete the digital admission form',
                'Upload required documents securely',
                'Pay registration and admission fees online',
                'Receive instant confirmation and student ID',
            ],
        ],
        'admission-process' => [
            'title' => 'Admission Process',
            'subtitle' => 'Simple steps to join BNS',
            'intro' => 'Our admission process is designed to be transparent, fast, and supportive at every step.',
            'items' => [
                'Step 1: Select Category & Program',
                'Step 2: Check Eligibility Criteria',
                'Step 3: Fill Online Admission Form',
                'Step 4: Upload Required Documents',
                'Step 5: Pay Registration / Admission Fee',
                'Step 6: Attend Introduction Session (if applicable)',
                'Step 7: Receive Admission Confirmation',
                'Step 8: Join Batch & Start Learning',
            ],
        ],
        'eligibility-criteria' => [
            'title' => 'Eligibility Criteria',
            'subtitle' => 'Who can apply to BNS programs',
            'intro' => 'Eligibility varies by program. Our admission team will guide you to the right program based on your education, age, and career goals.',
            'items' => [
                'School Students: Std. 6 to Std. 11',
                'College Students: Diploma, Undergraduate & Postgraduate',
                'Women Entrepreneurs: Aspiring and existing women business owners',
                'Job Professionals: Employees, managers, executives & officers',
                'Business Owners: Entrepreneurs and business professionals',
            ],
        ],
        'programs' => [
            'title' => 'Programs',
            'subtitle' => 'Business Education for Every Indian',
            'intro' => 'BNS offers specialized business education programs for every stage of your journey.',
            'items' => [
                'School Students Program',
                'College Students Program',
                'Women Entrepreneurs Program',
                'Job Professionals Program',
                'Business Owners & Business Professionals Program',
            ],
        ],
        'course-duration' => [
            'title' => 'Course Duration',
            'subtitle' => 'Flexible learning schedules',
            'intro' => 'Program duration depends on the selected course and batch. Contact our admission office for the latest schedule.',
            'items' => [
                'Foundation programs: 3–6 months',
                'Advanced business programs: 6–12 months',
                'Weekly Business School sessions',
                'Weekend and evening batches available',
            ],
        ],
        'program-fees' => [
            'title' => 'Program Fees',
            'subtitle' => 'Transparent fee structure',
            'intro' => 'BNS maintains a clear fee structure with registration fee, admission fee, and course fee components.',
            'items' => [
                'Registration Fee',
                'Admission Fee',
                'Course Fee',
                'GST as applicable',
                'Scholarship adjustments where eligible',
                'Discounts for early admission',
            ],
        ],
        'scholarships' => [
            'title' => 'Scholarships',
            'subtitle' => 'Financial support for deserving learners',
            'intro' => 'BNS offers scholarships and fee concessions for eligible students based on merit, need, and program criteria.',
            'items' => [
                'Merit-based scholarships',
                'Women entrepreneur scholarships',
                'Early bird admission discounts',
                'Referral benefits',
                'Special schemes for students and professionals',
            ],
        ],
        'batch-timings' => [
            'title' => 'Batch Timings',
            'subtitle' => 'Learn at a time that suits you',
            'intro' => 'Choose from morning, afternoon, evening, or weekend batches at your preferred centre.',
            'items' => ['Morning Batch', 'Afternoon Batch', 'Evening Batch', 'Weekend Batch'],
        ],
        'academic-calendar' => [
            'title' => 'Academic Calendar',
            'subtitle' => 'Plan your BNS learning journey',
            'intro' => 'View important dates for admissions, introduction sessions, batch starts, workshops, and examinations.',
            'items' => [
                'New batch admissions — ongoing',
                'Introduction sessions — every week',
                'Workshops & masterclasses — monthly',
                'Contact admission office for centre-wise calendar',
            ],
        ],
        'introduction-session' => [
            'title' => 'Introduction Session',
            'subtitle' => 'Experience BNS before you enroll',
            'intro' => 'Attend a free introduction session to understand our programs, faculty, learning methodology, and career outcomes.',
            'items' => [
                'Free for all prospective students',
                'Online and offline sessions available',
                'Meet admission counselors',
                'Get program recommendations',
                'Book your slot via Apply Now or WhatsApp',
            ],
        ],
        'book-counselling' => [
            'title' => 'Book Counselling',
            'subtitle' => 'Personalized admission guidance',
            'intro' => 'Speak with a BNS admission counselor to choose the right program, understand fees, and plan your learning path.',
            'items' => [
                'One-on-one counselling sessions',
                'Program selection guidance',
                'Career and business pathway advice',
                'Fee and scholarship consultation',
                'Book via contact form, call, or WhatsApp',
            ],
        ],
        'download-brochure' => [
            'title' => 'Download Brochure',
            'subtitle' => 'BNS Program Brochure',
            'intro' => 'Download the official Business Navachar School brochure for complete program details.',
            'items' => ['Program overview', 'Fee structure summary', 'Centre information', 'Admission contact details'],
            'download_url' => '#',
        ],
        'download-prospectus' => [
            'title' => 'Download Prospectus',
            'subtitle' => 'Official BNS Prospectus',
            'intro' => 'Get the full academic prospectus with curriculum, faculty, and certification details.',
            'items' => ['Academic framework', 'Learning outcomes', 'Certification details', 'Admission guidelines'],
            'download_url' => '#',
        ],
        'required-documents' => [
            'title' => 'Required Documents',
            'subtitle' => 'Keep these documents ready',
            'intro' => 'Upload the following documents during online admission. Requirements may vary by program.',
            'items' => [
                'Passport Size Photo',
                'Aadhaar Card',
                'School / College ID',
                'Last Marksheet',
                'Bonafide Certificate',
                'Graduation Certificate (if applicable)',
                'Experience Letter (for professionals)',
                'Business Proof (for business owners)',
            ],
        ],
        'fee-payment' => [
            'title' => 'Fee Payment',
            'subtitle' => 'Secure online payment',
            'intro' => 'Pay registration fee, admission fee, and course fee securely through our online payment system.',
            'items' => [
                'Registration Fee',
                'Admission Fee',
                'Course Fee',
                'GST',
                'Scholarship Adjustment',
                'Discount',
                'Total Payable — shown before payment',
                'Online Payment — UPI, Card, Net Banking',
            ],
        ],
        'emi-options' => [
            'title' => 'EMI Options',
            'subtitle' => 'Flexible payment plans',
            'intro' => 'BNS offers EMI and installment options on selected programs. Speak with our admission team for available plans.',
            'items' => [
                'Easy monthly installments',
                'Partner finance options',
                'Custom payment plans for eligible programs',
                'Contact admission office for EMI eligibility',
            ],
        ],
        'refund-policy' => [
            'title' => 'Refund Policy',
            'subtitle' => 'Fair and transparent refunds',
            'intro' => 'Our refund policy is designed to be clear and fair. Please read the terms before payment.',
            'items' => [
                'Refund requests must be submitted in writing',
                'Registration fee terms as per admission policy',
                'Course fee refunds subject to program terms',
                'Processing timeline communicated by admission office',
            ],
        ],
        'faqs' => [
            'title' => 'FAQs',
            'subtitle' => 'Admission frequently asked questions',
            'intro' => 'Find answers to common questions about BNS admissions, programs, fees, and batches.',
            'items' => [
                'How do I apply online? — Use Apply Now on our website',
                'What documents are required? — See Required Documents page',
                'Are scholarships available? — Yes, see Scholarships page',
                'Can I pay fees in EMI? — See EMI Options page',
                'How do I contact admission office? — Call, WhatsApp, or email us',
            ],
        ],
        'contact-admission-office' => [
            'title' => 'Contact Admission Office',
            'subtitle' => 'We are here to help you',
            'intro' => 'Reach our admission team for program guidance, fee details, batch information, and application support.',
            'items' => [
                'Admission Counselor available Monday–Saturday',
                'Phone, WhatsApp, and email support',
                'Visit our head office or nearest centre',
                'Book a counselling session online',
            ],
        ],
    ],

];
