<?php

return [
    'tagline' => 'About Us',
    'heading' => 'What is Business Navachar School?',
    'intro_text' => 'Business Navachar School (BNS) is not just a school — it is <strong>India\'s Weekly Business School</strong> and a complete business learning ecosystem where students, youth, professionals, entrepreneurs, and homemakers learn how to think, build, and grow in business.',
    'focus_heading' => 'We focus on:',
    'focus_points' => [
        '<strong>Practical business education</strong> through weekly learning',
        '<strong>Entrepreneurial thinking</strong>, leadership & financial literacy',
        'Real-world projects, case studies & expert mentorship',
        'Academic excellence with <strong>Faculties of IIM</strong>',
    ],
    'quote_text' => 'Business is not just trade. It is growth, expansion, and valuation.',
    'video_url' => 'https://www.youtube.com/watch?v=Get7rqXYrbQ',
    'mission_title' => 'Our Mission',
    'mission_text' => 'To create a practical, industry-oriented business learning platform that empowers Business Owners, Job Professionals, Women Entrepreneurs, and Youth with knowledge, skills, mindset, and confidence.',
    'vision_title' => 'Our Vision',
    'vision_text' => 'To build India\'s most trusted practical business learning ecosystem for Business Owners, Job Professionals, Women Entrepreneurs, and Youth — contributing to Viksit Bharat 2047.',
    'values' => [
        ['title' => 'Practical Learning', 'text' => 'Real business skills, not theory alone.'],
        ['title' => 'Inclusive Growth', 'text' => 'Programs for every age and background.'],
        ['title' => 'Nation Building', 'text' => 'Education of prosperity to eliminate poverty.'],
    ],

    'hub' => [
        'intro_2' => 'Through structured 4-hour weekly sessions, BNS delivers accessible and affordable <strong>business education</strong> designed to create employment creators, confident entrepreneurs, and financially independent individuals across India.',
        'collaboration_title' => 'Academic Collaboration with Faculties of IIM',
        'collaboration_text' => 'BNS collaborates with <strong>Faculties of IIM</strong> for mentor development, business learning methodologies, faculty training, and academic excellence — strengthening the quality of education delivered to every learner.',
        'collaboration_logo' => 'assets/images/partners/iim-ahmedabad-logo.png',
        'collaboration_logo_alt' => 'Faculties of IIM — Faculty Members',
        'pillars' => [
            [
                'label' => 'Our Vision',
                'route' => 'about.vision',
                'icon' => 'fas fa-eye',
                'description' => 'Building a prosperous, entrepreneurial India through business education for every Indian.',
            ],
            [
                'label' => 'Our Mission',
                'route' => 'about.mission',
                'icon' => 'fas fa-bullseye',
                'description' => 'Making practical business education accessible through the Weekly Business School model.',
            ],
            [
                'label' => 'Core Values',
                'route' => 'about.values',
                'icon' => 'fas fa-gem',
                'description' => 'The principles of knowledge, innovation, prosperity, and nation building that guide BNS.',
            ],
            [
                'label' => "Founder's Message",
                'route' => 'about.founder',
                'icon' => 'fas fa-quote-left',
                'description' => 'A personal message from Dr. Mehul Rupani, Founder of Business Navachar School.',
            ],
            [
                'label' => 'Why BNS?',
                'route' => 'about.why',
                'icon' => 'fas fa-star',
                'description' => '15 reasons to choose India\'s Weekly Business School for practical business education.',
            ],
            [
                'label' => 'Why Business Education?',
                'route' => 'about.why-business-education',
                'icon' => 'fas fa-lightbulb',
                'description' => 'Why business education is life education for every Indian learner.',
            ],
            [
                'label' => "India's Prosperity Mission",
                'route' => 'about.prosperity-mission',
                'icon' => 'fas fa-flag',
                'description' => 'Building a prosperous India through business education and Viksit Bharat 2047.',
            ],
            [
                'label' => 'Vision 2047',
                'route' => 'about.vision-2047',
                'icon' => 'fas fa-binoculars',
                'description' => 'Building a Developed India through business education by 2047.',
            ],
        ],
        'programs' => [
            ['icon' => '👧', 'label' => 'School Students'],
            ['icon' => '🎓', 'label' => 'College Youth'],
            ['icon' => '👩', 'label' => 'Women Entrepreneurs'],
            ['icon' => '💼', 'label' => 'Job Professionals'],
            ['icon' => '🏢', 'label' => 'Business Owners'],
        ],
    ],

    'mission_page' => [
        'title' => 'Mission',
        'subtitle' => 'Business Navachar School',
        'section_title' => 'Our Mission',
        'intro' => 'Our mission is to create a practical, industry-oriented business learning platform that empowers Business Owners, Job Professionals, Women Entrepreneurs, and Youth with the knowledge, skills, mindset, and confidence required to succeed in today\'s dynamic business world.',
        'points' => [
            'To provide practical, application-based business education beyond traditional classroom learning.',
            'To deliver a structured learning journey through a syllabus and learning methodology developed with the guidance of Faculties of IIM, as per the applicable collaboration framework.',
            'To provide learning through BNS-trained faculties, business coaches, industry experts, entrepreneurs, and mentors, with selected sessions delivered by Faculties of IIM, where applicable.',
            'To help entrepreneurs start, grow, systemize, scale, and sustain successful businesses.',
            'To enable job professionals to enhance leadership, management, business, and future-ready skills for career growth.',
            'To empower women entrepreneurs with business knowledge, confidence, leadership, and financial independence.',
            'To support youth in transforming innovative ideas into successful startups and scalable businesses.',
            'To develop entrepreneurial thinking, innovation, creativity, and problem-solving abilities.',
            'To build strong capabilities in finance, marketing, sales, operations, branding, AI, digital business, and strategic management.',
            'To promote ethical leadership, responsible entrepreneurship, and value-based business practices.',
            'To provide practical exposure through live projects, business case studies, workshops, masterclasses, business visits, networking events, and mentorship.',
            'To recognize participants through Program Completion Certificates, Skill Certificates, Project Certificates, and Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
            'To build a nationwide network of entrepreneurs, professionals, mentors, investors, and business leaders who learn, collaborate, and grow together.',
            'To contribute to employment generation, business innovation, economic development, and the vision of Viksit Bharat 2047.',
        ],
        'statement_title' => 'Mission Statement',
        'statement' => 'To Learn. To Apply. To Grow. To Scale. To Lead. To Create Impact.',
        'taglines' => [
            'Practical Learning. Business Excellence. Lifelong Growth.',
            'Empowering Entrepreneurs. Transforming Businesses. Building India.',
        ],
    ],

    'vision_page' => [
        'title' => 'Vision',
        'subtitle' => 'Business Navachar School',
        'section_title' => 'Our Vision',
        'intro' => 'To build India\'s most trusted practical business learning ecosystem for Business Owners, Job Professionals, Women Entrepreneurs, and Youth, empowering them with entrepreneurial thinking, leadership, innovation, AI, and business excellence to build successful businesses, create employment, and contribute to Viksit Bharat 2047.',
        'points' => [
            'To provide world-class practical business education that bridges the gap between knowledge and real business success.',
            'To deliver a structured learning journey through a syllabus and learning methodology developed with the guidance of Faculties of IIM, as per the applicable collaboration framework.',
            'To offer learning through BNS-trained faculties, business coaches, industry experts, entrepreneurs, and mentor-led sessions, with selected sessions delivered by Faculties of IIM, as applicable.',
            'To develop entrepreneurs, business owners, startup founders, corporate leaders, and innovators through experiential learning.',
            'To empower existing businesses to Grow, Systemize, Scale, and Sustain.',
            'To help job professionals enhance leadership, business, management, and future-ready skills.',
            'To enable women entrepreneurs to achieve business growth, financial independence, and leadership excellence.',
            'To transform youth into confident startup founders, innovators, and wealth creators.',
            'To promote innovation, creativity, design thinking, and problem-solving.',
            'To build strong foundations in finance, marketing, sales, operations, AI, digital business, and strategic leadership.',
            'To provide practical learning through live case studies, business simulations, workshops, masterclasses, projects, business visits, networking events, and mentoring.',
            'To recognize learning through Program Completion Certificates, Skill Certificates, Project Certificates, and Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
            'To create a lifelong ecosystem of entrepreneurs, business leaders, mentors, investors, professionals, and innovators.',
            'To contribute to India\'s economic growth by nurturing ethical, responsible, and globally competitive business leaders.',
        ],
        'statement_title' => 'Vision Statement',
        'statement' => 'World-Class Business Learning. Practical Experience. Future-Ready Leaders.',
        'taglines' => [
            'Syllabus & Methodology Guided by Faculties of IIM.',
            'Learn from BNS-Trained Faculties, Business Coaches & Industry Experts.',
            'Selected Learning Experiences with Faculties of IIM.',
            'Learn. Grow. Scale. Lead.',
            'Prosperous Businesses. Prosperous India.',
        ],
    ],

    'values_page' => [
        'title' => 'Core Values',
        'subtitle' => 'The Principles That Define Business Navachar School',
        'section_title' => 'Core Values',
        'intro' => [
            'At Business Navachar School (BNS), our values shape every learning experience, every decision, and every action. These values guide us in our mission to build a prosperous, entrepreneurial, and developed India.',
        ],
        'items' => [
            ['number' => 1, 'title' => 'Knowledge First', 'text' => 'We believe that knowledge is the foundation of success. Continuous learning creates lifelong growth.'],
            ['number' => 2, 'title' => 'Innovation Mindset', 'text' => 'We encourage creative thinking, problem-solving, and innovation to build future-ready entrepreneurs.'],
            ['number' => 3, 'title' => 'Prosperity for All', 'text' => 'We believe prosperity should be accessible to every individual, every family, and every community.'],
            ['number' => 4, 'title' => 'Practical Learning', 'text' => 'We focus on learning by doing through projects, case studies, research, discussions, and real-world business experiences.'],
            ['number' => 5, 'title' => 'Entrepreneurial Thinking', 'text' => 'We inspire learners to identify opportunities, create value, take initiative, and build sustainable businesses.'],
            ['number' => 6, 'title' => 'Integrity & Ethics', 'text' => 'We promote honesty, transparency, responsibility, and ethical business practices in every aspect of life.'],
            ['number' => 7, 'title' => 'Leadership Development', 'text' => 'We develop confident leaders who inspire others, create employment, and contribute to society.'],
            ['number' => 8, 'title' => 'Excellence', 'text' => 'We strive for the highest standards in education, mentorship, innovation, and learner outcomes.'],
            ['number' => 9, 'title' => 'Collaboration', 'text' => 'We believe that learning grows stronger through teamwork, mentorship, partnerships, and meaningful networking.'],
            ['number' => 10, 'title' => 'Financial Literacy', 'text' => 'We empower learners with the knowledge and skills to manage money wisely, build wealth responsibly, and achieve financial independence.'],
            ['number' => 11, 'title' => 'Lifelong Learning', 'text' => 'Business and technology evolve continuously. We encourage every learner to keep learning, adapting, and growing throughout life.'],
            ['number' => 12, 'title' => 'Nation Building', 'text' => 'Every entrepreneur, every business, and every innovation contributes to building a stronger and more prosperous India.'],
        ],
        'value_statement' => [
            'title' => 'Our Value Statement',
            'lines' => [
                'Knowledge empowers minds.',
                'Innovation creates opportunities.',
                'Entrepreneurship builds prosperity.',
                'Prosperity strengthens families.',
                'Strong families build a Developed India.',
            ],
        ],
        'philosophy' => [
            'title' => 'Our Guiding Philosophy',
            'hindi' => '( ज्ञान | नवाचार | समृद्धि )',
            'english' => 'Knowledge • Innovation • Prosperity',
        ],
    ],

    'why_bns_page' => [
        'title' => 'Why Business Navachar School (BNS)?',
        'subtitle' => 'Because the Future Belongs to Those Who Understand Business',
        'intro' => [
            'In today\'s rapidly changing world, academic qualifications alone are no longer enough. Success requires entrepreneurial thinking, financial literacy, innovation, leadership, and the ability to create opportunities.',
            'Business Navachar School (BNS) has been established to bridge the gap between traditional education and real-world business success.',
        ],
        'section_heading' => 'Why Choose BNS?',
        'reasons' => [
            [
                'number' => 1,
                'title' => 'India\'s Weekly Business School',
                'text' => 'A unique Weekly Business School offering structured business education throughout the year.',
            ],
            [
                'number' => 2,
                'title' => 'Practical Business Learning',
                'intro' => 'Learn through:',
                'items' => [
                    'Live Projects',
                    'Business Case Studies',
                    'Research Activities',
                    'Group Discussions',
                    'Presentations',
                    'Real Business Exposure',
                ],
            ],
            [
                'number' => 3,
                'title' => 'Learning Beyond Textbooks',
                'text' => 'Develop practical skills that are rarely taught in traditional schools and colleges.',
            ],
            [
                'number' => 4,
                'title' => 'Programs for Every Stage of Life',
                'intro' => 'Specially designed programs for:',
                'programs' => [
                    ['icon' => '👧', 'label' => 'School Students'],
                    ['icon' => '🎓', 'label' => 'College Youth'],
                    ['icon' => '👩', 'label' => 'Women Entrepreneurs'],
                    ['icon' => '💼', 'label' => 'Job Professionals'],
                    ['icon' => '🏢', 'label' => 'Business Owners'],
                ],
            ],
            [
                'number' => 5,
                'title' => 'Academic Collaboration with Faculties of IIM',
                'text' => 'BNS has an Academic Collaboration with Faculties of IIM to strengthen mentor development, business learning methodologies, and academic excellence.',
            ],
            [
                'number' => 6,
                'title' => 'Participation & Appreciation Certificates',
                'text' => 'Eligible participants receive Participation and Appreciation Certificates from the Faculties of IIM, adding value to their academic and professional profile.',
            ],
            [
                'number' => 7,
                'title' => 'Industry-Oriented Learning',
                'text' => 'Learn directly from entrepreneurs, business experts, mentors, and experienced professionals.',
            ],
            [
                'number' => 8,
                'title' => 'Entrepreneurial Mindset Development',
                'text' => 'Build confidence to identify opportunities, solve problems, take calculated risks, and create successful businesses.',
            ],
            [
                'number' => 9,
                'title' => 'Financial Literacy',
                'text' => 'Develop essential skills in money management, wealth creation, investments, budgeting, and financial planning.',
            ],
            [
                'number' => 10,
                'title' => 'Leadership Development',
                'text' => 'Strengthen communication, decision-making, teamwork, negotiation, and leadership abilities.',
            ],
            [
                'number' => 11,
                'title' => 'Business Networking',
                'text' => 'Become part of a growing ecosystem of students, entrepreneurs, mentors, industry experts, and business leaders.',
            ],
            [
                'number' => 12,
                'title' => 'Digital Learning Ecosystem',
                'text' => 'Access learning resources, assignments, projects, recorded sessions, and community support beyond the classroom.',
            ],
            [
                'number' => 13,
                'title' => 'Affordable & Accessible Education',
                'text' => 'High-quality business education designed to be accessible to learners across India.',
            ],
            [
                'number' => 14,
                'title' => 'Learning That Creates Opportunities',
                'text' => 'Our objective is not only to prepare learners for jobs but to empower them to create businesses, generate employment, and build sustainable careers.',
            ],
            [
                'number' => 15,
                'title' => 'A Mission Beyond Education',
                'text' => 'Business Navachar School is more than an institution—it is a national movement dedicated to building entrepreneurial citizens, prosperous families, and a Developed India (Viksit Bharat 2047).',
            ],
        ],
        'why_thousands' => [
            'title' => 'Why Thousands Will Choose BNS',
            'items' => [
                'Weekly Structured Learning',
                'Practical Business Education',
                'Academic Collaboration with Faculties of IIM',
                'Participation & Appreciation Certificates',
                'Expert Mentorship',
                'Project-Based Learning',
                'Entrepreneurial Mindset Development',
                'Leadership & Financial Literacy',
                'Business Networking Opportunities',
                'A Lifelong Learning Community',
            ],
        ],
        'closing' => [
            'brand' => 'Business Navachar School',
            'tagline' => 'Learn Prosperity • Create Prosperity • Build a Developed India',
            'hindi' => '( ज्ञान | नवाचार | समृद्धि )',
        ],
    ],

    'why_business_education_page' => [
        'title' => 'Why Business Education?',
        'subtitle' => 'Because Business Education is Life Education',
        'label' => 'Business Education',
        'intro' => [
            'The world is changing faster than ever before.',
            'Technology is evolving.',
            'Careers are changing.',
            'New industries are emerging.',
            'In this rapidly changing economy, academic knowledge alone is no longer enough.',
            'To succeed in the 21st century, every individual needs the ability to think, create, innovate, communicate, lead, and manage resources effectively.',
            'That is the power of Business Education.',
        ],
        'section_heading' => 'Why Business Education Matters',
        'reasons' => [
            [
                'number' => 1,
                'title' => 'Develops an Entrepreneurial Mindset',
                'text' => 'Business education teaches individuals to identify opportunities, solve problems, and create value for society.',
            ],
            [
                'number' => 2,
                'title' => 'Builds Financial Literacy',
                'text' => 'Understanding money, budgeting, saving, investing, and wealth creation are essential life skills that every person should learn.',
            ],
            [
                'number' => 3,
                'title' => 'Creates Job Creators',
                'text' => 'Instead of preparing people only to seek employment, business education empowers them to build businesses and generate employment for others.',
            ],
            [
                'number' => 4,
                'title' => 'Strengthens Leadership Skills',
                'text' => 'Business education develops confidence, communication, teamwork, decision-making, and problem-solving abilities.',
            ],
            [
                'number' => 5,
                'title' => 'Encourages Innovation',
                'text' => 'Innovation begins with curiosity. Business education inspires learners to think creatively and transform ideas into successful ventures.',
            ],
            [
                'number' => 6,
                'title' => 'Prepares Learners for the Real World',
                'text' => 'Students gain practical knowledge through projects, business case studies, research, presentations, and industry exposure.',
            ],
            [
                'number' => 7,
                'title' => 'Supports Career Growth',
                'text' => 'Whether someone is a student, employee, entrepreneur, or business owner, business education helps them grow professionally and financially.',
            ],
            [
                'number' => 8,
                'title' => 'Builds Multiple Income Opportunities',
                'text' => 'Learners understand how to diversify income, develop valuable skills, and create sustainable financial growth.',
            ],
            [
                'number' => 9,
                'title' => 'Promotes Ethical Business Practices',
                'text' => 'Business success is built on integrity, responsibility, transparency, and long-term value creation.',
            ],
            [
                'number' => 10,
                'title' => 'Contributes to Nation Building',
                'items' => [
                    'Entrepreneurs create businesses.',
                    'Businesses create employment.',
                    'Employment strengthens families.',
                    'Strong families build a prosperous nation.',
                ],
                'text' => 'Business education is one of the strongest foundations for a Developed India (Viksit Bharat 2047).',
            ],
        ],
        'for_everyone' => [
            'title' => 'Business Education is for Everyone',
            'intro' => 'At Business Navachar School (BNS), we believe business education should not be limited to business graduates.',
            'intro_2' => 'It should be available to:',
            'programs' => [
                ['icon' => '👧', 'label' => 'School Students'],
                ['icon' => '🎓', 'label' => 'College Youth'],
                ['icon' => '👩', 'label' => 'Women Entrepreneurs'],
                ['icon' => '💼', 'label' => 'Job Professionals'],
                ['icon' => '🏢', 'label' => 'Business Owners'],
            ],
            'outro' => 'Because every individual makes financial decisions, creates value, and contributes to society.',
        ],
        'approach' => [
            'title' => 'The BNS Approach',
            'intro' => 'Business Navachar School transforms learning through:',
            'items' => [
                'Weekly Business School Model',
                'Practical Learning',
                'Live Projects',
                'Business Case Studies',
                'Research-Based Activities',
                'Expert Mentorship',
                'Industry Interaction',
                'Leadership Development',
                'Financial Literacy',
                'Entrepreneurial Thinking',
            ],
        ],
        'belief' => [
            'title' => 'Our Belief',
            'text' => 'Business Education is not only about starting a business. It is about developing the knowledge, mindset, skills, and confidence to create opportunities, solve problems, build prosperity, and lead with purpose.',
        ],
        'closing' => [
            'brand' => 'Business Navachar School',
            'subtitle' => 'Business Education for Every Indian',
            'tagline' => 'Learn Prosperity • Create Prosperity • Build a Developed India',
            'hindi' => '( ज्ञान | नवाचार | समृद्धि )',
        ],
    ],

    'prosperity_mission_page' => [
        'title' => "India's Prosperity Mission",
        'subtitle' => 'Building a Prosperous India Through Business Education',
        'label' => 'Prosperity Mission',
        'intro' => [
            'India is one of the world\'s youngest and fastest-growing nations.',
            'We have talent.',
            'We have creativity.',
            'We have ambition.',
            'We have unlimited opportunities.',
            'The next chapter of India\'s growth will not be written by natural resources alone—it will be written by knowledge, innovation, entrepreneurship, and business leadership.',
            'At Business Navachar School (BNS), we believe that prosperity is not a privilege for a few; it is a possibility for every Indian.',
            'Our mission is to empower individuals with practical business education so they can create opportunities, generate employment, strengthen the economy, and contribute to nation-building.',
        ],
        'national_mission' => [
            'title' => 'Our National Mission',
            'intro' => 'We envision an India where:',
            'items' => [
                'Every Student develops an entrepreneurial mindset.',
                'Every Youth becomes an opportunity creator.',
                'Every Woman achieves financial independence.',
                'Every Professional continues to grow through lifelong learning.',
                'Every Business Owner builds sustainable and scalable enterprises.',
                'Every Family experiences financial stability and prosperity.',
            ],
        ],
        'why_prosperity' => [
            'title' => 'Why Prosperity Matters',
            'intro' => 'Prosperity creates:',
            'items' => [
                'Better Education',
                'Better Healthcare',
                'Better Employment',
                'Stronger Families',
                'Stronger Communities',
                'Stronger Businesses',
                'A Stronger Nation',
            ],
            'outro' => 'When individuals prosper, the nation prospers.',
        ],
        'role_of_education' => [
            'title' => 'The Role of Business Education',
            'intro' => 'We believe business education is one of the most powerful tools for national development because it helps people:',
            'items' => [
                'Think like entrepreneurs.',
                'Solve real-world problems.',
                'Create value for society.',
                'Build sustainable businesses.',
                'Generate employment.',
                'Manage finances wisely.',
                'Lead with integrity and innovation.',
            ],
            'outro' => 'Business education transforms learners into contributors to economic growth.',
        ],
        'movement' => [
            'title' => 'The BNS Prosperity Movement',
            'intro' => 'Business Navachar School is building a nationwide ecosystem through its Weekly Business School model for:',
            'programs' => [
                ['icon' => '👧', 'label' => 'School Students'],
                ['icon' => '🎓', 'label' => 'College Youth'],
                ['icon' => '👩', 'label' => 'Women Entrepreneurs'],
                ['icon' => '💼', 'label' => 'Job Professionals'],
                ['icon' => '🏢', 'label' => 'Business Owners'],
            ],
            'outro' => 'By nurturing entrepreneurial thinking and practical business skills, BNS aims to create a ripple effect of prosperity across every city, every village, and every family in India.',
        ],
        'viksit_bharat' => [
            'title' => 'Our Vision for Viksit Bharat 2047',
            'intro' => 'We proudly support the national vision of Viksit Bharat 2047 by developing citizens who are:',
            'items' => [
                'Knowledge-Driven',
                'Innovation-Oriented',
                'Financially Literate',
                'Entrepreneurial',
                'Ethical Leaders',
                'Employment Creators',
                'Nation Builders',
            ],
        ],
        'commitment' => [
            'title' => 'Our Commitment',
            'intro' => 'At Business Navachar School, we are committed to:',
            'items' => [
                'Making Business Education accessible to every Indian.',
                'Promoting entrepreneurship and innovation.',
                'Developing future-ready business leaders.',
                'Creating employment through enterprise.',
                'Strengthening India\'s economy through education.',
            ],
        ],
        'belief' => [
            'title' => 'Our Belief',
            'lines' => [
                'A prosperous India is built by prosperous families.',
                'Prosperous families are built by empowered individuals.',
                'Empowered individuals are created through education.',
                'Business education creates prosperity.',
            ],
        ],
        'closing' => [
            'brand' => 'BUSINESS NAVACHAR SCHOOL',
            'subtitle' => "India's Mission for Prosperity Through Business Education",
            'tagline' => 'Learn Prosperity • Create Prosperity • Build a Developed India',
            'hindi' => '( ज्ञान | नवाचार | समृद्धि )',
        ],
    ],

    'vision_2047_page' => [
        'title' => 'Vision 2047',
        'subtitle' => 'Building a Developed India Through Business Education',
        'label' => 'Vision 2047',
        'intro' => [
            'India is on a transformative journey towards becoming a Developed Nation by 2047.',
            'At Business Navachar School (BNS), we believe that this vision can only be achieved when education goes beyond academic excellence and prepares citizens to become entrepreneurs, innovators, wealth creators, and ethical leaders.',
            'Our Vision 2047 is to build a generation that creates opportunities, generates employment, strengthens the economy, and contributes to national prosperity.',
        ],
        'our_vision' => [
            'title' => 'Our Vision for 2047',
            'text' => 'By the year 2047, Business Navachar School aspires to become India\'s largest practical business education ecosystem, empowering millions of learners through structured Weekly Business Schools across the nation.',
        ],
        'goals_heading' => 'Our 2047 Goals',
        'goals' => [
            [
                'number' => 1,
                'title' => 'Business Education for Every Indian',
                'text' => 'Make practical business education accessible to School Students, College Youth, Women, Job Professionals, and Business Owners across India.',
            ],
            [
                'number' => 2,
                'title' => 'Nationwide Weekly Business Schools',
                'text' => 'Establish Business Navachar Schools in every district and major city, creating a strong national learning network.',
            ],
            [
                'number' => 3,
                'title' => 'Entrepreneurial India',
                'text' => 'Develop lakhs of entrepreneurs who create innovative businesses and generate employment opportunities.',
            ],
            [
                'number' => 4,
                'title' => 'Financially Literate Society',
                'text' => 'Empower individuals and families with financial literacy, wealth creation, and responsible money management.',
            ],
            [
                'number' => 5,
                'title' => 'Women-Led Prosperity',
                'text' => 'Support women in becoming confident entrepreneurs, business owners, and financially independent leaders.',
            ],
            [
                'number' => 6,
                'title' => 'Youth Leadership',
                'text' => 'Equip young people with entrepreneurial thinking, leadership, innovation, and business skills from an early age.',
            ],
            [
                'number' => 7,
                'title' => 'Strong Business Ecosystem',
                'text' => 'Build a nationwide network connecting learners with mentors, entrepreneurs, investors, industry experts, and business opportunities.',
            ],
            [
                'number' => 8,
                'title' => 'World-Class Business Learning',
                'text' => 'Continuously strengthen academic quality through collaborations with experienced educators, industry leaders, and Faculties of IIM.',
            ],
            [
                'number' => 9,
                'title' => 'Technology-Driven Learning',
                'text' => 'Leverage AI, digital platforms, mobile applications, and hybrid learning to make business education accessible anytime, anywhere.',
            ],
            [
                'number' => 10,
                'title' => 'Nation Building Through Prosperity',
                'text' => 'Contribute to Viksit Bharat 2047 by creating employment creators, ethical business leaders, and responsible citizens.',
            ],
        ],
        'commitment' => [
            'title' => 'Our Commitment',
            'intro' => 'We are committed to building an education ecosystem where:',
            'items' => [
                'Every learner understands business.',
                'Every family becomes financially stronger.',
                'Every entrepreneur creates value for society.',
                'Every business contributes to economic growth.',
                'Every citizen becomes a partner in building a Developed India.',
            ],
        ],
        'dream' => [
            'title' => 'Our Dream for India',
            'intro' => 'We dream of an India where:',
            'items' => [
                'Business Education becomes a part of mainstream learning.',
                'Entrepreneurship becomes a preferred career choice.',
                'Innovation drives economic growth.',
                'Prosperity reaches every home.',
                'Every citizen has the confidence to create opportunities.',
                'India becomes a global leader in entrepreneurship, innovation, and business education.',
            ],
        ],
        'statement' => [
            'title' => 'Vision 2047 Statement',
            'quote' => 'By 2047, Business Navachar School envisions a prosperous, entrepreneurial, and innovation-driven India where every citizen has access to practical business education, every learner possesses entrepreneurial thinking, every family experiences financial prosperity, and every business contributes to building a Viksit Bharat.',
        ],
        'closing' => [
            'brand' => 'BUSINESS NAVACHAR SCHOOL',
            'subtitle' => 'Vision 2047 – Business Education for Every Indian',
            'motto' => 'Knowledge | Innovation | Prosperity',
            'tagline' => 'Learn Prosperity • Create Prosperity • Build a Developed India',
        ],
    ],

    'founder_page' => [
        'title' => "Founder's Message",
        'subtitle' => 'Business Navachar School',
        'salutation' => 'Dear Learners, Parents, Entrepreneurs, and Future Leaders,',
        'paragraphs' => [
            'Welcome to Business Navachar School (BNS).',
            'I strongly believe that education should not only prepare us to earn a degree—it should prepare us to build a meaningful life, create opportunities, and contribute to society.',
            'Today, India has one of the world\'s youngest populations. Every year, millions of talented students graduate with dreams for a better future. Yet many still struggle because they have never been taught practical business skills, financial literacy, entrepreneurship, leadership, or wealth creation.',
            'This realization inspired the establishment of Business Navachar School.',
            'BNS is more than an educational institution. It is a Weekly Business School dedicated to empowering School Students, College Youth, Women, Job Professionals, and Business Owners with practical business knowledge and entrepreneurial thinking.',
            'At BNS, learning goes beyond classrooms. Through practical projects, business case studies, research activities, industry interaction, expert mentorship, and collaborative learning, we help learners develop the confidence to create opportunities rather than simply wait for them.',
            'To ensure academic excellence, Business Navachar School has established an Academic Collaboration with Faculties of IIM for mentor development, business learning methodologies, and academic enrichment. Eligible participants will also receive Participation and Appreciation Certificates from the Faculties of IIM, adding value to their learning journey.',
        ],
        'vision_heading' => 'Our vision is simple yet powerful:',
        'vision_text' => 'To make Business Education accessible to every Indian and build a prosperous, entrepreneurial, and developed nation.',
        'belief' => 'We believe that when knowledge meets innovation, innovation creates prosperity, and prosperity strengthens families, communities, and ultimately the nation.',
        'mission_invite' => 'Every learner who joins BNS becomes part of a larger mission—to build businesses, create employment, strengthen the economy, and contribute to the vision of Viksit Bharat 2047.',
        'invitation' => 'I warmly invite you to become a part of this movement.',
        'closing_lines' => [
            'Let us learn.',
            'Let us innovate.',
            'Let us create prosperity.',
            'Together, let us build a Developed India.',
        ],
        'signature' => [
            'closing' => 'With best wishes,',
            'name' => 'Dr. Mehul Rupani',
            'title' => 'Founder',
            'organization' => 'Business Navachar School (BNS)',
        ],
    ],
];
