<?php

return [

    'hub' => [
        'title' => 'Admissions',
        'subtitle' => "India's Complete Online Direct Admission System",
        'intro' => 'Business Navachar School (BNS) offers a full admission ecosystem — not just a form. Explore programs, check eligibility, apply online, upload documents, and begin your business education journey.',
        'intro_2' => 'Select any section below to learn more, or start your application with Book Your Spot Now.',
    ],

    'menu' => [
        ['label' => 'Book Your Spot Now', 'slug' => 'apply-now', 'icon' => 'fas fa-rocket', 'group' => 'Get Started', 'description' => 'Choose your program and complete the BNS registration form online.'],
        ['label' => 'Online Admission', 'slug' => 'online-admission', 'icon' => 'fas fa-laptop', 'group' => 'Get Started', 'description' => 'Learn how BNS online direct admission works from anywhere in India.'],
        ['label' => 'Admission Process', 'slug' => 'admission-process', 'icon' => 'fas fa-list-ol', 'group' => 'Get Started', 'description' => 'Step-by-step guide from application to batch allotment.'],
        ['label' => 'Eligibility Criteria', 'slug' => 'eligibility-criteria', 'icon' => 'fas fa-user-check', 'group' => 'Program Details', 'description' => 'Check who can apply for each BNS program category.'],
        ['label' => 'Programs', 'slug' => 'programs', 'icon' => 'fas fa-graduation-cap', 'group' => 'Program Details', 'description' => 'Explore all BNS business education programs.'],
        ['label' => 'Course Duration', 'slug' => 'course-duration', 'icon' => 'fas fa-clock', 'group' => 'Program Details', 'description' => 'Program length and flexible learning schedules.'],
        ['label' => 'Program Fees', 'slug' => 'program-fees', 'icon' => 'fas fa-rupee-sign', 'group' => 'Program Details', 'description' => 'Transparent registration, admission, and course fees.'],
        ['label' => 'Scholarships', 'slug' => 'scholarships', 'icon' => 'fas fa-award', 'group' => 'Program Details', 'description' => 'Merit-based and need-based financial support.'],
        ['label' => 'Batch Timings', 'slug' => 'batch-timings', 'icon' => 'fas fa-calendar-day', 'group' => 'Program Details', 'description' => 'Morning, afternoon, evening, and weekend batches.'],
        ['label' => 'Academic Calendar', 'slug' => 'academic-calendar', 'icon' => 'fas fa-calendar-alt', 'group' => 'Program Details', 'description' => 'Important dates for admissions, sessions, and workshops.'],
        ['label' => 'Introduction Session', 'slug' => 'introduction-session', 'icon' => 'fas fa-chalkboard-teacher', 'group' => 'Guidance & Sessions', 'description' => 'Attend a free session before you enroll.'],
        ['label' => 'Book Counselling', 'slug' => 'book-counselling', 'icon' => 'fas fa-comments', 'group' => 'Guidance & Sessions', 'description' => 'One-on-one admission counseling with our team.'],
        ['label' => 'Download Prospectus', 'slug' => 'download-prospectus', 'icon' => 'fas fa-file-pdf', 'group' => 'Resources', 'description' => 'Full academic prospectus and curriculum details.'],
        ['label' => 'Required Documents', 'slug' => 'required-documents', 'icon' => 'fas fa-folder-open', 'group' => 'Resources', 'description' => 'Documents to keep ready for online admission.'],
        ['label' => 'Fee Payment', 'slug' => 'fee-payment', 'icon' => 'fas fa-credit-card', 'group' => 'Fees & Policies', 'description' => 'Pay registration and admission fees securely online.'],
        ['label' => 'EMI Options', 'slug' => 'emi-options', 'icon' => 'fas fa-hand-holding-usd', 'group' => 'Fees & Policies', 'description' => 'Flexible installment and EMI payment plans.'],
        ['label' => 'Refund Policy', 'slug' => 'refund-policy', 'icon' => 'fas fa-undo', 'group' => 'Fees & Policies', 'description' => 'Clear and fair refund terms and process.'],
        ['label' => 'FAQs', 'slug' => 'faqs', 'icon' => 'fas fa-question-circle', 'group' => 'Help & Support', 'description' => 'Answers to common admission questions.'],
        ['label' => 'Contact Admission Office', 'slug' => 'contact-admission-office', 'icon' => 'fas fa-headset', 'group' => 'Help & Support', 'description' => 'Call, WhatsApp, or visit our admission team.'],
    ],

    'categories' => [
        'School Students',
        'College Students',
        'Women Entrepreneurs',
        'Job Professionals',
        'Business Owners',
    ],

    'programs' => [
        'School Students Program',
        'College Students Program',
        'Women Entrepreneurs Program',
        'Job Professionals Program',
        'Business Owners & Business Professionals Program',
    ],

    'year_levels' => ['Std. 6–8', 'Std. 9–11', 'Diploma', 'Undergraduate', 'Postgraduate', 'Working Professional', 'Business Owner'],
    'batches' => ['Morning', 'Afternoon', 'Evening', 'Weekend'],
    'cities' => ['Rajkot', 'Ahmedabad', 'Surat', 'Vadodara', 'Other'],
    'centres' => ['BNS Rajkot Main Centre', 'BNS Ahmedabad Centre', 'BNS Surat Centre', 'Online Learning Centre'],

    'trust' => [
        'title' => 'Why Trust BNS Admissions',
        'items' => [
            'Academic Collaboration with Faculties of IIM',
            'Participation & Appreciation Certificates by Faculties of IIM (for eligible participants)',
            'Weekly Business School',
            'Practical Business Education',
            'Industry Expert Mentors',
            'Digital Learning Platform',
        ],
    ],

    'ctas' => [
        ['label' => 'Book Your Spot Now', 'url' => '/register', 'icon' => 'fas fa-rocket', 'style' => 'primary'],
        ['label' => 'Book Free Introduction Session', 'url' => '/admissions/introduction-session', 'icon' => 'fas fa-calendar-check', 'style' => 'blue'],
        ['label' => 'Talk to Admission Counselor', 'url' => '/admissions/book-counselling', 'icon' => 'fas fa-user-tie', 'style' => 'dark'],
        ['label' => 'WhatsApp Now', 'url' => '/whatsapp-support', 'icon' => 'fab fa-whatsapp', 'style' => 'whatsapp'],
        ['label' => 'Pay Registration Fee', 'url' => '/admissions/fee-payment', 'icon' => 'fas fa-credit-card', 'style' => 'orange'],
        ['label' => 'Start Your Business Learning Journey', 'url' => '/register', 'icon' => 'fas fa-graduation-cap', 'style' => 'primary'],
    ],

    'after_admission' => [
        'title' => 'After Admission',
        'items' => [
            'Admission Confirmation',
            'Welcome Letter',
            'Student ID',
            'Receipt',
            'Batch Allotment',
            'Class Schedule',
            'WhatsApp Community Join',
            'Student Portal Login',
            'Learning App Access',
        ],
    ],

    'student_dashboard' => [
        'title' => 'Student Dashboard',
        'items' => [
            'My Profile', 'My Program', 'Attendance', 'Assignments', 'Projects',
            'Certificates', 'Fee Status', 'Timetable', 'Notices', 'Download Resources',
        ],
    ],

    'office' => [
        'counselor' => 'BNS Admission Counselor',
        'phone' => '+91 98250 98250',
        'whatsapp' => '+91 98250 98250',
        'email' => 'admissions@businessnavacharschool.com',
        'address' => 'Rajkot, Gujarat - 360005',
        'maps_embed_url' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3691.0!2d70.8022!3d22.3039!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjLCsDE4JzE0LjAiTiA3MMKwNDgnMDguMCJF!5e0!3m2!1sen!2sin!4v1',
    ],

    'pages' => [
        'online-admission' => [
            'title' => 'Online Admission',
            'subtitle' => 'Apply to Business Navachar School from anywhere in India',
            'intro' => 'BNS offers a complete online direct admission system. Select your program, complete your application, upload documents, and pay fees — all in one guided flow.',
            'items' => [
                'Choose your student category and program',
                'Complete the digital admission form',
                'Upload required documents securely',
                'Pay registration and admission fees online',
                'Receive instant confirmation and student ID',
            ],
        ],
        'admission-process' => [
            'title' => 'Admission Process',
            'subtitle' => 'Your Journey Begins Here',
            'intro' => 'Joining Business Navachar School (BNS) is simple, transparent, and student-friendly. Our admission process is designed to help every learner choose the right program and begin their journey towards entrepreneurship, leadership, and prosperity.',
            'steps' => [
                [
                    'number' => 1,
                    'title' => 'Explore Our Programs',
                    'intro' => 'Choose the program that best matches your profile.',
                    'programs' => [
                        ['icon' => '👧', 'label' => 'School Students Program'],
                        ['icon' => '🎓', 'label' => 'College Students Program'],
                        ['icon' => '👩', 'label' => 'Women Entrepreneurs Program'],
                        ['icon' => '💼', 'label' => 'Job Professionals Program'],
                        ['icon' => '🏢', 'label' => 'Business Owners & Business Professionals Program'],
                    ],
                ],
                [
                    'number' => 2,
                    'title' => 'Check Eligibility',
                    'intro' => 'Review the eligibility criteria for your selected program.',
                    'note' => 'Ensure you meet the age, educational, or professional requirements before applying.',
                    'link' => ['label' => 'View Eligibility Criteria', 'slug' => 'eligibility-criteria'],
                ],
                [
                    'number' => 3,
                    'title' => 'Book a Free Introduction Session',
                    'intro' => 'Attend a complimentary Introduction Session to understand:',
                    'items' => [
                        'Business Navachar School Vision',
                        'Course Structure',
                        'Learning Methodology',
                        'Weekly Business School Model',
                        'Program Benefits',
                        'Certification Process',
                        'Academic Collaboration with Faculties of IIM',
                        'Career & Business Opportunities',
                    ],
                    'link' => ['label' => 'Book Introduction Session', 'slug' => 'introduction-session'],
                ],
                [
                    'number' => 4,
                    'title' => 'Counselling Session',
                    'intro' => 'Meet with our Admission Counselor to:',
                    'items' => [
                        'Select the Right Program',
                        'Understand Your Career Goals',
                        'Resolve Your Questions',
                        'Receive Admission Guidance',
                    ],
                    'link' => ['label' => 'Book Counselling', 'slug' => 'book-counselling'],
                ],
                [
                    'number' => 5,
                    'title' => 'Submit Online Application',
                    'intro' => 'Complete the Online Admission Form with:',
                    'items' => [
                        'Personal Details',
                        'Educational Details',
                        'Professional Information (if applicable)',
                        'Preferred Program',
                        'Preferred Centre',
                    ],
                    'link' => ['label' => 'Book Your Spot Now', 'route' => 'register'],
                ],
                [
                    'number' => 6,
                    'title' => 'Upload Required Documents',
                    'intro' => 'Submit the necessary documents for verification.',
                    'examples_label' => 'Examples:',
                    'examples' => [
                        ['icon' => '📷', 'label' => 'Passport Size Photograph'],
                        ['icon' => '🆔', 'label' => 'Aadhaar Card'],
                        ['icon' => '📄', 'label' => 'Educational Certificates'],
                        ['icon' => '🏫', 'label' => 'School / College ID (if applicable)'],
                        ['icon' => '💼', 'label' => 'Professional ID / Business Proof (if applicable)'],
                    ],
                    'link' => ['label' => 'View Required Documents', 'slug' => 'required-documents'],
                ],
                [
                    'number' => 7,
                    'title' => 'Pay Admission Fee',
                    'intro' => 'Secure your seat by completing the admission payment through our secure online payment gateway.',
                    'options_label' => 'Payment Options:',
                    'options' => [
                        ['icon' => '💳', 'label' => 'UPI'],
                        ['icon' => '🏦', 'label' => 'Net Banking'],
                        ['icon' => '💳', 'label' => 'Credit Card'],
                        ['icon' => '💳', 'label' => 'Debit Card'],
                        ['icon' => '📱', 'label' => 'Digital Wallets'],
                    ],
                    'link' => ['label' => 'Pay Admission Fee', 'slug' => 'fee-payment'],
                ],
                [
                    'number' => 8,
                    'title' => 'Admission Confirmation',
                    'intro' => 'Once your documents and payment are verified, you will receive:',
                    'items' => [
                        'Admission Confirmation',
                        'Welcome Letter',
                        'Fee Receipt',
                        'Student ID Number',
                        'Batch Allocation',
                    ],
                    'style' => 'success',
                ],
                [
                    'number' => 9,
                    'title' => 'Student Onboarding',
                    'intro' => 'After admission, students receive access to:',
                    'examples' => [
                        ['icon' => '📱', 'label' => 'Student Portal'],
                        ['icon' => '📚', 'label' => 'Digital Learning Resources'],
                        ['icon' => '📅', 'label' => 'Academic Calendar'],
                        ['icon' => '📝', 'label' => 'Weekly Timetable'],
                        ['icon' => '👥', 'label' => 'WhatsApp Learning Community'],
                        ['icon' => '🎒', 'label' => 'Student Welcome Kit'],
                    ],
                ],
                [
                    'number' => 10,
                    'title' => 'Start Your Learning Journey',
                    'intro' => 'Attend your first Weekly Business School session and begin learning through:',
                    'items' => [
                        'Practical Business Education',
                        'Live Projects',
                        'Business Case Studies',
                        'Research Activities',
                        'Expert Mentorship',
                        'Business Networking',
                    ],
                ],
            ],
            'certification' => [
                'title' => 'Certification',
                'intro' => 'Eligible participants who successfully complete the required attendance and program activities will receive:',
                'items' => [
                    ['icon' => '🏅', 'label' => 'Participation Certificate'],
                    ['icon' => '🏆', 'label' => 'Appreciation Certificate'],
                ],
                'outro' => 'These certificates will be awarded by the Faculties of IIM as per the academic framework and program guidelines.',
            ],
            'need_help' => [
                'title' => 'Need Help?',
                'intro' => 'Our Admission Team is always available to guide you throughout the admission process.',
                'contacts' => [
                    ['icon' => '📞', 'label' => 'Call Us', 'type' => 'phone'],
                    ['icon' => '💬', 'label' => 'WhatsApp Us', 'type' => 'whatsapp'],
                    ['icon' => '📧', 'label' => 'Email Us', 'type' => 'email'],
                    ['icon' => '📍', 'label' => 'Visit Our Admission Office', 'type' => 'office', 'slug' => 'contact-admission-office'],
                ],
            ],
            'ready' => [
                'title' => 'Ready to Begin?',
                'paragraphs' => [
                    'Your journey towards entrepreneurship, leadership, financial prosperity, and lifelong learning starts with one decision.',
                    "Join Business Navachar School and become a part of India's Prosperity Movement.",
                ],
            ],
            'actions' => [
                ['label' => 'Book Your Spot Now', 'route' => 'register', 'icon' => 'fas fa-rocket', 'style' => 'primary'],
                ['label' => 'Book Free Introduction Session', 'slug' => 'introduction-session', 'icon' => 'fas fa-calendar-check', 'style' => 'blue'],
                ['label' => 'Talk to an Admission Counselor', 'slug' => 'book-counselling', 'icon' => 'fas fa-user-tie', 'style' => 'dark'],
                ['label' => 'WhatsApp Us', 'route' => 'whatsapp.support', 'icon' => 'fab fa-whatsapp', 'style' => 'whatsapp'],
            ],
            'closing' => [
                'brand' => 'BUSINESS NAVACHAR SCHOOL',
                'subtitle' => 'Business Education for Every Indian',
                'tagline' => 'Learn Prosperity • Create Prosperity • Build a Developed India',
                'hindi' => '( ज्ञान | नवाचार | समृद्धि )',
            ],
        ],
        'eligibility-criteria' => array_merge(
            ['title' => 'Eligibility Criteria'],
            require __DIR__.'/bns_eligibility_criteria.php'
        ),
        'programs' => [
            'title' => 'Programs',
            'subtitle' => 'Business Education for Every Indian',
            'intro' => 'BNS offers specialized business education programs for every stage of your journey.',
            'items' => [
                'School Students Program',
                'College Students Program',
                'Women Entrepreneurs Program',
                'Job Professionals Program',
                'Business Owners & Business Professionals Program',
                'Business and Job Professional Batch Program',
            ],
        ],
        'course-duration' => [
            'title' => 'Course Duration',
            'subtitle' => 'Flexible learning schedules',
            'intro' => 'Program duration depends on the selected course and batch. Contact our admission office for the latest schedule.',
            'items' => [
                'Foundation programs: 3–6 months',
                'Advanced business programs: 6–12 months',
                'Weekly Business School sessions',
                'Weekend and evening batches available',
            ],
        ],
        'program-fees' => [
            'title' => 'Program Fees',
            'subtitle' => 'Transparent fee structure',
            'intro' => 'BNS maintains a clear fee structure with registration fee, admission fee, and course fee components.',
            'items' => [
                'Registration Fee',
                'Admission Fee',
                'Course Fee',
                'GST as applicable',
                'Scholarship adjustments where eligible',
                'Discounts for early admission',
            ],
        ],
        'scholarships' => [
            'title' => 'Scholarships',
            'subtitle' => 'Financial support for deserving learners',
            'intro' => 'BNS offers scholarships and fee concessions for eligible students based on merit, need, and program criteria.',
            'items' => [
                'Merit-based scholarships',
                'Women entrepreneur scholarships',
                'Early bird admission discounts',
                'Referral benefits',
                'Special schemes for students and professionals',
            ],
        ],
        'batch-timings' => [
            'title' => 'Batch Timings',
            'subtitle' => 'Learn at a time that suits you',
            'intro' => 'Choose from morning, afternoon, evening, or weekend batches at your preferred centre.',
            'items' => ['Morning Batch', 'Afternoon Batch', 'Evening Batch', 'Weekend Batch'],
        ],
        'academic-calendar' => [
            'title' => 'Academic Calendar',
            'subtitle' => 'Plan your BNS learning journey',
            'intro' => 'View important dates for admissions, introduction sessions, batch starts, workshops, and examinations.',
            'items' => [
                'New batch admissions — ongoing',
                'Introduction sessions — every week',
                'Workshops & masterclasses — monthly',
                'Contact admission office for centre-wise calendar',
            ],
        ],
        'introduction-session' => [
            'title' => 'Introduction Session',
            'subtitle' => 'Experience BNS before you enroll',
            'intro' => 'Attend a free introduction session to understand our programs, faculty, learning methodology, and career outcomes.',
            'admission_form_url' => '/introduction-session-admission',
            'items' => [
                'Free for all prospective students',
                'Online and offline sessions available',
                'Meet admission counselors',
                'Get program recommendations',
                'Book your slot online or via WhatsApp',
            ],
        ],
        'book-counselling' => [
            'title' => 'Book Counselling',
            'subtitle' => 'Personalized admission guidance',
            'intro' => 'Speak with a BNS admission counselor to choose the right program, understand fees, and plan your learning path.',
            'items' => [
                'One-on-one counselling sessions',
                'Program selection guidance',
                'Career and business pathway advice',
                'Fee and scholarship consultation',
                'Book via contact form, call, or WhatsApp',
            ],
        ],
        'download-prospectus' => [
            'title' => 'Download Prospectus',
            'subtitle' => 'Official BNS Prospectus',
            'intro' => 'Get the full academic prospectus with curriculum, faculty, and certification details.',
            'items' => ['Academic framework', 'Learning outcomes', 'Certification details', 'Admission guidelines'],
            'download_url' => '#',
        ],
        'required-documents' => [
            'title' => 'Required Documents',
            'subtitle' => 'Keep these documents ready',
            'intro' => 'Upload the following documents during online admission. Requirements may vary by program.',
            'items' => [
                'Passport Size Photo',
                'Aadhaar Card',
                'School / College ID',
                'Last Marksheet',
                'Bonafide Certificate',
                'Graduation Certificate (if applicable)',
                'Experience Letter (for professionals)',
                'Business Proof (for business owners)',
            ],
        ],
        'fee-payment' => [
            'title' => 'Fee Payment',
            'subtitle' => 'Secure online payment',
            'intro' => 'Pay registration fee, admission fee, and course fee securely through our online payment system.',
            'items' => [
                'Registration Fee',
                'Admission Fee',
                'Course Fee',
                'GST',
                'Scholarship Adjustment',
                'Discount',
                'Total Payable — shown before payment',
                'Online Payment — UPI, Card, Net Banking',
            ],
        ],
        'emi-options' => [
            'title' => 'EMI Options',
            'subtitle' => 'Flexible payment plans',
            'intro' => 'BNS offers EMI and installment options on selected programs. Speak with our admission team for available plans.',
            'items' => [
                'Easy monthly installments',
                'Partner finance options',
                'Custom payment plans for eligible programs',
                'Contact admission office for EMI eligibility',
            ],
        ],
        'refund-policy' => [
            'title' => 'Refund Policy',
            'subtitle' => 'Fair and transparent refunds',
            'intro' => 'Our refund policy is designed to be clear and fair. Please read the terms before payment.',
            'items' => [
                'Refund requests must be submitted in writing',
                'Registration fee terms as per admission policy',
                'Course fee refunds subject to program terms',
                'Processing timeline communicated by admission office',
            ],
        ],
        'faqs' => [
            'title' => 'Frequently Asked Questions (FAQs)',
            'subtitle' => 'Business Navachar School (BNS)',
            'intro' => 'Find clear answers about BNS programs, admissions, learning model, certificates, fees, and how to get started.',
            'questions' => [
                [
                    'number' => 1,
                    'question' => 'What is Business Navachar School (BNS)?',
                    'answer' => 'Business Navachar School (BNS) is a Weekly Business School that provides practical business education, entrepreneurship, leadership, financial literacy, and innovation-based learning for learners of different age groups and professions.',
                ],
                [
                    'number' => 2,
                    'question' => 'Who can join BNS?',
                    'answer' => 'BNS offers specialized programs for:',
                    'items' => [
                        ['icon' => '👧', 'label' => 'School Students (Std. 6, 7, 8, 9 & 11)'],
                        ['icon' => '🎓', 'label' => 'College Students'],
                        ['icon' => '👩', 'label' => 'Women Entrepreneurs'],
                        ['icon' => '💼', 'label' => 'Job Professionals'],
                        ['icon' => '🏢', 'label' => 'Business Owners & Business Professionals'],
                    ],
                ],
                [
                    'number' => 3,
                    'question' => 'Is this an online or offline program?',
                    'answer' => 'BNS follows a Hybrid Learning Model, including offline classroom sessions supported by digital learning resources.',
                ],
                [
                    'number' => 4,
                    'question' => 'How many hours are the classes?',
                    'items' => [
                        '4 Hours Every Week',
                        '16 Hours Every Month',
                        '160–200 Hours Every Year',
                    ],
                ],
                [
                    'number' => 5,
                    'question' => 'How long are the programs?',
                    'items' => [
                        'School Students – 5 Years',
                        'College Students – 3 Years',
                        'Women Entrepreneurs – 2 Years',
                        'Job Professionals – 1 Year',
                        'Business Owners – 1 Year',
                    ],
                ],
                [
                    'number' => 6,
                    'question' => 'What is the teaching methodology?',
                    'answer' => 'Students learn through:',
                    'items' => [
                        'Practical Learning',
                        'Live Projects',
                        'Business Case Studies',
                        'Group Discussions',
                        'Research Activities',
                        'Business Presentations',
                        'Industry Exposure',
                        'Expert Mentorship',
                    ],
                ],
                [
                    'number' => 7,
                    'question' => 'What topics are covered?',
                    'answer' => 'Topics include:',
                    'items' => [
                        'Entrepreneurship',
                        'Financial Literacy',
                        'Leadership',
                        'Business Strategy',
                        'Marketing',
                        'Sales',
                        'Branding',
                        'AI & Digital Business',
                        'Innovation',
                        'Communication Skills',
                        'Business Growth',
                    ],
                ],
                [
                    'number' => 8,
                    'question' => 'Do I need prior business experience?',
                    'answer' => 'No. Beginners and experienced professionals are both welcome.',
                ],
                [
                    'number' => 9,
                    'question' => 'Is there an entrance exam?',
                    'answer' => 'No. Admission is based on eligibility and completion of the admission process.',
                ],
                [
                    'number' => 10,
                    'question' => 'Is the Introduction Session compulsory?',
                    'answer' => 'It is highly recommended to help you understand the program before admission.',
                ],
                [
                    'number' => 11,
                    'question' => 'What certificates will I receive?',
                    'answer' => 'Eligible participants receive:',
                    'items' => [
                        'Participation Certificate',
                        'Appreciation Certificate',
                    ],
                    'outro' => 'These certificates are awarded by the Faculties of IIM as per the academic framework and program guidelines.',
                ],
                [
                    'number' => 12,
                    'question' => 'What is the Academic Collaboration with Faculties of IIM?',
                    'answer' => 'Business Navachar School has an Academic Collaboration with Faculties of IIM for mentor development, business learning methodologies, and academic excellence.',
                ],
                [
                    'number' => 13,
                    'question' => 'Will I receive study materials?',
                    'answer' => 'Yes. Students receive access to:',
                    'items' => [
                        'Learning Resources',
                        'Assignments',
                        'Business Projects',
                        'Digital Resources',
                        'Business Learning Kit (where applicable)',
                    ],
                ],
                [
                    'number' => 14,
                    'question' => 'Are classes conducted every week?',
                    'answer' => 'Yes. BNS follows a structured Weekly Business School model.',
                ],
                [
                    'number' => 15,
                    'question' => 'Can working professionals attend?',
                    'answer' => 'Yes. Dedicated programs are available for Job Professionals and Business Owners.',
                ],
                [
                    'number' => 16,
                    'question' => 'Is there any age limit?',
                    'answer' => 'Each program has its own eligibility criteria. Please refer to the Eligibility section.',
                    'link' => ['label' => 'View Eligibility Criteria', 'slug' => 'eligibility-criteria'],
                ],
                [
                    'number' => 17,
                    'question' => 'Can women with no business experience join?',
                    'answer' => 'Yes. The Women Entrepreneurs Program is designed for beginners as well as existing entrepreneurs.',
                ],
                [
                    'number' => 18,
                    'question' => 'Is this useful for college students?',
                    'answer' => 'Absolutely. The program develops entrepreneurship, leadership, business skills, and career readiness alongside college education.',
                ],
                [
                    'number' => 19,
                    'question' => 'Can business owners join?',
                    'answer' => 'Yes. The Business to Empire Business School is specially designed for business owners and entrepreneurs.',
                ],
                [
                    'number' => 20,
                    'question' => 'What are the class timings?',
                    'answer' => 'Batch timings are announced before each intake.',
                    'link' => ['label' => 'View Batch Timings', 'slug' => 'batch-timings'],
                ],
                [
                    'number' => 21,
                    'question' => 'How do I apply?',
                    'answer' => 'Simply complete the online admission process through Book Your Spot Now on our website.',
                    'link' => ['label' => 'Book Your Spot Now', 'route' => 'register'],
                ],
                [
                    'number' => 22,
                    'question' => 'What documents are required?',
                    'answer' => 'Depending on the program:',
                    'items' => [
                        'Passport Size Photo',
                        'Aadhaar Card',
                        'Educational Certificates',
                        'School/College ID',
                        'Professional ID',
                        'Business Proof (if applicable)',
                    ],
                    'link' => ['label' => 'View Required Documents', 'slug' => 'required-documents'],
                ],
                [
                    'number' => 23,
                    'question' => 'Is online fee payment available?',
                    'answer' => 'Yes. Secure online payment options are available.',
                    'link' => ['label' => 'Fee Payment', 'slug' => 'fee-payment'],
                ],
                [
                    'number' => 24,
                    'question' => 'Will I get a fee receipt?',
                    'answer' => 'Yes. A digital receipt is generated immediately after payment.',
                ],
                [
                    'number' => 25,
                    'question' => 'Will I receive a Student ID?',
                    'answer' => 'Yes. Every admitted participant receives a unique Student ID.',
                ],
                [
                    'number' => 26,
                    'question' => 'Is there a Student Portal?',
                    'answer' => 'Yes. Students receive access to the BNS Learning Portal.',
                ],
                [
                    'number' => 27,
                    'question' => 'Will recordings be available?',
                    'answer' => 'Selected learning resources and digital content may be provided as per the program structure.',
                ],
                [
                    'number' => 28,
                    'question' => 'Can I network with entrepreneurs?',
                    'answer' => 'Yes. BNS provides networking opportunities with entrepreneurs, mentors, business leaders, and industry experts.',
                ],
                [
                    'number' => 29,
                    'question' => 'Can I visit before taking admission?',
                    'answer' => 'Yes. You may attend an Introduction Session or speak with our Admission Team.',
                    'link' => ['label' => 'Book Introduction Session', 'slug' => 'introduction-session'],
                ],
                [
                    'number' => 30,
                    'question' => 'How can I contact BNS?',
                    'answer' => 'You can contact us through:',
                    'items' => [
                        'Phone',
                        'WhatsApp',
                        'Email',
                        'Website Contact Form',
                        'Admission Office',
                    ],
                    'link' => ['label' => 'Contact Admission Office', 'slug' => 'contact-admission-office'],
                ],
            ],
            'additional_heading' => 'Additional FAQs',
            'additional_questions' => [
                [
                    'number' => 31,
                    'question' => 'Why should I join Business Navachar School?',
                    'answer' => 'BNS provides practical business education that helps learners develop entrepreneurial thinking, leadership, financial literacy, and real-world business skills.',
                ],
                [
                    'number' => 32,
                    'question' => 'Why is Business Education important?',
                    'answer' => 'Business education prepares individuals to create opportunities, build businesses, manage finances, and become leaders in today\'s economy.',
                ],
                [
                    'number' => 33,
                    'question' => 'Is BNS only for people who want to start a business?',
                    'answer' => 'No. BNS is valuable for students, professionals, entrepreneurs, homemakers, and anyone who wants to develop business and leadership skills.',
                ],
                [
                    'number' => 34,
                    'question' => 'Can I continue my regular school, college, or job while studying at BNS?',
                    'answer' => 'Yes. BNS follows a Weekly Business School model, allowing participants to continue their regular education or profession.',
                ],
                [
                    'number' => 35,
                    'question' => 'How many classes are conducted every week?',
                    'answer' => 'One structured learning session every week totaling approximately 4 learning hours.',
                ],
                [
                    'number' => 36,
                    'question' => 'Will there be practical assignments?',
                    'answer' => 'Yes. Every participant works on projects, assignments, case studies, research activities, and presentations.',
                ],
                [
                    'number' => 37,
                    'question' => 'Will I get opportunities to present my ideas?',
                    'answer' => 'Yes. Regular business presentations and idea pitching sessions are part of the learning process.',
                ],
                [
                    'number' => 38,
                    'question' => 'Will I learn Artificial Intelligence (AI)?',
                    'answer' => 'Yes. AI tools and their practical business applications are introduced as part of the curriculum.',
                ],
                [
                    'number' => 39,
                    'question' => 'Are there networking opportunities?',
                    'answer' => 'Yes. Participants interact with entrepreneurs, business leaders, mentors, industry experts, and fellow learners.',
                ],
                [
                    'number' => 40,
                    'question' => 'Will guest speakers conduct sessions?',
                    'answer' => 'Yes. Guest sessions by entrepreneurs, industry experts, and subject specialists are organized regularly.',
                ],
                [
                    'number' => 41,
                    'question' => 'Is attendance compulsory?',
                    'answer' => 'Participants are expected to maintain the required attendance to successfully complete the program and qualify for certification.',
                ],
                [
                    'number' => 42,
                    'question' => 'What language will be used during the sessions?',
                    'answer' => 'Sessions may be conducted in English, Hindi, Gujarati, or a bilingual format depending on the batch.',
                ],
                [
                    'number' => 43,
                    'question' => 'Will I receive a Business Learning Kit?',
                    'answer' => 'Yes. Eligible participants receive learning materials and resources as applicable to their program.',
                ],
                [
                    'number' => 44,
                    'question' => 'Can I change my batch after admission?',
                    'answer' => 'Batch changes may be considered based on seat availability and institutional policies.',
                ],
                [
                    'number' => 45,
                    'question' => 'Can I transfer my admission to another centre?',
                    'answer' => 'Subject to institutional policy and seat availability.',
                ],
                [
                    'number' => 46,
                    'question' => 'What happens if I miss a class?',
                    'answer' => 'Participants should contact the Student Support Team for available learning support and resources.',
                ],
                [
                    'number' => 47,
                    'question' => 'Is there any examination?',
                    'answer' => 'The evaluation process may include attendance, assignments, projects, presentations, and participation.',
                ],
                [
                    'number' => 48,
                    'question' => 'How are students evaluated?',
                    'answer' => 'Participants are assessed through continuous learning activities, practical work, presentations, and project performance.',
                ],
                [
                    'number' => 49,
                    'question' => 'Will I receive feedback on my progress?',
                    'answer' => 'Yes. Mentors provide guidance and feedback throughout the learning journey.',
                ],
                [
                    'number' => 50,
                    'question' => 'Are parents involved in the School Students Program?',
                    'answer' => 'Yes. Parent orientation sessions and periodic interactions may be organized to discuss student development.',
                ],
                [
                    'number' => 51,
                    'question' => 'Will I get business mentorship?',
                    'answer' => 'Yes. Participants receive guidance from experienced mentors and business professionals.',
                ],
                [
                    'number' => 52,
                    'question' => 'Is internship support available?',
                    'answer' => 'Selected programs may include industry exposure, live projects, or internship opportunities wherever applicable.',
                ],
                [
                    'number' => 53,
                    'question' => 'Can I build my own startup while studying?',
                    'answer' => 'Yes. BNS encourages learners to work on business ideas and startup projects during the program.',
                ],
                [
                    'number' => 54,
                    'question' => 'Can existing business owners join even if their business is small?',
                    'answer' => 'Yes. The Business Owners Program is designed for businesses at every stage of growth.',
                ],
                [
                    'number' => 55,
                    'question' => 'Will I learn how to increase my income?',
                    'answer' => 'Yes. The curriculum includes business growth strategies, financial planning, and income generation concepts.',
                ],
                [
                    'number' => 56,
                    'question' => 'Is there any alumni network?',
                    'answer' => 'Yes. Participants become part of the growing BNS Alumni & Business Networking Community.',
                ],
                [
                    'number' => 57,
                    'question' => 'How will I receive updates after admission?',
                    'answer' => 'Through the Student Portal, WhatsApp Community, Email, SMS, and official communication channels.',
                ],
                [
                    'number' => 58,
                    'question' => 'Are seats limited?',
                    'answer' => 'Yes. Each batch has limited seats to ensure quality learning and personalized mentorship.',
                ],
                [
                    'number' => 59,
                    'question' => 'Why should I apply early?',
                    'answer' => 'Early applicants receive priority in batch allocation and admission processing.',
                    'link' => ['label' => 'Book Your Spot Now', 'route' => 'register'],
                ],
                [
                    'number' => 60,
                    'question' => 'How do I get more information?',
                    'answer' => 'You can contact the BNS Admission Team through Phone, WhatsApp, Email, or by attending a Free Introduction Session.',
                    'link' => ['label' => 'Book Free Introduction Session', 'slug' => 'introduction-session'],
                ],
                [
                    'number' => 61,
                    'question' => 'Is Business Navachar School affiliated with a university?',
                    'answer' => 'Business Navachar School is an independent business education initiative focused on practical business learning. Please refer to the official website for current academic collaborations and certifications.',
                ],
                [
                    'number' => 62,
                    'question' => 'Will the certificates help my profile?',
                    'answer' => 'Participation and Appreciation Certificates recognize your involvement and successful completion of the applicable program requirements, which can strengthen your academic or professional profile.',
                ],
                [
                    'number' => 63,
                    'question' => 'Can organizations nominate their employees?',
                    'answer' => 'Yes. Corporate organizations, institutions, and businesses can enroll teams through customized group programs.',
                    'link' => ['label' => 'Contact Us', 'route' => 'contact'],
                ],
                [
                    'number' => 64,
                    'question' => 'Are franchise or centre partnership opportunities available?',
                    'answer' => 'Yes. Eligible organizations and individuals may apply to become BNS Centre or Franchise Partners.',
                    'link' => ['label' => 'Contact Admission Office', 'slug' => 'contact-admission-office'],
                ],
                [
                    'number' => 65,
                    'question' => 'How can I become a mentor or visiting faculty?',
                    'answer' => 'You can apply through the Careers or Become a Mentor section on the BNS website. Eligible applicants may be invited for the selection and training process.',
                    'link' => ['label' => 'Contact Us', 'route' => 'contact'],
                ],
            ],
            'collaboration_heading' => 'Additional FAQs – Academic Collaboration & Certification',
            'collaboration_questions' => [
                [
                    'number' => 66,
                    'question' => 'What is the Academic Collaboration with Faculties of IIM?',
                    'answer' => 'Business Navachar School (BNS) has an Academic Collaboration with Faculties of IIM for mentor development, business learning methodologies, faculty development, and academic excellence, helping strengthen the quality of business education delivered at BNS.',
                ],
                [
                    'number' => 67,
                    'question' => 'Are BNS programs conducted by Faculties of IIM?',
                    'answer' => 'No. BNS programs are conducted by Business Navachar School. BNS has an Academic Collaboration with Faculties of IIM for academic support, faculty development, and business learning methodologies.',
                ],
                [
                    'number' => 68,
                    'question' => 'Who conducts the classes at BNS?',
                    'answer' => 'Classes are conducted by experienced Visiting Expert Faculty, entrepreneurs, industry professionals, business mentors, and Faculties of IIM Trained Business Education Mentors.',
                    'link' => ['label' => 'Meet Visiting Expert Faculty', 'route' => 'about.faculty'],
                ],
                [
                    'number' => 69,
                    'question' => 'What are Faculties of IIM Trained Business Education Mentors?',
                    'answer' => 'These are BNS Visiting Expert Faculty members who have successfully completed the Faculty Development & Business Education Training Program conducted with the Faculties of IIM and are recognized by BNS as Faculties of IIM Trained Business Education Mentors.',
                ],
                [
                    'number' => 70,
                    'question' => 'Will I learn from Faculties of IIM Trained Teachers?',
                    'answer' => 'Yes. Depending on the batch and faculty allocation, participants may be taught by Faculties of IIM Trained Business Education Mentors, along with experienced entrepreneurs and industry experts.',
                ],
                [
                    'number' => 71,
                    'question' => 'What certificates will participants receive?',
                    'answer' => 'Eligible participants who successfully complete the required attendance and program activities will receive:',
                    'items' => [
                        ['icon' => '🏅', 'label' => 'Participation Certificate'],
                        ['icon' => '🏆', 'label' => 'Appreciation Certificate'],
                    ],
                    'outro' => 'These certificates will be awarded by the Faculties of IIM as per the academic framework and program guidelines.',
                ],
                [
                    'number' => 72,
                    'question' => 'Who is eligible to receive the certificates?',
                    'answer' => 'Participants who fulfill the prescribed attendance requirements and successfully complete the required projects, assignments, and program activities will be eligible.',
                ],
                [
                    'number' => 73,
                    'question' => 'Are the certificates included in the program fee?',
                    'answer' => 'Yes. Eligible participants receive the certificates as part of the program after successfully meeting the required criteria.',
                ],
                [
                    'number' => 74,
                    'question' => 'Why are Participation & Appreciation Certificates important?',
                    'answer' => 'These certificates recognize your commitment, participation, and learning journey, adding value to your academic, professional, and entrepreneurial profile.',
                ],
                [
                    'number' => 75,
                    'question' => 'Will every participant receive a certificate?',
                    'answer' => 'Certificates are awarded only to participants who meet the eligibility requirements, attendance criteria, and academic guidelines of the program.',
                ],
                [
                    'number' => 76,
                    'question' => 'What is the benefit of learning from Faculties of IIM Trained Teachers?',
                    'answer' => 'Participants benefit from structured teaching methodologies, practical business learning approaches, and high-quality classroom delivery developed through the Faculty Development Training Program with the Faculties of IIM.',
                ],
                [
                    'number' => 77,
                    'question' => 'Does the Academic Collaboration improve the quality of education?',
                    'answer' => 'Yes. The collaboration supports mentor development, teaching quality, business education methodologies, and continuous academic improvement at Business Navachar School.',
                ],
                [
                    'number' => 78,
                    'question' => 'Will BNS continue Faculty Development Programs?',
                    'answer' => 'Yes. Business Navachar School is committed to continuously developing its Visiting Expert Faculty through faculty development initiatives, advanced business education training, and academic collaborations.',
                ],
                [
                    'number' => 79,
                    'question' => 'Can experienced professionals become BNS Visiting Expert Faculty?',
                    'answer' => 'Yes. Eligible entrepreneurs, corporate leaders, business professionals, academicians, consultants, and subject experts can apply to become Visiting Expert Faculty. Selected candidates may participate in the BNS Faculty Development Program.',
                    'link' => ['label' => 'Visiting Expert Faculty', 'route' => 'about.faculty'],
                ],
                [
                    'number' => 80,
                    'question' => 'Why does BNS focus on faculty training?',
                    'answer' => 'At BNS, we believe that outstanding learners are developed by outstanding teachers. Continuous faculty development ensures participants receive practical, industry-relevant, and high-quality business education.',
                ],
            ],
            'still_have_questions' => [
                'title' => 'Still Have Questions?',
                'intro' => 'Our Admission Team is happy to assist you.',
                'contacts' => [
                    ['icon' => '📞', 'label' => 'Call Us', 'type' => 'phone'],
                    ['icon' => '💬', 'label' => 'WhatsApp Us', 'type' => 'whatsapp'],
                    ['icon' => '📧', 'label' => 'Email Us', 'type' => 'email'],
                    ['icon' => '📅', 'label' => 'Book a Free Introduction Session', 'type' => 'page', 'slug' => 'introduction-session'],
                    ['icon' => '🚀', 'label' => 'Apply Online Today', 'type' => 'apply'],
                ],
            ],
        ],
        'contact-admission-office' => [
            'title' => 'Contact Admission Office',
            'subtitle' => 'We are here to help you',
            'intro' => 'Reach our admission team for program guidance, fee details, batch information, and application support.',
            'items' => [
                'Admission Counselor available Monday–Saturday',
                'Phone, WhatsApp, and email support',
                'Visit our head office or nearest centre',
                'Book a counselling session online',
            ],
        ],
    ],

];
