<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Women Business School',
    'title' => 'Frequently Asked Questions (FAQs)',
    'parts' => [
        [
            'questions' => [
                [
                    'number' => 1,
                    'question' => 'What is Women Business School?',
                    'answers' => [
                        'Women Business School is a 2-Year Practical Business Education Program specially designed to empower women with entrepreneurship, business management, leadership, AI, digital business, and financial literacy.',
                    ],
                ],
                [
                    'number' => 2,
                    'question' => 'Who can join this program?',
                    'answers' => [
                        'Housewives',
                        'Homemakers',
                        'Women Entrepreneurs',
                        'Startup Founders',
                        'Existing Business Owners',
                        'Working Women',
                        'Freelancers',
                        'Consultants',
                        'Family Business Members',
                        'Women planning to start a business',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 3,
                    'question' => 'Do I need previous business experience?',
                    'answers' => [
                        'No.',
                        'This program is suitable for both beginners and experienced women entrepreneurs.',
                    ],
                ],
                [
                    'number' => 4,
                    'question' => 'What is the duration of the program?',
                    'answers' => [
                        '2 Years',
                        '200 Sessions',
                        '400 Learning Hours',
                        'Weekly 2 Sessions',
                        '4 Hours Per Week',
                    ],
                ],
                [
                    'number' => 5,
                    'question' => 'What is the learning journey?',
                    'answers' => [
                        'Year 1 – Women Startup School',
                        'Year 2 – Women Business Growth School',
                        'Students learn from Dream → Idea → Startup → Business Growth.',
                    ],
                ],
                [
                    'number' => 6,
                    'question' => 'What subjects will I learn?',
                    'answers' => [
                        'Entrepreneurship',
                        'Startup Development',
                        'Marketing',
                        'Branding',
                        'Sales',
                        'Digital Marketing',
                        'AI for Business',
                        'Finance',
                        'Accounting',
                        'HR',
                        'Leadership',
                        'Communication',
                        'Business Strategy',
                        'Customer Experience',
                        'E-Commerce',
                        'Business Operations',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 7,
                    'question' => 'Is the learning practical?',
                    'answers' => [
                        'Yes.',
                        'Learning includes:',
                        'Live Projects',
                        'Business Case Studies',
                        'Workshops',
                        'Masterclasses',
                        'Business Simulations',
                        'Startup Challenges',
                        'Mentoring',
                        'Networking Events',
                        'Business Visits',
                        'And many more practical learning experiences.',
                    ],
                ],
                [
                    'number' => 8,
                    'question' => 'Will I learn AI and Digital Business?',
                    'answers' => [
                        'Yes.',
                        'Topics include:',
                        'AI for Business',
                        'Prompt Engineering',
                        'Business Automation',
                        'Social Media Marketing',
                        'Digital Marketing',
                        'WhatsApp Business',
                        'Google Business Profile',
                        'E-Commerce',
                        'Content Marketing',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 9,
                    'question' => 'Who will teach the program?',
                    'answers' => [
                        'You will learn from:',
                        'BNS-Trained Faculties',
                        'Business Coaches',
                        'Industry Experts',
                        'Successful Entrepreneurs',
                        'Startup Mentors',
                        'Corporate Leaders',
                        'Selected sessions by Faculties of IIM, where applicable.',
                    ],
                ],
                [
                    'number' => 10,
                    'question' => 'Is the syllabus industry-oriented?',
                    'answers' => [
                        'Yes.',
                        'The syllabus and learning methodology are developed with the guidance of Faculties of IIM, as per the applicable collaboration framework.',
                    ],
                ],
                [
                    'number' => 11,
                    'question' => 'Will I receive certificates?',
                    'answers' => [
                        'Participants may receive:',
                        'Year-wise Completion Certificates',
                        'Program Completion Certificate',
                        'Skill Certificates',
                        'Project Certificates',
                        'Leadership Certificates',
                        'Business Excellence Certificates',
                        'AI Skill Certificates',
                        'Digital Marketing Certificates',
                        'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
                    ],
                ],
                [
                    'number' => 12,
                    'question' => 'Will I receive mentorship?',
                    'answers' => [
                        'Yes.',
                        'Participants receive guidance through:',
                        'Business Coaches',
                        'Industry Experts',
                        'Startup Mentors',
                        'Women Entrepreneurs',
                        'Business Networking',
                        'Practical Learning Support',
                    ],
                ],
                [
                    'number' => 13,
                    'question' => 'Will this program help me start my business?',
                    'answers' => [
                        'Yes.',
                        'The program helps you:',
                        'Identify Business Opportunities',
                        'Validate Business Ideas',
                        'Build Business Models',
                        'Launch Startups',
                        'Develop Brands',
                        'Acquire Customers',
                        'Manage Finance',
                        'Grow Your Business',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 14,
                    'question' => 'Can I join if I already have a business?',
                    'answers' => [
                        'Absolutely.',
                        'The program is ideal for women who want to:',
                        'Grow Existing Businesses',
                        'Increase Sales',
                        'Improve Marketing',
                        'Build Business Systems',
                        'Expand Operations',
                        'Adopt AI & Digital Technologies',
                        'Scale Their Business',
                    ],
                ],
                [
                    'number' => 15,
                    'question' => 'Will I get networking opportunities?',
                    'answers' => [
                        'Yes.',
                        'Meet and learn from:',
                        'Women Entrepreneurs',
                        'Business Owners',
                        'Investors',
                        'Mentors',
                        'Business Coaches',
                        'Industry Experts',
                        'Startup Founders',
                        'Corporate Leaders',
                        'And many more professionals.',
                    ],
                ],
                [
                    'number' => 16,
                    'question' => 'Why should I choose BNS?',
                    'answers' => [
                        'Because BNS provides:',
                        'Practical Business Education',
                        'Structured 2-Year Program',
                        'Industry-Oriented Curriculum',
                        'AI & Digital Business Learning',
                        'Business Coaching',
                        'Expert Mentorship',
                        'Live Projects',
                        'Professional Certifications',
                        'Women Entrepreneur Network',
                        'Business Growth Ecosystem',
                        'Lifelong Learning Community',
                        'And many more growth opportunities.',
                    ],
                ],
                [
                    'number' => 17,
                    'question' => 'What are the learning hours?',
                    'answers' => [
                        'Weekly: 2 Sessions | 4 Hours',
                        'Monthly: 8 Sessions | 16 Hours',
                        'Yearly: 100 Sessions | 200 Hours',
                        'Total Program: 200 Sessions | 400 Hours',
                    ],
                ],
                [
                    'number' => 18,
                    'question' => 'What is the final outcome of this program?',
                    'answers' => [
                        'After completing the program, participants will be able to:',
                        'Start a Business',
                        'Grow an Existing Business',
                        'Build a Strong Brand',
                        'Use AI in Business',
                        'Improve Sales & Marketing',
                        'Manage Finance',
                        'Lead Teams',
                        'Create Employment',
                        'Achieve Financial Independence',
                        'Become Successful Women Entrepreneurs',
                        'Contribute towards Viksit Bharat 2047',
                    ],
                ],
            ],
            'footer' => [
                'philosophy' => [
                    'heading' => 'Still Have Questions?',
                    'intro' => 'Our BNS Admission Team is always ready to guide you regarding admissions, curriculum, certifications, learning journey, and business opportunities.',
                    'lines' => [],
                ],
                'taglines' => [
                    'Dream Big. Build Bigger.',
                    'Empowered Women. Prosperous Families.',
                    'Women Entrepreneurs. Strong India.',
                    'Learn. Launch. Grow. Lead.',
                ],
            ],
        ],
    ],
];
