<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Women Business School',
    'title' => 'Why Choose BNS?',
    'subtitle' => 'Because Every Woman Deserves the Opportunity to Learn, Lead & Succeed.',
    'intro' => [
        'At Business Navachar School (BNS), we believe that empowering women through business education creates <strong>stronger families, stronger businesses, and a stronger nation</strong>.',
        'Our <strong>2-Year Women Business School</strong> is designed to help women confidently transform <strong>Ideas into Startups</strong> and <strong>Startups into Successful Businesses</strong> through practical learning, expert mentorship, and future-ready business skills.',
    ],
    'sections' => [
        [
            'heading' => 'Why Choose BNS?',
        ],
        [
            'heading' => '🚀 2-Year Structured Business Program',
            'list_intro' => 'A comprehensive business learning journey:',
            'points' => [
                'Year 1 – Women Startup School',
                'Year 2 – Women Business Growth School',
                'Designed to help women move from Dream → Idea → Startup → Business Growth.',
            ],
        ],
        [
            'heading' => '📚 Industry-Oriented Curriculum',
            'intro' => 'Learn through a <strong>structured syllabus and learning methodology</strong> developed with the guidance of <strong>Faculties of IIM</strong>, as per the applicable collaboration framework.',
        ],
        [
            'heading' => '👩‍🏫 Learn from Experts',
            'list_intro' => 'Gain practical knowledge from:',
            'points' => [
                'BNS-Trained Faculties',
                'Business Coaches',
                'Industry Experts',
                'Successful Women Entrepreneurs',
                'Startup Mentors',
                'Corporate Leaders',
                'Selected sessions by Faculties of IIM, where applicable.',
            ],
        ],
        [
            'heading' => '💼 Practical Business Learning',
            'list_intro' => 'Learn through:',
            'points' => [
                'Live Business Projects',
                'Business Case Studies',
                'Workshops',
                'Masterclasses',
                'Startup Challenges',
                'Business Simulations',
                'Mentoring Sessions',
                'Networking Events',
                'Business Visits',
                'And many more experiential learning opportunities.',
            ],
        ],
        [
            'heading' => '💡 Future-Ready Business Skills',
            'list_intro' => 'Develop expertise in:',
            'points' => [
                'Entrepreneurship',
                'Marketing',
                'Sales',
                'Branding',
                'Digital Marketing',
                'Artificial Intelligence (AI)',
                'Finance & Accounting',
                'Human Resource Management',
                'Leadership',
                'Communication',
                'Business Strategy',
                'Business Operations',
                'Customer Experience',
                'E-Commerce',
                'Personal Branding',
                'And many more future-ready skills.',
            ],
        ],
        [
            'heading' => '🏆 Professional Certifications',
            'list_intro' => 'Participants may receive:',
            'points' => [
                'Year-wise Completion Certificates',
                'Program Completion Certificate',
                'Skill Certificates',
                'Project Certificates',
                'Achievement Certificates',
                'Leadership Certificates',
                'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
            ],
        ],
        [
            'heading' => '🤝 Powerful Business Network',
            'list_intro' => 'Connect with:',
            'points' => [
                'Women Entrepreneurs',
                'Business Owners',
                'Startup Founders',
                'Industry Experts',
                'Investors',
                'Mentors',
                'Business Coaches',
                'Corporate Leaders',
                'Like-minded Women Professionals',
                'And many more business connections.',
            ],
        ],
        [
            'heading' => '🌍 Career & Business Growth',
            'list_intro' => 'Whether you want to:',
            'points' => [
                'Start a Business',
                'Grow Your Existing Business',
                'Build a Home-Based Business',
                'Expand Your Family Business',
                'Become Financially Independent',
                'Build a Personal Brand',
                'Learn AI & Digital Business',
                'Become a Business Leader',
            ],
            'closing' => 'BNS provides the <strong>knowledge, guidance, and ecosystem</strong> to help you succeed.',
        ],
        [
            'heading' => '❤️ Supportive Learning Ecosystem',
            'intro' => 'At BNS, you become part of a community where women:',
            'checklist' => [
                'Learn Together',
                'Grow Together',
                'Inspire Each Other',
                'Collaborate',
                'Build Businesses',
                'Create Employment',
                'Achieve Financial Independence',
            ],
        ],
        [
            'heading' => 'Why Thousands of Women Choose BNS',
            'checklist' => [
                'Practical Business Education',
                'Learn Beyond Traditional Classrooms',
                'Industry-Oriented Curriculum',
                'AI & Digital Business Learning',
                'Business Coaching & Mentoring',
                'Real Business Projects',
                'Professional Certifications',
                'Networking Opportunities',
                'Leadership Development',
                'Business Growth Strategies',
                'Financial Independence',
                'Lifelong Learning Community',
            ],
        ],
    ],
    'belief_heading' => 'Our Belief',
    'taglines' => [
        'Dream Big. Build Bigger.',
        'Believe in Yourself. Build Your Future.',
        'Financial Independence Begins with Entrepreneurship.',
        'Empowered Women Build Prosperous Families.',
        'Strong Women. Strong Businesses. Strong India.',
        'Learn. Launch. Grow. Lead.',
        'Together Towards Viksit Bharat 2047.',
    ],
];
