<?php

return [
    'eyebrow' => 'Growth Batch',
    'title' => 'Frequently Asked Questions (FAQs)',
    'parts' => [
        [
            'questions' => [
                [
                    'number' => 1,
                    'question' => 'What is the BNS Growth Batch?',
                    'answers' => [
                        'The BNS Growth Batch is a practical business learning program designed for Business Owners, Job Professionals, Women Entrepreneurs, and Youth Startups.',
                        'It focuses on helping participants start, grow, scale, and systemize businesses while developing leadership and future-ready business skills.',
                    ],
                ],
                [
                    'number' => 2,
                    'question' => 'Who can join the Growth Batch?',
                    'answers' => [
                        'Business Owners',
                        'MSME Owners',
                        'Startup Founders',
                        'Job Professionals',
                        'Women Entrepreneurs',
                        'Family Business Successors',
                        'Aspiring Entrepreneurs',
                        'Youth Startups',
                        'Freelancers',
                        'Consultants',
                        'And other eligible participants.',
                    ],
                ],
                [
                    'number' => 3,
                    'question' => 'What is the duration of the program?',
                    'answers' => [
                        '100 Interactive Sessions',
                        '200 Learning Hours',
                        'Weekly 2 Sessions',
                        '4 Hours Per Week',
                        'Practical & Project-Based Learning',
                    ],
                ],
                [
                    'number' => 4,
                    'question' => 'What will I learn in this program?',
                    'answers' => [
                        'Business Strategy',
                        'Marketing',
                        'Sales',
                        'Digital Marketing',
                        'AI for Business',
                        'Accounting',
                        'Finance',
                        'HR & Recruitment',
                        'Leadership',
                        'SOP Development',
                        'Business Systems',
                        'Business Scaling',
                        'Corporate Governance',
                        'Funding',
                        'IPO Journey',
                        'And many more practical business topics.',
                    ],
                ],
                [
                    'number' => 5,
                    'question' => 'Is this program practical or theoretical?',
                    'answers' => [
                        'The program is highly practical and includes:',
                        'Live Case Studies',
                        'Business Projects',
                        'Workshops',
                        'Masterclasses',
                        'Business Simulations',
                        'Group Discussions',
                        'Mentoring',
                        'Real Business Problem Solving',
                        'And many more experiential learning activities.',
                    ],
                ],
                [
                    'number' => 6,
                    'question' => 'Is the syllabus industry-oriented?',
                    'answers' => [
                        'Yes. The program follows a structured syllabus and learning methodology developed with the guidance of Faculties of IIM, as per the applicable collaboration framework, and is regularly updated to reflect modern business practices.',
                    ],
                ],
                [
                    'number' => 7,
                    'question' => 'Who will teach the sessions?',
                    'answers' => [
                        'Participants will learn through:',
                        'BNS-Trained Faculties',
                        'Business Coaches',
                        'Industry Experts',
                        'Entrepreneurs',
                        'Mentors',
                        'Subject Specialists',
                        'Selected sessions by Faculties of IIM, where applicable.',
                    ],
                ],
                [
                    'number' => 8,
                    'question' => 'Will I receive a certificate?',
                    'answers' => [
                        'Yes. Participants may receive:',
                        'Program Completion Certificate',
                        'Skill Certificates',
                        'Project Certificates',
                        'Achievement Certificates',
                        'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
                    ],
                ],
                [
                    'number' => 9,
                    'question' => 'Is prior business experience required?',
                    'answers' => [
                        'No. Whether you are starting a business, growing an existing one, or advancing your career, the program is designed to support learners at different stages.',
                    ],
                ],
                [
                    'number' => 10,
                    'question' => 'How will this program help my business or career?',
                    'answers' => [
                        'The program helps you:',
                        'Increase business growth',
                        'Improve profitability',
                        'Build business systems',
                        'Strengthen leadership',
                        'Improve marketing and sales',
                        'Use AI effectively',
                        'Build high-performing teams',
                        'Make better business decisions',
                        'Prepare for long-term success',
                    ],
                ],
                [
                    'number' => 11,
                    'question' => 'Will I learn Digital Marketing and AI?',
                    'answers' => [
                        'Yes. Dedicated modules cover:',
                        'Social Media Marketing',
                        'Google Business Profile',
                        'SEO',
                        'Content Marketing',
                        'E-Commerce',
                        'AI Tools',
                        'Prompt Engineering',
                        'Business Automation',
                        'AI for Marketing & Sales',
                        'And many more digital business skills.',
                    ],
                ],
                [
                    'number' => 12,
                    'question' => 'Will there be networking opportunities?',
                    'answers' => [
                        'Yes. Participants can connect with:',
                        'Entrepreneurs',
                        'Business Owners',
                        'Professionals',
                        'Investors',
                        'Industry Experts',
                        'Mentors',
                        'Business Coaches',
                        'Fellow Participants',
                    ],
                ],
                [
                    'number' => 13,
                    'question' => 'Will I work on live business projects?',
                    'answers' => [
                        'Yes. The program includes practical assignments, business case studies, growth strategies, business planning, startup projects, and real-world business applications.',
                    ],
                ],
                [
                    'number' => 14,
                    'question' => 'Is this suitable for Women Entrepreneurs?',
                    'answers' => [
                        'Absolutely. The program helps women entrepreneurs start, grow, manage, and scale businesses while building confidence, leadership, financial knowledge, and digital business skills.',
                    ],
                ],
                [
                    'number' => 15,
                    'question' => 'Why should I choose BNS?',
                    'answers' => [
                        'Because BNS offers:',
                        'Practical Business Learning',
                        'Industry-Oriented Curriculum',
                        'AI & Digital Business Training',
                        'Business Coaching & Mentoring',
                        'Structured Learning Methodology',
                        'Business Growth Strategies',
                        'Networking Opportunities',
                        'Professional Certifications',
                        'Learning ecosystem guided through collaboration with Faculties of IIM, where applicable.',
                    ],
                ],
            ],
            'footer' => [
                'philosophy' => [
                    'heading' => 'Still Have Questions?',
                    'intro' => 'Our team is ready to guide you through the program, eligibility, admissions, curriculum, and learning journey.',
                    'lines' => [],
                ],
                'taglines' => [
                    'Learn. Grow. Scale. Lead.',
                    'Empowering Businesses. Building Leaders.',
                    'Prosperous Businesses. Prosperous India.',
                ],
            ],
        ],
    ],
];
