<?php

return [
    'eyebrow' => 'Growth Batch',
    'title' => 'Certifications',
    'subtitle' => 'Recognizing Your Learning, Skills & Business Growth',
    'intro' => [
        'At Business Navachar School (BNS), every participant\'s learning journey is recognized through professional certifications that reflect knowledge, practical skills, project work, and continuous development.',
    ],
    'intro_closing' => 'Our certification framework is designed to enhance your professional profile, business credibility, and lifelong learning journey.',
    'sections' => [
        [
            'type' => 'graduation',
            'heading' => 'Program Completion Certificate',
            'intro' => 'Participants who successfully complete the Growth Batch program will receive the:',
            'highlight_title' => 'Business Navachar School (BNS) Program Completion Certificate',
            'list_heading' => 'This certificate recognizes:',
            'checklist' => [
                'Successful completion of the program',
                'Completion of 100 Sessions',
                'Completion of 200 Learning Hours',
                'Active participation in practical business learning',
                'Business growth and leadership development',
            ],
        ],
        [
            'type' => 'skills',
            'heading' => 'Skill Development Certificates',
            'intro' => 'Participants may receive <strong>Skill Certificates</strong> in areas such as:',
            'items' => [
                'Entrepreneurship',
                'Business Strategy',
                'Marketing',
                'Digital Marketing',
                'Sales Excellence',
                'Branding',
                'Artificial Intelligence (AI)',
                'Finance & Accounting',
                'Human Resource Management',
                'Leadership Development',
                'Business Communication',
                'Customer Relationship Management (CRM)',
                'Business Planning',
                'Business Automation',
                'Innovation & Design Thinking',
                'And many more future-ready business skills',
            ],
        ],
        [
            'type' => 'projects',
            'heading' => 'Project Completion Certificates',
            'intro' => 'Participants who successfully complete business projects may receive certificates for:',
            'items' => [
                'Business Growth Project',
                'Startup Project',
                'Business Plan Development',
                'Marketing Project',
                'Digital Marketing Campaign',
                'AI Implementation Project',
                'SOP Development',
                'HR & Recruitment Project',
                'Finance Improvement Project',
                'Business Transformation Project',
                'Innovation Project',
                'And many more practical business projects',
            ],
        ],
        [
            'heading' => 'Participation & Appreciation Certificates',
            'intro' => 'Participants may receive <strong>Participation/Appreciation Certificates by Faculties of IIM</strong> for eligible:',
            'list_heading' => 'Eligible programs include:',
            'checklist' => [
                'Workshops',
                'Masterclasses',
                'Seminars',
                'Business Conferences',
                'Training Programs',
                'Business Events',
                'Special Learning Sessions',
            ],
            'footer' => 'These certificates are awarded for eligible programs conducted under the applicable collaboration framework.',
        ],
        [
            'heading' => 'Achievement & Recognition Certificates',
            'intro' => 'Outstanding participants may also receive recognition for:',
            'checklist' => [
                'Best Entrepreneur Award',
                'Business Growth Excellence Award',
                'Leadership Excellence Award',
                'Innovation Excellence Award',
                'Startup Excellence Award',
                'Digital Business Excellence Award',
                'Outstanding Project Award',
                'Best Business Presentation Award',
                'Best Performer Award',
                'And many more recognitions based on performance and participation',
            ],
        ],
        [
            'type' => 'benefits',
            'heading' => 'Why BNS Certifications Matter',
            'list_heading' => 'Our certifications help participants:',
            'checklist' => [
                'Strengthen their professional profile',
                'Showcase practical business knowledge',
                'Demonstrate continuous learning',
                'Enhance business credibility',
                'Build confidence and leadership',
                'Highlight project-based experience',
                'Support career and business growth',
                'Showcase commitment to professional excellence',
            ],
        ],
    ],
    'taglines' => [
        'Every Session Builds Knowledge.',
        'Every Project Builds Experience.',
        'Every Certificate Reflects Your Growth.',
        'Learn. Grow. Scale. Lead.',
        'Business Excellence Through Continuous Learning.',
    ],
];
