<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Youth Business School',
    'title' => 'Certifications',
    'subtitle' => 'Recognizing Your Learning, Skills, Innovation & Entrepreneurial Journey',
    'intro' => [
        'At Business Navachar School (BNS), certifications represent more than course completion—they recognize your <strong>knowledge, practical skills, projects, leadership, innovation, and commitment to continuous learning</strong>.',
        'Throughout the <strong>3-Year Youth Business School Journey</strong>, participants have the opportunity to earn multiple certificates that strengthen their academic profile, professional portfolio, and entrepreneurial credibility.',
    ],
    'sections' => [
        [
            'type' => 'year_certificates',
            'heading' => 'Year-wise Completion Certificates',
            'intro' => 'Students who successfully complete each academic year will receive:',
            'certificates' => [
                [
                    'year' => 1,
                    'name' => 'Youth Foundation School Completion Certificate',
                    'description' => 'Recognition for successfully completing the foundation year in entrepreneurship, leadership, financial literacy, innovation, and business fundamentals.',
                ],
                [
                    'year' => 2,
                    'name' => 'Youth Startup School Completion Certificate',
                    'description' => 'Recognition for successfully completing startup development, product innovation, marketing, digital business, AI, business planning, and entrepreneurial learning.',
                ],
                [
                    'year' => 3,
                    'name' => 'Youth Business Growth School (Scale-Up School) Completion Certificate',
                    'description' => 'Recognition for successfully completing advanced business growth, leadership, corporate management, finance, business systems, scaling strategies, and IPO fundamentals.',
                ],
            ],
        ],
        [
            'type' => 'graduation',
            'heading' => 'Final Graduation Certificate',
            'intro' => 'Upon successful completion of the 3-Year Youth Business School Program, participants will receive the:',
            'highlight_title' => 'Business Navachar School (BNS) – Graduation Certificate',
            'list_heading' => 'Recognizing:',
            'checklist' => [
                'Successful completion of the 3-Year Program.',
                '300 Interactive Sessions.',
                '600 Learning Hours.',
                'Practical Business Education.',
                'Entrepreneurial & Leadership Development.',
                'Business Projects and Startup Learning.',
                'Commitment to lifelong learning.',
            ],
        ],
        [
            'type' => 'skills',
            'heading' => 'Skill Development Certificates',
            'intro' => 'Participants may receive skill-based certificates in areas such as:',
            'items' => [
                'Entrepreneurship',
                'Startup Development',
                'Innovation & Design Thinking',
                'Business Strategy',
                'Marketing',
                'Digital Marketing',
                'Branding',
                'Sales Excellence',
                'Artificial Intelligence (AI)',
                'Prompt Engineering',
                'Finance & Accounting',
                'Human Resource Management',
                'Leadership Development',
                'Business Communication',
                'Public Speaking',
                'Business Planning',
                'Business Analytics',
                'Customer Relationship Management (CRM)',
                'Business Automation',
                'And many more future-ready business skills.',
            ],
        ],
        [
            'type' => 'projects',
            'heading' => 'Project Completion Certificates',
            'intro' => 'Students may receive project certificates for successfully completing:',
            'items' => [
                'Startup Project',
                'Business Plan Project',
                'Product Development Project',
                'Market Research Project',
                'Digital Marketing Campaign',
                'AI Business Application Project',
                'Branding Project',
                'Sales Strategy Project',
                'HR & Recruitment Project',
                'Business Growth Project',
                'Innovation Project',
                'Social Impact Project',
                'Capstone Business Project',
                'And many more practical business projects.',
            ],
        ],
        [
            'heading' => 'Participation & Appreciation Certificates',
            'intro' => 'Students may receive <strong>Participation/Appreciation Certificates by Faculties of IIM</strong> for eligible:',
            'checklist' => [
                'Workshops',
                'Seminars',
                'Masterclasses',
                'Startup Bootcamps',
                'Business Conferences',
                'Training Programs',
                'Innovation Events',
                'Entrepreneurship Events',
                'Special Learning Sessions',
            ],
            'footer' => 'These certificates are awarded for eligible programs conducted under the applicable collaboration framework.',
        ],
        [
            'heading' => 'Achievement & Recognition Certificates',
            'intro' => 'Outstanding students may also receive recognition through:',
            'checklist' => [
                'Best Startup Idea Award',
                'Young Entrepreneur Award',
                'Innovation Excellence Award',
                'Leadership Excellence Award',
                'Business Plan Excellence Award',
                'Best Business Pitch Award',
                'Digital Marketing Excellence Award',
                'AI Innovation Award',
                'Outstanding Project Award',
                'Best Performer Award',
                'Business Excellence Award',
                'And many more awards based on participation, innovation, leadership, and performance.',
            ],
        ],
        [
            'type' => 'benefits',
            'heading' => 'Why BNS Certifications Matter',
            'list_heading' => 'BNS certifications help students:',
            'checklist' => [
                'Build a strong professional profile.',
                'Showcase practical business knowledge.',
                'Strengthen their resume and portfolio.',
                'Demonstrate entrepreneurial and leadership skills.',
                'Highlight project-based learning.',
                'Build credibility for higher education, careers, and startups.',
                'Showcase commitment to continuous learning and professional growth.',
                'Prepare for entrepreneurship, corporate careers, and future business opportunities.',
            ],
        ],
    ],
    'taglines' => [
        'Every Session Builds Knowledge.',
        'Every Project Builds Experience.',
        'Every Certificate Reflects Your Growth.',
        'Every Achievement Inspires Your Future.',
        'From Idea to Startup.',
        'From Startup to IPO.',
        'Learn Today. Launch Tomorrow. Scale Forever.',
    ],
];
