<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Why Choose BNS?',
    'subtitle' => 'For Job Excellence School & Business Empire School',
    'intro' => [
        'Because Success Doesn\'t Come from Experience Alone. It Comes from <strong>Continuous Learning, Innovation & Execution</strong>.',
        'In today\'s rapidly changing business world, professionals and business owners need much more than experience. They need <strong>business knowledge, leadership, Artificial Intelligence (AI), digital transformation, strategic thinking, and practical implementation</strong>.',
        'At Business Navachar School (BNS), we provide a <strong>structured, practical, and industry-oriented business education</strong> designed to help professionals accelerate their careers and business owners build stronger, scalable, and future-ready enterprises.',
    ],
    'sections' => [
        [
            'heading' => 'Why Choose BNS?',
        ],
        [
            'heading' => '🚀 Executive Business Learning Program',
            'list_intro' => 'Specially designed for:',
            'points' => [
                'Job Professionals',
                'Business Owners',
                'Entrepreneurs',
                'Startup Founders',
                'MSME Owners',
                'Directors',
                'CEOs',
                'Senior Managers',
                'Family Business Owners',
                'And many more professionals.',
            ],
        ],
        [
            'heading' => '📚 Industry-Oriented Curriculum',
            'intro' => 'Learn through a <strong>structured syllabus and learning methodology</strong> developed with the guidance of <strong>Faculties of IIM</strong>, as per the applicable collaboration framework.',
        ],
        [
            'heading' => '👨‍🏫 Learn from Experts',
            'list_intro' => 'Gain practical learning from:',
            'points' => [
                'BNS-Trained Faculties',
                'Business Coaches',
                'Industry Experts',
                'Entrepreneurs',
                'Corporate Leaders',
                'Startup Mentors',
                'Business Consultants',
                'Selected sessions by Faculties of IIM, where applicable.',
            ],
        ],
        [
            'heading' => '💼 Practical Business Learning',
            'list_intro' => 'Experience learning through:',
            'points' => [
                'Live Business Case Studies',
                'Business Simulations',
                'Workshops',
                'Masterclasses',
                'Executive Coaching',
                'Leadership Labs',
                'Business Problem Solving',
                'Industrial Visits',
                'Networking Events',
                'Business Growth Projects',
                'AI-Based Learning',
                'And many more practical experiences.',
            ],
        ],
        [
            'heading' => '💡 Future-Ready Skills',
            'list_intro' => 'Develop expertise in:',
            'points' => [
                'Business Strategy',
                'Leadership',
                'Marketing',
                'Sales',
                'Branding',
                'Artificial Intelligence (AI)',
                'Digital Marketing',
                'Finance',
                'Accounting',
                'Human Resource Management',
                'Business Operations',
                'SOP Development',
                'Business Analytics',
                'Business Automation',
                'Corporate Management',
                'Innovation',
                'Business Scaling',
                'Wealth Creation',
                'And many more future-ready business skills.',
            ],
        ],
        [
            'heading' => '🏆 Professional Certifications',
            'list_intro' => 'Participants may receive:',
            'points' => [
                'Program Completion Certificate',
                'Skill Development Certificates',
                'Project Completion Certificates',
                'Leadership Certificates',
                'Business Excellence Certificates',
                'AI & Digital Business Certificates',
                'Achievement Certificates',
                'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, and events conducted under the applicable collaboration framework.',
            ],
        ],
        [
            'heading' => '🤝 Powerful Business Network',
            'list_intro' => 'Connect with:',
            'points' => [
                'Entrepreneurs',
                'Business Owners',
                'Startup Founders',
                'Investors',
                'Industry Experts',
                'Business Coaches',
                'Corporate Leaders',
                'Mentors',
                'Consultants',
                'Professionals Across India',
                'And many more valuable business connections.',
            ],
        ],
        [
            'heading' => '📈 Business & Career Growth',
            'list_intro' => 'Whether you want to:',
            'points' => [
                'Accelerate Your Career',
                'Become a Better Leader',
                'Increase Your Salary Potential',
                'Grow Your Business',
                'Improve Profitability',
                'Build Strong Business Systems',
                'Expand Nationally or Globally',
                'Adopt AI & Digital Technologies',
                'Build High-Performance Teams',
                'Create Long-Term Wealth',
            ],
            'closing' => 'BNS provides the <strong>knowledge, mentorship, and ecosystem</strong> to help you achieve your goals.',
        ],
        [
            'heading' => '🌍 Lifetime Learning Community',
            'intro' => 'Become part of an ecosystem where professionals and entrepreneurs:',
            'checklist' => [
                'Learn Together',
                'Grow Together',
                'Collaborate Together',
                'Solve Business Challenges',
                'Share Opportunities',
                'Build Partnerships',
                'Create Employment',
                'Contribute to India\'s Growth',
            ],
        ],
        [
            'heading' => 'Why Thousands Choose BNS',
            'checklist' => [
                'Practical Business Education',
                'Executive Learning Model',
                'Industry-Oriented Curriculum',
                'AI & Digital Business Learning',
                'Business Coaching & Mentoring',
                'Live Business Case Studies',
                'Professional Certifications',
                'Leadership Development',
                'Networking with Industry Experts',
                'Business Growth Strategies',
                'Lifetime Learning Community',
                'Continuous Professional Development',
            ],
        ],
    ],
    'belief_heading' => 'Our Belief',
    'taglines' => [
        'Learn More. Lead More.',
        'Business Excellence Creates Prosperity.',
        'Innovation Creates Opportunities.',
        'AI + Business = Future Success.',
        'Strong Leaders Build Strong Businesses.',
        'Strong Businesses Build a Strong India.',
        'Never Stop Learning. Never Stop Growing.',
        'Together Towards Viksit Bharat 2047.',
    ],
];
