<?php

return [
    'eyebrow' => 'School Students',
    'title' => 'Why BNS for School Students?',
    'subtitle' => 'Empowering Young Minds to Build the Future',
    'intro' => [
        'School is the best place to build knowledge, values, and character. But in today\'s rapidly changing world, students also need <strong>entrepreneurial thinking, financial literacy, leadership, creativity, and problem-solving skills</strong>.',
        'Business Navachar School (BNS) bridges the gap between <strong>traditional education</strong> and <strong>future-ready education</strong> by preparing students to become innovators, entrepreneurs, professionals, and responsible leaders.',
    ],
    'intro_closing' => 'Because tomorrow\'s success begins with today\'s learning.',
    'sections' => [
        [
            'heading' => 'Why Business Education?',
            'intro' => 'Business education is not only for future entrepreneurs—it is for every student who wants to succeed in life.',
            'list_intro' => 'At BNS, students learn to:',
            'points' => [
                'Think Creatively and Solve Problems',
                'Develop Leadership & Communication Skills',
                'Understand Money, Finance & Wealth Creation',
                'Build Confidence and Decision-Making Ability',
                'Learn Innovation and Design Thinking',
                'Understand Marketing, Branding & Sales',
                'Explore AI, Technology & Digital Business',
                'Work Effectively in Teams',
                'Develop Real-World Business Knowledge',
                'Build Skills Beyond Textbooks',
                'And many more practical life and business skills...',
            ],
        ],
        [
            'heading' => 'Why Start Early?',
            'intro' => 'Great habits and great leaders are built early.',
            'paragraph' => 'The earlier students begin learning entrepreneurship and business skills, the greater their confidence, creativity, and ability to lead in the future.',
            'list_intro' => 'Starting early helps students:',
            'checklist' => [
                'Build an Entrepreneurial Mindset',
                'Develop Financial Awareness',
                'Improve Leadership Skills',
                'Strengthen Communication',
                'Increase Creativity & Innovation',
                'Learn Through Practical Experience',
                'Stay Ahead in a Competitive World',
                'Prepare for Future Careers',
                'And continuously grow with confidence...',
            ],
            'footer' => 'Early learning creates lifelong advantages.',
        ],
        [
            'heading' => 'Benefits of Joining BNS',
            'intro' => 'Students become more than academically successful—they become future-ready individuals.',
            'list_intro' => 'At BNS, students develop:',
            'points' => [
                'Entrepreneurial Mindset',
                'Leadership Skills',
                'Financial Literacy',
                'Public Speaking',
                'Communication Skills',
                'Critical Thinking',
                'Creativity & Innovation',
                'Problem-Solving Ability',
                'Teamwork & Collaboration',
                'Business Planning Skills',
                'Marketing & Sales Knowledge',
                'AI & Digital Readiness',
                'Personality Development',
                'Ethical Values',
                'Confidence to Lead',
                'Real-World Learning Experience',
                'And many more future-ready competencies...',
            ],
        ],
        [
            'heading' => 'Future Scope',
            'intro' => 'The skills learned at BNS prepare students for success in every stage of life.',
            'list_intro' => 'Students can confidently pursue careers as:',
            'checklist' => [
                'Entrepreneur',
                'Startup Founder',
                'Family Business Successor',
                'CEO',
                'Business Leader',
                'Corporate Professional',
                'Investor',
                'Innovator',
                'Consultant',
                'Wealth Creator',
                'Social Entrepreneur',
                'Global Business Leader',
                'Nation Builder',
                'And many more exciting career opportunities...',
            ],
        ],
        [
            'heading' => 'Job Creator Mindset',
            'intro' => 'The world needs more creators than followers.',
            'paragraph' => 'At BNS, students are inspired to think beyond employment and focus on creating opportunities for themselves and others.',
            'contrast' => [
                'instead' => 'Instead of asking, "Where can I get a job?"',
                'they_learn' => 'They learn to ask, "How can I create jobs, solve problems, and make a positive impact?"',
            ],
            'closing' => 'By developing this mindset, students become capable of building businesses, generating employment, driving innovation, and contributing to India\'s economic growth.',
        ],
    ],
    'belief_heading' => 'Our Belief',
    'taglines' => [
        'Dream Big. Build Bigger.',
        'Ideas Create the Future.',
        'Don\'t Chase Jobs. Create Jobs.',
        'Young Minds. Strong Nation. Viksit Bharat 2047.',
        'Learn Today. Build Tomorrow. Lead Forever.',
    ],
];
