<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Program Structure',
    'subtitle' => 'Wealth Creation to IPO Mastery Program',
    'tagline' => 'From Wealth Creation to IPO – A Complete Business Journey',
    'stats' => [
        ['icon' => 'fas fa-chalkboard-teacher', 'text' => '100 Sessions'],
        ['icon' => 'fas fa-clock', 'text' => '200 Learning Hours'],
    ],
    'intro' => [
        '<strong>Theme:</strong> Create Wealth • Build Systems • Scale Business • Create Legacy • Reach IPO',
    ],
    'modules_heading' => 'Modules',
    'modules' => [
        [
            'heading' => 'Module 1 – Wealth Creation Foundation',
            'topics' => [
                'Wealth Mindset',
                'Money Psychology',
                'Financial Intelligence',
                'Wealth Creation Formula',
                'Active vs Passive Income',
                'Multiple Income Streams',
                'Asset Creation',
                'Liability Management',
                'Financial Freedom Planning',
                'Personal Finance',
                'Family Wealth Planning',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 2 – Business Opportunity Creation',
            'topics' => [
                'Opportunity Identification',
                'Future Industries',
                'AI Business Opportunities',
                'Digital Business',
                'Rural Business',
                'Global Opportunities',
                'Innovation Framework',
                'Blue Ocean Strategy',
                'Problem Solving Business',
                'Value Creation',
                'New Business Models',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 3 – Startup Architecture',
            'topics' => [
                'Business Model Design',
                'MVP Development',
                'Product Development',
                'Service Design',
                'Customer Validation',
                'Business Planning',
                'Market Entry Strategy',
                'Business Registration',
                'Legal Foundation',
                'Startup Ecosystem',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 4 – Revenue Engineering',
            'topics' => [
                'Revenue Model Design',
                'Pricing Strategy',
                'Subscription Model',
                'Franchise Revenue',
                'Licensing',
                'Royalty Income',
                'Digital Products',
                'Membership Model',
                'Marketplace Business',
                'Global Revenue Models',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 5 – Sales & Marketing Excellence',
            'topics' => [
                'Growth Marketing',
                'AI Marketing',
                'Personal Branding',
                'Corporate Branding',
                'Omni Channel Marketing',
                'Sales Psychology',
                'Sales Automation',
                'Funnel Building',
                'Customer Experience',
                'Customer Lifetime Value',
                'Business Networking',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 6 – Finance Mastery',
            'topics' => [
                'Business Accounting',
                'Cash Flow Mastery',
                'Working Capital',
                'Profit Engineering',
                'Cost Optimization',
                'Financial Dashboard',
                'Business Valuation',
                'Investment Readiness',
                'Banking Relationship',
                'Tax Planning',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 7 – Business Systems',
            'topics' => [
                'SOP Development',
                'Business Automation',
                'AI Automation',
                'ERP',
                'CRM',
                'HR Systems',
                'Team Building',
                'Recruitment',
                'Leadership',
                'KPI & OKR Systems',
                'Business Processes',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 8 – Scale-Up Framework',
            'topics' => [
                'Business Scaling',
                'Multi Branch Expansion',
                'Franchise System',
                'Licensing Model',
                'National Expansion',
                'International Expansion',
                'Export Business',
                'Strategic Partnerships',
                'Joint Ventures',
                'Acquisition Strategy',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 9 – Corporate Excellence',
            'topics' => [
                'Corporate Governance',
                'Board Management',
                'Family Business Transformation',
                'Holding Company Structure',
                'Group Company Development',
                'Risk Management',
                'ESG',
                'Corporate Branding',
                'CXO Leadership',
                'Business Legacy',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 10 – Funding Mastery',
            'topics' => [
                'Bootstrapping',
                'Angel Investors',
                'Venture Capital',
                'Private Equity',
                'Debt Funding',
                'Government Schemes',
                'Investor Pitch',
                'Due Diligence',
                'Cap Table',
                'Shareholding Structure',
                'Fund Raising Strategy',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 11 – IPO Readiness',
            'topics' => [
                'SME IPO',
                'Main Board IPO',
                'Merchant Banking Basics',
                'Investment Banking',
                'Corporate Compliance',
                'Secretarial Compliance',
                'Audit Readiness',
                'Investor Relations',
                'Company Valuation',
                'IPO Documentation',
                'IPO Process',
                'IPO Roadmap',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Module 12 – Legacy & Global Business',
            'topics' => [
                'Family Office',
                'Wealth Preservation',
                'Trust Structure',
                'Global Business',
                'International Tax Awareness',
                'Cross Border Expansion',
                'Innovation Culture',
                'Business Legacy',
                'Next Generation Leadership',
                'Philanthropy',
                'Nation Building',
                'And many more.',
            ],
        ],
    ],
    'key_areas_heading' => 'Special BNS Innovation Modules',
    'key_areas' => [
        'AI CEO Framework',
        'Digital CEO',
        'Business Command Center',
        'Business Dashboard',
        'CEO Decision Framework',
        'Zero to Unicorn Journey',
        'MSME to Corporate Journey',
        'Corporate to IPO Journey',
        'Business Turnaround Blueprint',
        'Wealth Multiplication System',
        'Billion Dollar Thinking',
        'Family Business Modernization',
        'Personal Brand to Corporate Brand',
        'Data Driven Leadership',
        'Future Ready Enterprise',
        'Business Intelligence',
        'Corporate Innovation Lab',
        'Enterprise Risk Intelligence',
        'Business Excellence Framework',
        'And many more.',
    ],
    'practical_model' => [
        'heading' => 'Practical Learning',
        'includes_heading' => 'Participants will work on:',
        'items' => [
            'Personal Wealth Blueprint',
            'Business Growth Blueprint',
            'Scale-Up Blueprint',
            'Business Transformation Project',
            'AI Implementation Project',
            'SOP Manual',
            'Marketing Blueprint',
            'HR Blueprint',
            'Finance Blueprint',
            'Investor Pitch Deck',
            'Business Valuation Report',
            'Fund Raising Strategy',
            'IPO Readiness Checklist',
            'Corporate Governance Framework',
            'Legacy Planning Document',
            'Capstone Business Project',
            'And many more live implementation projects.',
        ],
    ],
    'outcome' => [
        'heading' => 'Final Outcome',
        'includes_heading' => 'Participants will be able to:',
        'items' => [
            'Build Wealth Systematically',
            'Launch & Scale Businesses',
            'Build High-Performance Teams',
            'Master AI & Digital Business',
            'Increase Revenue & Profitability',
            'Raise Investment',
            'Create National Brands',
            'Build Corporate Structures',
            'Prepare Businesses for SME IPO & Main Board IPO',
            'Build Multi-Generational Wealth',
            'Create Employment',
            'Build a Business Empire',
            'Leave a Lasting Legacy',
            'Contribute towards Viksit Bharat 2047',
            'And many more transformational business outcomes.',
        ],
    ],
    'taglines' => [
        'Wealth → Startup → Growth → Scale → Corporate → Funding → IPO → Legacy',
        'Learn. Build. Scale. List. Lead.',
    ],
];
