<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Women Business School',
    'title' => 'Vision',
    'subtitle' => 'Empowering Women. Building Businesses. Transforming Families. Strengthening India.',
    'intro' => [
        'At Business Navachar School (BNS), we believe that when a woman becomes <strong>financially empowered</strong>, she transforms not only her own life but also her <strong>family, community, and society</strong>.',
        'Our vision is to empower women with <strong>practical business education, entrepreneurial thinking, leadership, financial literacy, digital skills, Artificial Intelligence (AI), and business growth strategies</strong> so they can confidently build successful startups, grow sustainable businesses, and become independent business leaders.',
        'Through our structured <strong>2-Year Women Business School</strong>, we aim to help women transform <strong>Ideas into Startups, Startups into Successful Businesses, and Businesses into Sustainable Growth Enterprises</strong>, while contributing to the vision of <strong>Viksit Bharat 2047</strong>.',
    ],
    'points_heading' => 'Our Vision',
    'points' => [
        ['icon' => 'fas fa-female', 'text' => 'To inspire women to become <strong>confident entrepreneurs and business leaders</strong>.'],
        ['icon' => 'fas fa-coins', 'text' => 'To promote <strong>financial independence</strong> through entrepreneurship and business ownership.'],
        ['icon' => 'fas fa-lightbulb', 'text' => 'To transform <strong>business ideas into successful startups</strong>.'],
        ['icon' => 'fas fa-chart-line', 'text' => 'To help women <strong>establish, manage, and grow profitable businesses</strong>.'],
        ['icon' => 'fas fa-user-tie', 'text' => 'To develop <strong>leadership, confidence, communication, and decision-making skills</strong>.'],
        ['icon' => 'fas fa-briefcase', 'text' => 'To strengthen knowledge in <strong>Marketing, Sales, Finance, Accounting, Human Resources, Operations, Digital Marketing, AI, Branding, and Business Strategy</strong>.'],
        ['icon' => 'fas fa-robot', 'text' => 'To prepare women for the <strong>AI-powered and digital business economy</strong>.'],
        ['icon' => 'fas fa-puzzle-piece', 'text' => 'To encourage <strong>innovation, creativity, and problem-solving</strong>.'],
        ['icon' => 'fas fa-network-wired', 'text' => 'To create a strong network of <strong>women entrepreneurs, mentors, investors, industry experts, and business coaches</strong>.'],
        ['icon' => 'fas fa-laptop-code', 'text' => 'To provide practical business education through <strong>live projects, workshops, masterclasses, case studies, mentoring, networking events, and business visits</strong>.'],
        ['icon' => 'fas fa-university', 'text' => 'To deliver a structured syllabus and learning methodology developed with the guidance of <strong>Faculties of IIM</strong>, as per the applicable collaboration framework.'],
        ['icon' => 'fas fa-chalkboard-teacher', 'text' => 'To provide learning through <strong>BNS-trained faculties, business coaches, industry experts</strong>, with selected sessions by <strong>Faculties of IIM</strong>, where applicable.'],
        ['icon' => 'fas fa-certificate', 'text' => 'To recognize learning through <strong>Program Completion Certificates, Skill Certificates, Project Certificates</strong>, and <strong>Participation/Appreciation Certificates by Faculties of IIM</strong> for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.'],
        ['icon' => 'fas fa-hands-helping', 'text' => 'To support women in <strong>creating employment opportunities through entrepreneurship</strong>.'],
        ['icon' => 'fas fa-flag', 'text' => 'To contribute towards <strong>Viksit Bharat 2047</strong> by developing women-led businesses that strengthen India\'s economy.'],
    ],
    'dream_heading' => '2-Year Learning Journey',
    'journey_years' => [
        [
            'title' => 'Year 1 – Women Startup School',
            'intro' => 'Build entrepreneurial confidence and learn how to transform ideas into successful startups through practical business education.',
            'focus_heading' => 'Focus Areas',
            'focus_areas' => [
                'Entrepreneurial Mindset',
                'Business Foundation',
                'Startup Development',
                'Marketing',
                'Digital Marketing',
                'Branding',
                'AI for Business',
                'Financial Literacy',
                'Business Planning',
                'Leadership',
                'Communication',
                'And many more future-ready skills.',
            ],
        ],
        [
            'title' => 'Year 2 – Women Business Growth School',
            'intro' => 'Learn how to manage, systemize, scale, and grow businesses sustainably.',
            'focus_heading' => 'Focus Areas',
            'focus_areas' => [
                'Business Growth Strategy',
                'Sales Excellence',
                'Finance & Accounting',
                'Human Resource Management',
                'Business Operations',
                'Business Systems',
                'AI & Automation',
                'Leadership',
                'Business Expansion',
                'Wealth Creation',
                'Corporate Readiness',
                'And many more advanced business concepts.',
            ],
        ],
    ],
    'structure_block' => [
        'heading' => 'Program Structure',
        'items' => [
            'Duration: 2 Years',
            'Weekly: 2 Sessions | 4 Learning Hours',
            'Monthly: 8 Sessions | 16 Learning Hours',
            'Yearly: 100 Sessions | 200 Learning Hours',
            'Total Program: 200 Sessions | 400 Learning Hours',
        ],
    ],
    'statement_heading' => 'Vision Statement',
    'statement' => [
        '"To empower every woman with the knowledge, confidence, leadership, and entrepreneurial skills to build successful businesses, achieve financial independence, create employment, and become a catalyst for social and economic transformation."',
    ],
    'taglines' => [
        'Empowered Women. Strong Businesses. Prosperous Families.',
        'Women Entrepreneurs. Strong India.',
        'Learn. Launch. Grow. Lead.',
        'Together Towards Viksit Bharat 2047.',
    ],
];
