<?php

return [
    [
        'key' => 'vision',
        'label' => 'Vision',
        'icon' => 'fas fa-eye',
        'description' => 'Youth Business School vision — empowering college students to become entrepreneurs, innovators, and nation builders.',
        'action' => 'modal',
        'modal' => 'vision',
        'modal_cta' => 'Read Vision',
    ],
    [
        'key' => 'mission',
        'label' => 'Mission',
        'icon' => 'fas fa-bullseye',
        'description' => 'From Idea to IPO — transform ideas into startups, businesses, and IPO-ready enterprises.',
        'action' => 'modal',
        'modal' => 'mission',
        'modal_cta' => 'Read Mission',
    ],
    [
        'key' => 'eligibility',
        'label' => 'Eligibility Criteria',
        'icon' => 'fas fa-user-check',
        'description' => 'College students, aspiring entrepreneurs & young professionals — who can join the Youth Business School.',
        'action' => 'modal',
        'modal' => 'eligibility',
        'modal_id' => 'bnsEligibilityModal',
        'modal_cta' => 'View Eligibility',
    ],
    [
        'key' => 'program_structure',
        'label' => 'Program Structure',
        'icon' => 'fas fa-sitemap',
        'description' => '3-Year program — 300 sessions, 600 hours. Foundation, Startup & Scale-Up schools.',
        'action' => 'modal',
        'modal' => 'program_structure',
        'modal_id' => 'bnsProgramStructureModal',
        'modal_cta' => 'View Structure',
    ],
    [
        'key' => 'core_values',
        'label' => 'Core Values',
        'icon' => 'fas fa-gem',
        'description' => '15 values guiding every youth learner — from Idea to Startup to IPO.',
        'action' => 'modal',
        'modal' => 'core_values',
        'modal_id' => 'bnsCoreValuesModal',
        'modal_cta' => 'Read Core Values',
    ],
    [
        'key' => 'founder_message',
        'label' => "Founder's Message",
        'icon' => 'fas fa-quote-left',
        'description' => 'A personal message from Dr. Mehul Rupani to future entrepreneurs & business leaders.',
        'action' => 'modal',
        'modal' => 'founder_message',
        'modal_id' => 'bnsFounderMessageModal',
        'modal_cta' => 'Read Message',
    ],
    [
        'key' => 'why_bns',
        'label' => 'Why BNS?',
        'icon' => 'fas fa-star',
        'description' => 'Why business education matters — learn, innovate & build for the future economy.',
        'action' => 'modal',
        'modal' => 'why_bns',
        'modal_id' => 'bnsWhyBnsModal',
        'modal_cta' => 'Discover Why',
    ],
    [
        'key' => 'vision_2047',
        'label' => 'Vision 2047',
        'icon' => 'fas fa-flag',
        'description' => 'From Campus to Corporate. From Idea to IPO. Towards Viksit Bharat 2047.',
        'action' => 'modal',
        'modal' => 'vision_2047',
        'modal_id' => 'bnsVision2047Modal',
        'modal_cta' => 'Read Vision 2047',
    ],
    [
        'key' => 'prosperity_mission',
        'label' => 'Prosperity Vision',
        'icon' => 'fas fa-landmark',
        'description' => "India's Prosperity Vision — empowering young minds, building startups & Viksit Bharat 2047.",
        'action' => 'modal',
        'modal' => 'prosperity_mission',
        'modal_id' => 'bnsProsperityMissionModal',
        'modal_cta' => 'Read Vision',
    ],
    [
        'key' => 'certification',
        'label' => 'Certification',
        'icon' => 'fas fa-certificate',
        'description' => 'Year-wise, skill, project & Faculties of IIM certificates — recognizing your entrepreneurial journey.',
        'action' => 'modal',
        'modal' => 'certification',
        'modal_id' => 'bnsCertificationModal',
        'modal_cta' => 'View Certificates',
    ],
    [
        'key' => 'faqs',
        'label' => 'FAQs',
        'icon' => 'fas fa-question-circle',
        'description' => '15 FAQs — program, eligibility, curriculum, AI, certifications & career growth.',
        'action' => 'modal',
        'modal' => 'faqs',
        'modal_id' => 'bnsFaqsModal',
        'modal_cta' => 'Read FAQs',
    ],
];
