<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Executive Business School',
    'title' => 'Frequently Asked Questions (FAQs)',
    'parts' => [
        [
            'heading' => 'Job Excellence School & Business Empire School',
            'questions' => [
                [
                    'number' => 1,
                    'question' => 'What is Business Navachar School (BNS)?',
                    'answers' => [
                        'BNS is a practical business education ecosystem designed for Job Professionals, Business Owners, Entrepreneurs, Startup Founders, and Business Leaders to build business excellence, leadership, wealth creation, and long-term business growth.',
                    ],
                ],
                [
                    'number' => 2,
                    'question' => 'Who can join this program?',
                    'answers' => [
                        'Job Professionals',
                        'Business Owners',
                        'MSME Owners',
                        'Startup Founders',
                        'Directors',
                        'CEOs',
                        'Managers',
                        'Family Business Owners',
                        'Professionals planning to start a business',
                        'Entrepreneurs',
                        'Consultants',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 3,
                    'question' => 'What is the duration of the program?',
                    'answers' => [
                        '1 Year',
                        '100 Sessions',
                        '200 Learning Hours',
                        'Weekly 2 Sessions',
                        '4 Hours Per Week',
                    ],
                ],
                [
                    'number' => 4,
                    'question' => 'What is the learning model?',
                    'answers' => [
                        'Participants learn through:',
                        'Live Business Case Studies',
                        'Business Simulations',
                        'Executive Workshops',
                        'Masterclasses',
                        'Business Coaching',
                        'Industry Expert Sessions',
                        'Practical Projects',
                        'Networking Events',
                        'AI-Based Learning',
                        'Business Visits',
                        'And many more practical learning methods.',
                    ],
                ],
                [
                    'number' => 5,
                    'question' => 'What subjects will I learn?',
                    'answers' => [
                        'Leadership',
                        'Business Strategy',
                        'Wealth Creation',
                        'Marketing',
                        'Sales',
                        'Branding',
                        'Artificial Intelligence (AI)',
                        'Digital Marketing',
                        'Finance',
                        'Accounting',
                        'HR',
                        'Business Operations',
                        'SOP Development',
                        'Business Scaling',
                        'Fund Raising',
                        'SME IPO',
                        'Main Board IPO',
                        'Corporate Governance',
                        'Legacy Planning',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 6,
                    'question' => 'Will I learn AI?',
                    'answers' => [
                        'Yes.',
                        'Participants will learn:',
                        'AI for Business',
                        'Prompt Engineering',
                        'AI Productivity Tools',
                        'AI Marketing',
                        'AI Sales',
                        'AI Automation',
                        'Business Intelligence',
                        'AI Decision Making',
                        'And many more AI applications.',
                    ],
                ],
                [
                    'number' => 7,
                    'question' => 'Will I learn Digital Marketing?',
                    'answers' => [
                        'Yes.',
                        'Topics include:',
                        'Social Media Marketing',
                        'SEO',
                        'Google Business Profile',
                        'Performance Marketing',
                        'Meta Ads',
                        'LinkedIn Marketing',
                        'YouTube Marketing',
                        'WhatsApp Business',
                        'Content Marketing',
                        'E-Commerce',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 8,
                    'question' => 'Will I learn Wealth Creation?',
                    'answers' => [
                        'Yes.',
                        'The program covers:',
                        'Wealth Creation',
                        'Multiple Income Streams',
                        'Business Profitability',
                        'Investment Readiness',
                        'Business Valuation',
                        'Financial Planning',
                        'Wealth Preservation',
                        'Legacy Planning',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 9,
                    'question' => 'Will I learn Business Scaling?',
                    'answers' => [
                        'Yes.',
                        'Participants will learn:',
                        'Business Expansion',
                        'Franchise Model',
                        'Licensing',
                        'Distribution Network',
                        'Export Business',
                        'International Business',
                        'Corporate Structuring',
                        'Business Systems',
                        'AI Automation',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 10,
                    'question' => 'Will I learn about IPO?',
                    'answers' => [
                        'Yes.',
                        'The program includes:',
                        'SME IPO',
                        'Main Board IPO',
                        'IPO Readiness',
                        'Fund Raising',
                        'Investor Relations',
                        'Business Valuation',
                        'Corporate Governance',
                        'Due Diligence',
                        'IPO Roadmap',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 11,
                    'question' => 'Who will teach the program?',
                    'answers' => [
                        'Participants learn from:',
                        'BNS-Trained Faculties',
                        'Business Coaches',
                        'Industry Experts',
                        'Entrepreneurs',
                        'Corporate Leaders',
                        'Startup Mentors',
                        'Business Consultants',
                        'Selected sessions by Faculties of IIM, where applicable.',
                    ],
                ],
                [
                    'number' => 12,
                    'question' => 'Is the syllabus industry-oriented?',
                    'answers' => [
                        'Yes.',
                        'The syllabus and learning methodology are developed with the guidance of Faculties of IIM, as per the applicable collaboration framework.',
                    ],
                ],
                [
                    'number' => 13,
                    'question' => 'Will I receive certificates?',
                    'answers' => [
                        'Participants may receive:',
                        'Program Completion Certificate',
                        'Skill Development Certificates',
                        'Leadership Certificate',
                        'Project Completion Certificates',
                        'Business Excellence Certificate',
                        'AI & Digital Business Certificate',
                        'Wealth Creation Certificate',
                        'Business Growth Certificate',
                        'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, and events conducted under the applicable collaboration framework.',
                    ],
                ],
                [
                    'number' => 14,
                    'question' => 'Will I receive mentorship?',
                    'answers' => [
                        'Yes.',
                        'Participants receive guidance from:',
                        'Business Coaches',
                        'Industry Experts',
                        'Entrepreneurs',
                        'Corporate Leaders',
                        'Startup Mentors',
                        'Investors',
                        'Business Consultants',
                        'And many more mentors.',
                    ],
                ],
                [
                    'number' => 15,
                    'question' => 'Is this useful for Job Professionals?',
                    'answers' => [
                        'Yes.',
                        'The program helps professionals:',
                        'Build Leadership Skills',
                        'Improve Career Growth',
                        'Increase Productivity',
                        'Develop Business Thinking',
                        'Strengthen Decision Making',
                        'Prepare for Senior Management Roles',
                        'Build Entrepreneurial Mindset',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 16,
                    'question' => 'Is this useful for Business Owners?',
                    'answers' => [
                        'Absolutely.',
                        'Business owners will learn to:',
                        'Increase Revenue',
                        'Improve Profitability',
                        'Build Business Systems',
                        'Scale Operations',
                        'Adopt AI',
                        'Expand Nationally & Globally',
                        'Raise Funds',
                        'Prepare for IPO',
                        'Build Long-Term Wealth',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 17,
                    'question' => 'What certifications will I receive?',
                    'answers' => [
                        'Participants may receive:',
                        'Program Completion Certificate',
                        'Skill Certificates',
                        'Project Certificates',
                        'Leadership Certificates',
                        'AI Certificates',
                        'Wealth Creation Certificates',
                        'Business Growth Certificates',
                        'Achievement Certificates',
                        'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops and training programs conducted under the applicable collaboration framework.',
                    ],
                ],
                [
                    'number' => 18,
                    'question' => 'What are the networking opportunities?',
                    'answers' => [
                        'Meet and connect with:',
                        'Business Owners',
                        'Entrepreneurs',
                        'Investors',
                        'Industry Experts',
                        'Corporate Leaders',
                        'Startup Founders',
                        'Mentors',
                        'Consultants',
                        'Professionals Across India',
                        'And many more.',
                    ],
                ],
                [
                    'number' => 19,
                    'question' => 'Why should I choose BNS?',
                    'answers' => [
                        'Because BNS provides:',
                        'Practical Business Education',
                        'Industry-Oriented Curriculum',
                        'Executive Learning Model',
                        'AI & Digital Business Learning',
                        'Business Coaching',
                        'Live Business Case Studies',
                        'Professional Certifications',
                        'Wealth Creation to IPO Learning',
                        'Networking Opportunities',
                        'Business Growth Ecosystem',
                        'Lifelong Learning Community',
                        'And many more growth opportunities.',
                    ],
                ],
                [
                    'number' => 20,
                    'question' => 'What is the final outcome of this program?',
                    'answers' => [
                        'After completing the program, participants will be able to:',
                        'Build Wealth',
                        'Increase Revenue & Profitability',
                        'Lead High-Performance Teams',
                        'Scale Businesses',
                        'Implement AI in Business',
                        'Raise Investment',
                        'Build Strong Business Systems',
                        'Prepare for SME IPO & Main Board IPO',
                        'Create Employment',
                        'Build a Business Legacy',
                        'Become Future-Ready Leaders',
                        'Contribute towards Viksit Bharat 2047',
                    ],
                ],
            ],
            'footer' => [
                'philosophy' => [
                    'heading' => 'Still Have Questions?',
                    'intro' => 'Our BNS Admission Team is always ready to guide you regarding admissions, curriculum, certifications, business growth, and your Wealth Creation to IPO journey.',
                    'lines' => [],
                ],
                'taglines' => [
                    'Learn More. Lead More.',
                    'Create Wealth. Build Business. Reach IPO.',
                    'Strong Businesses. Strong India.',
                    'Together Towards Viksit Bharat 2047.',
                ],
            ],
        ],
    ],
];
