<?php

return [
    [
        'key' => 'vision',
        'label' => 'Vision',
        'icon' => 'fas fa-eye',
        'description' => 'Our vision for practical business learning — world-class education for owners, professionals, women entrepreneurs, and youth.',
        'action' => 'modal',
        'modal' => 'vision',
        'modal_cta' => 'Read Vision',
    ],
    [
        'key' => 'mission',
        'label' => 'Mission',
        'icon' => 'fas fa-bullseye',
        'description' => 'How BNS empowers owners, professionals, women entrepreneurs, and youth through practical business learning.',
        'action' => 'modal',
        'modal' => 'mission',
        'modal_cta' => 'Read Mission',
    ],
    [
        'key' => 'vision_2047',
        'label' => 'Vision 2047',
        'icon' => 'fas fa-flag',
        'description' => 'BNS commitment to Viksit Bharat 2047 — empowering entrepreneurs, strengthening businesses, building India.',
        'action' => 'modal',
        'modal' => 'vision_2047',
        'modal_id' => 'bnsVision2047Modal',
        'modal_cta' => 'Read Vision 2047',
    ],
    [
        'key' => 'eligibility',
        'label' => 'Eligibility Criteria',
        'icon' => 'fas fa-user-check',
        'description' => 'Who can join BNS — business owners, job professionals, women entrepreneurs, and youth startup founders.',
        'action' => 'modal',
        'modal' => 'eligibility',
        'modal_id' => 'bnsEligibilityModal',
        'modal_cta' => 'View Eligibility',
    ],
    [
        'key' => 'core_values',
        'label' => 'Core Values',
        'icon' => 'fas fa-gem',
        'description' => '15 values that guide BNS learners — learn, innovate, grow sustainably, and lead responsibly.',
        'action' => 'modal',
        'modal' => 'core_values',
        'modal_id' => 'bnsCoreValuesModal',
        'modal_cta' => 'Read Core Values',
    ],
    [
        'key' => 'founder_message',
        'label' => "Founder's Message",
        'icon' => 'fas fa-quote-left',
        'description' => 'A personal message from Dr. Mehul Rupani for entrepreneurs, professionals, women leaders & young innovators.',
        'action' => 'modal',
        'modal' => 'founder_message',
        'modal_id' => 'bnsFounderMessageModal',
        'modal_cta' => 'Read Message',
    ],
    [
        'key' => 'why_bns',
        'label' => 'Why BNS?',
        'icon' => 'fas fa-star',
        'description' => 'Why BNS learners choose us — practical learning, expert guidance, growth & leadership.',
        'action' => 'modal',
        'modal' => 'why_bns',
        'modal_id' => 'bnsWhyBnsModal',
        'modal_cta' => 'Discover Why',
    ],
    [
        'key' => 'why_business_education',
        'label' => 'Why Business Education?',
        'icon' => 'fas fa-graduation-cap',
        'description' => 'Why business education matters — mindset, leadership, finance, innovation & career growth.',
        'action' => 'modal',
        'modal' => 'why_business_education',
        'modal_id' => 'bnsWhyBusinessEducationModal',
        'modal_cta' => 'Read More',
    ],
    [
        'key' => 'prosperity_mission',
        'label' => 'Prosperity Mission',
        'icon' => 'fas fa-landmark',
        'description' => "India's Prosperity Mission — empowering people, strengthening businesses, building Viksit Bharat 2047.",
        'action' => 'modal',
        'modal' => 'prosperity_mission',
        'modal_id' => 'bnsProsperityMissionModal',
        'modal_cta' => 'Read Mission',
    ],
    [
        'key' => 'program_structure',
        'label' => 'Program Structure',
        'icon' => 'fas fa-sitemap',
        'description' => 'Business to IPO Journey — 100 sessions, 10 modules, from foundation to global business leadership.',
        'action' => 'modal',
        'modal' => 'program_structure',
        'modal_id' => 'bnsProgramStructureModal',
        'modal_cta' => 'View Syllabus',
    ],
    [
        'key' => 'certification',
        'label' => 'Certification',
        'icon' => 'fas fa-certificate',
        'description' => 'Program completion, skill, project & achievement certificates recognizing your business growth.',
        'action' => 'modal',
        'modal' => 'certification',
        'modal_id' => 'bnsCertificationModal',
        'modal_cta' => 'View Certificates',
    ],
    [
        'key' => 'faqs',
        'label' => 'FAQs',
        'icon' => 'fas fa-question-circle',
        'description' => 'Frequently asked questions — program, eligibility, learning, certification & growth.',
        'action' => 'modal',
        'modal' => 'faqs',
        'modal_id' => 'bnsFaqsModal',
        'modal_cta' => 'Read FAQs',
    ],
];
