<?php

return [

    'school-student' => [
        'title' => 'School Student Program',
        'page_title' => 'School Student Entrepreneurship Program',
        'icon' => '👧',
        'tagline' => 'Weekly Business School',
        'intro' => 'Std 6 to Std 11 — build entrepreneurial foundations early through BNS structured Weekly Business School learning.',
        'vision' => [
            'eyebrow' => 'Business Navachar School (BNS)',
            'title' => 'Vision (School Students)',
            'intro' => [],
            'points_heading' => 'Vision Points',
            'points' => [
                ['icon' => 'fas fa-lightbulb', 'text' => 'To develop an <strong>entrepreneurial mindset</strong> in every student from an early age.'],
                ['icon' => 'fas fa-route', 'text' => 'To transform students from <strong>Idea Thinkers to Future CEOs</strong> through a structured <strong>5-year learning journey</strong>.'],
                ['icon' => 'fas fa-flask', 'text' => 'To nurture <strong>innovation, creativity, and problem-solving skills</strong> through experiential learning.'],
                ['icon' => 'fas fa-user-tie', 'text' => 'To build <strong>self-confidence, leadership, communication, and decision-making</strong> abilities.'],
                ['icon' => 'fas fa-coins', 'text' => 'To provide <strong>financial literacy</strong> and develop smart money management habits.'],
                ['icon' => 'fas fa-robot', 'text' => 'To equip students with <strong>AI, digital, and future-ready technology skills</strong>.'],
                ['icon' => 'fas fa-briefcase', 'text' => 'To inspire students to become <strong>job creators</strong> rather than job seekers.'],
                ['icon' => 'fas fa-search', 'text' => 'To encourage students to identify <strong>real-life problems</strong> and develop innovative business solutions.'],
                ['icon' => 'fas fa-rocket', 'text' => 'To help students <strong>design, build, launch, and grow</strong> their own startup projects.'],
                ['icon' => 'fas fa-brain', 'text' => 'To develop <strong>critical thinking, analytical thinking, and design thinking</strong> capabilities.'],
                ['icon' => 'fas fa-users', 'text' => 'To cultivate <strong>teamwork, collaboration, and responsible leadership</strong>.'],
                ['icon' => 'fas fa-balance-scale', 'text' => 'To teach <strong>business ethics, integrity, and social responsibility</strong>.'],
                ['icon' => 'fas fa-industry', 'text' => 'To expose students to real-world businesses through <strong>industry visits, business simulations, and live projects</strong>.'],
                ['icon' => 'fas fa-chart-line', 'text' => 'To prepare students with practical knowledge of <strong>marketing, sales, finance, branding, and business management</strong>.'],
                ['icon' => 'fas fa-seedling', 'text' => 'To build an <strong>entrepreneurial ecosystem</strong> where students can learn, experiment, fail, improve, and succeed.'],
                ['icon' => 'fas fa-laptop-code', 'text' => 'To prepare students for the future through <strong>AI, automation, digital entrepreneurship, and emerging technologies</strong>.'],
                ['icon' => 'fas fa-hands-helping', 'text' => 'To encourage innovation that contributes to <strong>society, sustainability, and nation-building</strong>.'],
                ['icon' => 'fas fa-globe-asia', 'text' => 'To develop <strong>globally competitive entrepreneurs</strong> with an Indian value system.'],
                ['icon' => 'fas fa-map-signs', 'text' => 'To prepare students for the complete journey from <strong>Idea → Startup → Growth → Scale-up → Corporate → IPO</strong>.'],
                ['icon' => 'fas fa-flag', 'text' => 'To create a generation of <strong>confident, ethical, innovative, and visionary business leaders</strong> who contribute to <strong>Viksit Bharat 2047</strong> and the global economy.'],
            ],
            'statement_heading' => null,
            'statement' => [],
            'taglines' => [],
        ],
        'mission' => [
            'eyebrow' => 'Business Navachar School (BNS)',
            'title' => 'Mission',
            'intro' => [],
            'points_heading' => 'Mission Points',
            'points' => [
                ['icon' => 'fas fa-graduation-cap', 'text' => 'To provide <strong>world-class entrepreneurship education</strong> through a structured, progressive, and experiential learning journey.'],
                ['icon' => 'fas fa-flask', 'text' => 'To make business education <strong>practical, activity-based, project-based, and experience-driven</strong>.'],
                ['icon' => 'fas fa-lightbulb', 'text' => 'To develop <strong>creativity, innovation, critical thinking, problem-solving abilities, and an entrepreneurial mindset</strong> in every student.'],
                ['icon' => 'fas fa-search', 'text' => 'To help students discover their <strong>strengths, talents, interests, and entrepreneurial potential</strong>.'],
                ['icon' => 'fas fa-user-tie', 'text' => 'To nurture <strong>leadership, communication, teamwork, decision-making, and personality development</strong> skills.'],
                ['icon' => 'fas fa-coins', 'text' => 'To build strong <strong>financial literacy, wealth creation awareness, and smart money management habits</strong> from an early age.'],
                ['icon' => 'fas fa-robot', 'text' => 'To equip students with <strong>Artificial Intelligence (AI), digital technology, automation, and future-ready business skills</strong>.'],
                ['icon' => 'fas fa-rocket', 'text' => 'To encourage students to identify <strong>real-world problems</strong> and develop innovative products, services, startups, and business solutions.'],
                ['icon' => 'fas fa-laptop-code', 'text' => 'To provide hands-on learning through <strong>business simulations, live projects, startup challenges, industrial visits, exhibitions, innovation labs, and experiential learning</strong>.'],
                ['icon' => 'fas fa-chalkboard-teacher', 'text' => 'To develop a strong mentor ecosystem where <strong>Business Coaches, Industry Experts, and Entrepreneurship Mentors</strong> trained by faculty members of the <strong>Faculties of IIM</strong> deliver practical entrepreneurship education, mentoring, workshops, and project guidance to students.'],
                ['icon' => 'fas fa-users', 'text' => 'To organize regular <strong>masterclasses, innovation workshops, startup boot camps, business expos, industry interactions, and entrepreneurship development programs</strong> led by experienced business leaders and expert mentors.'],
                ['icon' => 'fas fa-certificate', 'text' => 'To facilitate <strong>Participation and Appreciation Certificates</strong> from faculty members of the <strong>Faculties of IIM</strong> for students of Business Navachar School, in accordance with the academic collaboration and certification framework established under the programme.'],
                ['icon' => 'fas fa-medal', 'text' => 'To recognize students\' achievements through <strong>certifications, competitions, innovation challenges, project presentations, entrepreneurship awards, and continuous performance evaluation</strong>.'],
                ['icon' => 'fas fa-map-signs', 'text' => 'To guide every student through the complete entrepreneurial journey from <strong>Idea → Startup → Growth → Scale-up → Corporate → IPO</strong>.'],
                ['icon' => 'fas fa-balance-scale', 'text' => 'To promote <strong>ethical entrepreneurship, responsible leadership, sustainability, innovation, and social responsibility</strong>.'],
                ['icon' => 'fas fa-briefcase', 'text' => 'To inspire students to become <strong>job creators, entrepreneurs, innovators, business leaders, and nation builders</strong> rather than only job seekers.'],
                ['icon' => 'fas fa-flag', 'text' => 'To prepare <strong>globally competitive entrepreneurs</strong> who contribute to innovation, employment generation, economic development, and the vision of <strong>Viksit Bharat 2047</strong>.'],
            ],
            'statement_heading' => null,
            'statement' => [],
            'taglines' => [],
        ],
        'vision_2047' => [
            'eyebrow' => 'Business Navachar School (BNS)',
            'title' => 'Vision 2047 – School Students',
            'points_heading' => 'Our Vision',
            'points' => [
                ['icon' => 'fas fa-shield-alt', 'text' => 'To build India\'s <strong>most trusted and future-ready entrepreneurship education ecosystem</strong> for school students.'],
                ['icon' => 'fas fa-lightbulb', 'text' => 'To nurture <strong>entrepreneurial thinking, innovation, creativity, leadership, financial literacy, Artificial Intelligence (AI), and future-ready business skills</strong> from an early age.'],
                ['icon' => 'fas fa-route', 'text' => 'To transform every student through a <strong>structured five-year journey</strong>:<br><strong>Idea → Startup → Growth → Scale-up → Corporate → IPO → Unicorn</strong>.'],
                ['icon' => 'fas fa-chart-line', 'text' => 'To begin every student\'s entrepreneurial journey with the philosophy of <strong>"Double Your Income, Double Your Balance Sheet"</strong>, creating a strong foundation for <strong>lifelong wealth creation and financial independence</strong>.'],
                ['icon' => 'fas fa-briefcase', 'text' => 'To inspire every student to become a <strong>Job Creator</strong> rather than only a <strong>Job Seeker</strong>.'],
                ['icon' => 'fas fa-rocket', 'text' => 'To empower students to identify <strong>real-world problems</strong>, develop <strong>innovative solutions</strong>, and build <strong>successful startups</strong>.'],
                ['icon' => 'fas fa-user-tie', 'text' => 'To prepare students to become future <strong>Startup Founders, Business Leaders, Corporate Executives, CEOs, Investors, and Unicorn Entrepreneurs</strong>.'],
                ['icon' => 'fas fa-laptop-code', 'text' => 'To integrate <strong>entrepreneurship, AI, digital technology, business management, communication, leadership, and financial education</strong> into <strong>practical, project-based learning</strong>.'],
                ['icon' => 'fas fa-industry', 'text' => 'To provide <strong>real-world exposure</strong> through <strong>live projects, startup simulations, business competitions, industrial visits, exhibitions, mentorship, and innovation challenges</strong>.'],
                ['icon' => 'fas fa-balance-scale', 'text' => 'To develop <strong>ethical, responsible, socially conscious, and globally competitive entrepreneurs</strong> with <strong>strong Indian values</strong>.'],
                ['icon' => 'fas fa-users', 'text' => 'To create an ecosystem of <strong>Business Coaches, Industry Experts, Entrepreneurship Mentors, and educators</strong> to guide students throughout their entrepreneurial journey.'],
                ['icon' => 'fas fa-map-marked-alt', 'text' => 'To establish <strong>Business Navachar School chapters across India</strong>, making quality entrepreneurship education accessible to students from <strong>every school, every board, and every medium</strong>.'],
                ['icon' => 'fas fa-graduation-cap', 'text' => 'To empower <strong>more than 10 lakh students by 2047</strong> with <strong>entrepreneurial knowledge, AI skills, leadership, innovation, and practical business experience</strong>.'],
                ['icon' => 'fas fa-store', 'text' => 'To create <strong>thousands of student-led startups, family businesses, social enterprises, and future Unicorn companies</strong> that contribute to <strong>economic growth and employment generation</strong>.'],
                ['icon' => 'fas fa-flag', 'text' => 'To contribute to the vision of <strong>Viksit Bharat 2047</strong> by preparing a generation of <strong>confident entrepreneurs</strong> who build businesses, create jobs, generate wealth, strengthen India\'s economy, and positively impact society.'],
            ],
            'statement_heading' => 'Vision Statement',
            'statement' => [
                'Business Navachar School is committed to transforming young students into <strong>innovative thinkers, startup founders, business leaders, and future Unicorn entrepreneurs</strong> through <strong>practical entrepreneurship education, AI-powered learning, financial literacy, and real-world business experiences</strong>.',
                'Our mission is not just to teach business, but to build the <strong>next generation of entrepreneurs</strong> who will lead India\'s journey towards a <strong>prosperous, innovative, and developed Viksit Bharat 2047</strong>.',
            ],
        ],
        'core_values' => [
            'eyebrow' => 'Student Business School (BNS)',
            'title' => 'Core Values – Student Business School (BNS)',
            'points' => [
                ['icon' => 'fas fa-lightbulb', 'title' => 'Entrepreneurial Mindset', 'text' => 'Think like a <strong>creator</strong>, not just a <strong>job seeker</strong>.'],
                ['icon' => 'fas fa-puzzle-piece', 'title' => 'Innovation', 'text' => 'Encourage <strong>creativity</strong> and develop <strong>solutions for real-world problems</strong>.'],
                ['icon' => 'fas fa-balance-scale', 'title' => 'Integrity', 'text' => 'Practice <strong>honesty, ethics, and responsibility</strong> in every action.'],
                ['icon' => 'fas fa-user-tie', 'title' => 'Leadership', 'text' => 'Lead with <strong>confidence, vision, teamwork, and accountability</strong>.'],
                ['icon' => 'fas fa-coins', 'title' => 'Financial Wisdom', 'text' => 'Develop <strong>smart money habits, financial literacy, and wealth creation skills</strong>.'],
                ['icon' => 'fas fa-book-reader', 'title' => 'Lifelong Learning', 'text' => 'Stay <strong>curious</strong>, continuously <strong>learn</strong>, and <strong>adapt to change</strong>.'],
                ['icon' => 'fas fa-medal', 'title' => 'Discipline & Excellence', 'text' => 'Build <strong>consistency, commitment</strong>, and a habit of <strong>giving your best</strong>.'],
                ['icon' => 'fas fa-brain', 'title' => 'Problem Solving', 'text' => 'Face challenges with <strong>critical thinking</strong> and <strong>innovative solutions</strong>.'],
                ['icon' => 'fas fa-hands-helping', 'title' => 'Collaboration', 'text' => 'Respect <strong>teamwork, communication, and collective growth</strong>.'],
                ['icon' => 'fas fa-robot', 'title' => 'Digital & AI Readiness', 'text' => 'Use <strong>technology and AI responsibly</strong> to create <strong>future opportunities</strong>.'],
                ['icon' => 'fas fa-heart', 'title' => 'Social Responsibility', 'text' => 'Build businesses that create <strong>value for society and the nation</strong>.'],
                ['icon' => 'fas fa-globe-asia', 'title' => 'Global Vision, Indian Values', 'text' => 'Think <strong>globally</strong> while staying rooted in <strong>Indian culture, ethics, and values</strong>.'],
                ['icon' => 'fas fa-mountain', 'title' => 'Resilience', 'text' => 'Learn from <strong>failures</strong>, embrace <strong>challenges</strong>, and keep <strong>moving forward</strong>.'],
                ['icon' => 'fas fa-leaf', 'title' => 'Sustainability', 'text' => 'Create businesses that care for <strong>people, the planet, and long-term prosperity</strong>.'],
                ['icon' => 'fas fa-flag', 'title' => 'Nation Building', 'text' => 'Develop <strong>responsible entrepreneurs</strong> who contribute to <strong>Viksit Bharat 2047</strong> through <strong>innovation, employment generation, and economic growth</strong>.'],
            ],
            'motto_heading' => 'BNS Student Motto',
            'motto' => 'Learn • Innovate • Build • Lead • Prosper',
        ],
        'founder_message' => [
            'eyebrow' => 'Business Navachar School (BNS)',
            'title' => "Founder's Message",
            'photo' => 'assets/images/founder/dr-mehul-rupani-school-student.png',
            'photo_alt' => 'Dr. Mehul Rupani, Founder & Visionary, Business Navachar School',
            'salutation' => 'Dear Students,',
            'opening' => [
                'The future is not created by those who wait.',
                'The future is created by those who <strong>dare to dream, think differently, and take action</strong>.',
                'Every great entrepreneur was once a student. Every successful business started with a <strong>single idea</strong>.',
                'At Business Navachar School (BNS), we believe that your <strong>age is never a limitation</strong>—your <strong>vision is your greatest strength</strong>.',
                'We don\'t just teach business; we nurture a mindset that empowers you to <strong>dream, innovate, lead, and create lasting impact</strong>.',
            ],
            'sections' => [
                [
                    'heading' => 'Our Belief',
                    'blocks' => [
                        ['tagline' => 'Dream Big. Build Bigger.', 'text' => 'Because every extraordinary achievement begins with a <strong>bold dream</strong>.'],
                        ['tagline' => 'Ideas Create the Future.', 'text' => 'Every innovation, every startup, and every successful company begins with <strong>one powerful idea</strong>.'],
                    ],
                ],
                [
                    'heading' => 'Our Mission',
                    'intro' => 'We don\'t want students to grow up only looking for jobs. We want them to become <strong>innovators, entrepreneurs, and leaders</strong> who create opportunities for thousands of others.',
                    'blocks' => [
                        ['tagline' => 'Don\'t Chase Jobs. Create Jobs.'],
                    ],
                ],
                [
                    'heading' => 'Our Learning Philosophy',
                    'intro' => 'Business education is not limited to textbooks. It is about <strong>thinking differently, solving real-world problems, and learning through experience</strong>.',
                    'blocks' => [
                        ['tagline' => 'Beyond Books. Beyond Boundaries.'],
                    ],
                ],
                [
                    'heading' => 'Our Mindset',
                    'intro' => 'Success is never decided by age. It is decided by <strong>vision, courage, discipline, and consistent action</strong>.',
                    'blocks' => [
                        ['tagline' => 'Age Doesn\'t Matter. Vision Does.'],
                    ],
                ],
                [
                    'heading' => 'Our Growth Formula',
                    'intro' => 'Every challenge teaches a lesson. Every failure builds experience. Every step forward brings you closer to your dreams.',
                    'blocks' => [
                        ['tagline' => 'Start Early. Stay Ahead.'],
                    ],
                ],
                [
                    'heading' => 'What You Will Become at BNS',
                    'intro' => 'You will learn to...',
                    'list' => [
                        'Think Like an Entrepreneur',
                        'Lead with Confidence',
                        'Manage Money Wisely',
                        'Build Strong Teams',
                        'Create Innovative Solutions',
                        'Start and Grow Businesses',
                        'Make Smart Decisions',
                        'Build Wealth with Values',
                        'Create Positive Social Impact',
                    ],
                    'blocks' => [
                        ['tagline' => 'Innovate. Inspire. Impact.'],
                    ],
                ],
                [
                    'heading' => 'Our Success Philosophy',
                    'intro' => 'True success is not measured only by money. It is measured by the <strong>value you create, the lives you touch, and the legacy you leave behind</strong>.',
                    'blocks' => [
                        ['tagline' => 'Build Wealth. Build Values.'],
                    ],
                ],
                [
                    'heading' => 'Our Vision',
                    'intro' => 'Our dream is to nurture a generation of <strong>young entrepreneurs, innovators, and business leaders</strong> who will build world-class companies, generate employment, strengthen India\'s economy, and contribute to <strong>Viksit Bharat 2047</strong>.',
                    'blocks' => [
                        ['tagline' => 'Young Minds. Strong Nation. Viksit Bharat 2047.'],
                    ],
                ],
            ],
            'remember' => [
                'heading' => 'Remember...',
                'taglines' => [
                    'Don\'t Wait for Opportunities. Create Them.',
                    'Don\'t Follow the Future. Build It.',
                    'Don\'t Just Study for Success. Build a Legacy.',
                    'Learn Today. Build Tomorrow. Lead Forever.',
                ],
            ],
            'signature' => [
                'closing' => 'With Best Wishes,',
                'name' => 'Dr. Mehul Rupani',
                'title' => 'Founder & Visionary',
                'organization' => 'Business Navachar School (BNS)',
            ],
        ],
        'why_bns' => require __DIR__.'/audience_program_why_bns.php',
        'prosperity_mission' => [
            'eyebrow' => 'School Students',
            'title' => "India's Prosperity Mission",
            'subtitle' => 'Empowering School Students to Build a Prosperous India',
            'intro' => [
                'India\'s greatest strength is its <strong>young population</strong>. The students of today will become the <strong>entrepreneurs, innovators, professionals, scientists, business leaders, and policymakers</strong> of tomorrow.',
                'At Business Navachar School (BNS), we believe that a <strong>prosperous India begins with empowered students</strong>. By nurturing entrepreneurial thinking, financial literacy, innovation, leadership, and strong values from an early age, we are preparing a generation that will <strong>create opportunities rather than wait for them</strong>.',
            ],
            'points_heading' => 'Our Mission for Every Student',
            'points' => [
                ['icon' => 'fas fa-lightbulb', 'title' => 'Develop an Entrepreneurial Mindset from an Early Age.'],
                ['icon' => 'fas fa-coins', 'title' => 'Build Financial Literacy and Wealth Creation Skills.'],
                ['icon' => 'fas fa-palette', 'title' => 'Encourage Innovation, Creativity, and Problem-Solving.'],
                ['icon' => 'fas fa-user-plus', 'title' => 'Inspire Students to Become Job Creators, Not Just Job Seekers.'],
                ['icon' => 'fas fa-users', 'title' => 'Develop Leadership, Communication, and Decision-Making Skills.'],
                ['icon' => 'fas fa-globe-asia', 'title' => 'Prepare Students for the AI, Digital, and Global Economy.'],
                ['icon' => 'fas fa-balance-scale', 'title' => 'Promote Ethical Business Practices and Responsible Leadership.'],
                ['icon' => 'fas fa-leaf', 'title' => 'Encourage Sustainable Development and Social Responsibility.'],
                ['icon' => 'fas fa-hands-helping', 'title' => 'Foster Self-Reliance through Skills, Entrepreneurship, and Innovation.'],
                ['icon' => 'fas fa-building', 'title' => 'Empower Students to Build Successful Businesses that Generate Employment.'],
                ['icon' => 'fas fa-chart-line', 'title' => 'Contribute to India\'s Economic Growth through Youth Entrepreneurship.'],
                ['icon' => 'fas fa-flag', 'title' => 'Create Responsible Citizens Who Lead with Integrity, Purpose, and Vision.'],
            ],
            'vision_heading' => 'Our Vision',
            'vision' => 'To nurture a generation of <strong>young entrepreneurs and leaders</strong> who will build innovative businesses, strengthen India\'s economy, create millions of employment opportunities, and contribute to <strong>Viksit Bharat 2047</strong>.',
            'become_heading' => 'Every Student Can Become...',
            'become_points' => [
                'An Innovator',
                'An Entrepreneur',
                'A Wealth Creator',
                'A Business Leader',
                'A Problem Solver',
                'A Nation Builder',
            ],
            'belief_heading' => 'Our Belief',
            'belief_lines' => [
                'When Students Prosper, Families Prosper.',
                'When Families Prosper, Society Progresses.',
                'When Society Progresses, India Prospers.',
            ],
            'taglines' => [
                'Dream Big. Build Bigger.',
                'Don\'t Chase Jobs. Create Jobs.',
                'Young Minds. Strong Nation. Prosperous India.',
                'Learn Today. Build Tomorrow. Lead Forever.',
            ],
        ],
        'program_structure' => require __DIR__.'/audience_program_structure.php',
        'certification' => require __DIR__.'/audience_program_certification.php',
        'events_experiences' => require __DIR__.'/audience_program_events.php',
        'faqs' => require __DIR__.'/audience_program_faqs.php',
        'eligibility_content' => require __DIR__.'/audience_program_school_eligibility.php',
        'boxes' => [
            [
                'key' => 'vision',
                'label' => 'Vision',
                'icon' => 'fas fa-eye',
                'description' => 'Business Navachar School (BNS) – Vision for School Students: 20 vision points from entrepreneurial mindset to Viksit Bharat 2047.',
                'action' => 'modal',
                'modal' => 'vision',
                'modal_cta' => 'Read Vision',
            ],
            [
                'key' => 'mission',
                'label' => 'Mission',
                'icon' => 'fas fa-bullseye',
                'description' => 'Business Navachar School (BNS) – Mission for School Students: 17 mission points from world-class entrepreneurship education to Viksit Bharat 2047.',
                'action' => 'modal',
                'modal' => 'mission',
                'modal_cta' => 'Read Mission',
            ],
            [
                'key' => 'eligibility',
                'label' => 'Eligibility Criteria',
                'icon' => 'fas fa-user-check',
                'description' => 'Std 6 to Std 11 — age eligibility, school boards, and admission criteria for school students.',
                'action' => 'modal',
                'modal' => 'eligibility',
                'modal_id' => 'bnsEligibilityModal',
                'modal_cta' => 'View Eligibility',
            ],
            [
                'key' => 'vision_2047',
                'label' => 'Vision 2047',
                'icon' => 'fas fa-flag',
                'description' => 'BNS commitment to Viksit Bharat 2047 — 10 lakh student entrepreneurs.',
                'action' => 'modal',
                'modal' => 'vision_2047',
                'modal_id' => 'bnsVision2047Modal',
                'modal_cta' => 'Read Vision 2047',
            ],
            [
                'key' => 'core_values',
                'label' => 'Core Values',
                'icon' => 'fas fa-gem',
                'description' => '15 values that guide every BNS school student — Learn • Innovate • Build • Lead • Prosper.',
                'action' => 'modal',
                'modal' => 'core_values',
                'modal_id' => 'bnsCoreValuesModal',
                'modal_cta' => 'Read Core Values',
            ],
            [
                'key' => 'founder_message',
                'label' => "Founder's Message",
                'icon' => 'fas fa-quote-left',
                'description' => 'A personal message from Dr. Mehul Rupani, Founder & Visionary of BNS.',
                'action' => 'modal',
                'modal' => 'founder_message',
                'modal_id' => 'bnsFounderMessageModal',
                'modal_cta' => 'Read Message',
            ],
            [
                'key' => 'why_bns',
                'label' => 'Why BNS?',
                'icon' => 'fas fa-star',
                'description' => 'Why BNS for School Students — business education, early learning, benefits, future scope, and job-creator mindset.',
                'action' => 'modal',
                'modal' => 'why_bns',
                'modal_id' => 'bnsWhyBnsModal',
                'modal_cta' => 'Discover Why',
            ],
            [
                'key' => 'prosperity_mission',
                'label' => 'Prosperity Mission',
                'icon' => 'fas fa-landmark',
                'description' => "India's Prosperity Mission — empowering students to build a prosperous nation.",
                'action' => 'modal',
                'modal' => 'prosperity_mission',
                'modal_id' => 'bnsProsperityMissionModal',
                'modal_cta' => 'Read Mission',
            ],
            [
                'key' => 'program_structure',
                'label' => 'Program Structure',
                'icon' => 'fas fa-sitemap',
                'description' => 'Weekly, monthly, yearly & 5-year learning plans — 500 sessions, 1000 hours.',
                'action' => 'modal',
                'modal' => 'program_structure',
                'modal_id' => 'bnsProgramStructureModal',
                'modal_cta' => 'View Structure',
            ],
            [
                'key' => 'certification',
                'label' => 'Certification',
                'icon' => 'fas fa-certificate',
                'description' => 'Year-wise, skill, project & graduation certificates recognizing every achievement.',
                'action' => 'modal',
                'modal' => 'certification',
                'modal_id' => 'bnsCertificationModal',
                'modal_cta' => 'View Certificates',
            ],
            [
                'key' => 'events_experiences',
                'label' => 'Events & Experiences',
                'icon' => 'fas fa-calendar-check',
                'description' => 'Workshops, seminars, startup summits, business fests & experiential learning.',
                'action' => 'modal',
                'modal' => 'events_experiences',
                'modal_id' => 'bnsEventsExperiencesModal',
                'modal_cta' => 'Explore Events',
            ],
            [
                'key' => 'faqs',
                'label' => 'FAQs',
                'icon' => 'fas fa-question-circle',
                'description' => 'Complete FAQ guide — program, admission, certification & growth (Q1–Q50).',
                'action' => 'modal',
                'modal' => 'faqs',
                'modal_id' => 'bnsFaqsModal',
                'modal_cta' => 'Read FAQs',
            ],
        ],
    ],

    'growth-batch' => array_merge(require __DIR__.'/audience_program_bns_core.php', require __DIR__.'/audience_program_growth_shared.php', [
        'title' => 'Growth Batch',
        'page_title' => 'Growth Batch — Business to IPO Journey',
        'icon' => '📈',
        'tagline' => 'Business to IPO Journey',
        'intro' => 'Business to IPO Journey — grow, lead, scale, and systemize your business through BNS structured Weekly Business School learning.',
    ]),

    'college-youth' => [
        'title' => 'College Youth Program',
        'page_title' => 'College Youth — Youth Business School',
        'icon' => '🎓',
        'tagline' => 'Youth Business School',
        'intro' => 'Undergraduate & postgraduate students — build startup thinking, business skills, and leadership through BNS structured 3-Year Business Learning Journey.',
        'vision' => require __DIR__.'/audience_program_college_youth_vision.php',
        'vision_2047' => require __DIR__.'/audience_program_college_youth_vision_2047.php',
        'mission' => require __DIR__.'/audience_program_college_youth_mission.php',
        'core_values' => require __DIR__.'/audience_program_college_youth_core_values.php',
        'founder_message' => require __DIR__.'/audience_program_college_youth_founder_message.php',
        'why_bns' => require __DIR__.'/audience_program_college_youth_why_bns.php',
        'prosperity_mission' => require __DIR__.'/audience_program_college_youth_prosperity_vision.php',
        'program_structure' => require __DIR__.'/audience_program_college_youth_structure.php',
        'certification' => require __DIR__.'/audience_program_college_youth_certification.php',
        'faqs' => require __DIR__.'/audience_program_college_youth_faqs.php',
        'eligibility_content' => require __DIR__.'/audience_program_college_youth_eligibility.php',
        'boxes' => require __DIR__.'/audience_program_college_youth_boxes.php',
    ],

    'women-batch' => array_merge(require __DIR__.'/audience_program_bns_core.php', require __DIR__.'/audience_program_growth_shared.php', [
        'title' => 'Women Batch',
        'page_title' => 'Women Batch — Women Entrepreneurship & Business Growth',
        'icon' => '👩',
        'tagline' => 'Women Entrepreneurship & Business Growth',
        'intro' => 'Women entrepreneurs, homepreneurs, and aspiring founders — build confidence, grow businesses, and achieve financial independence through practical BNS learning.',
        'vision' => require __DIR__.'/audience_program_women_batch_vision.php',
        'mission' => require __DIR__.'/audience_program_women_batch_mission.php',
        'eligibility_content' => require __DIR__.'/audience_program_women_batch_eligibility.php',
        'core_values' => require __DIR__.'/audience_program_women_batch_core_values.php',
        'founder_message' => require __DIR__.'/audience_program_women_batch_founder_message.php',
        'why_bns' => require __DIR__.'/audience_program_women_batch_why_bns.php',
        'why_business_education' => array_merge(require __DIR__.'/audience_program_growth_batch_why_business_education.php', [
            'eyebrow' => 'Women Batch',
        ]),
        'prosperity_mission' => require __DIR__.'/audience_program_women_batch_prosperity_mission.php',
        'vision_2047' => require __DIR__.'/audience_program_women_batch_vision_2047.php',
        'program_structure' => require __DIR__.'/audience_program_women_batch_structure.php',
        'faqs' => require __DIR__.'/audience_program_women_batch_faqs.php',
        'certification' => require __DIR__.'/audience_program_women_batch_certification.php',
        'boxes' => require __DIR__.'/audience_program_women_batch_boxes.php',
    ]),

    'business-job-professional-batch' => array_merge(require __DIR__.'/audience_program_bns_core.php', require __DIR__.'/audience_program_growth_shared.php', [
        'title' => 'Business & Job Professional Batch',
        'page_title' => 'Business & Job Professional Batch — Job Excellence & Business Empire School',
        'icon' => '💼',
        'tagline' => 'Job Excellence School • Business Empire School',
        'intro' => 'Job professionals and business owners — advance your career or grow your enterprise through BNS One-Year Executive Business Programs.',
        'vision' => require __DIR__.'/audience_program_business_job_professional_vision.php',
        'mission' => require __DIR__.'/audience_program_business_job_professional_mission.php',
        'founder_message' => require __DIR__.'/audience_program_business_job_professional_founder_message.php',
        'why_bns' => require __DIR__.'/audience_program_business_job_professional_why_bns.php',
        'why_business_education' => array_merge(require __DIR__.'/audience_program_growth_batch_why_business_education.php', [
            'eyebrow' => 'Business & Job Professional Batch',
        ]),
        'core_values' => array_merge(require __DIR__.'/audience_program_growth_batch_core_values.php', [
            'eyebrow' => 'Business Navachar School (BNS) – Business & Job Professional Batch',
            'intro' => [
                'At Business Navachar School (BNS), we believe that <strong>sustainable business growth</strong> is built on <strong>strong values, ethical leadership, continuous learning, and innovation</strong>. Our Business & Job Professional Batch is guided by the following core values:',
            ],
        ]),
        'prosperity_mission' => require __DIR__.'/audience_program_business_job_professional_prosperity_mission.php',
        'vision_2047' => require __DIR__.'/audience_program_business_job_professional_vision_2047.php',
        'program_structure' => require __DIR__.'/audience_program_business_job_professional_structure.php',
        'certification' => require __DIR__.'/audience_program_business_job_professional_certification.php',
        'faqs' => require __DIR__.'/audience_program_business_job_professional_faqs.php',
        'eligibility_content' => require __DIR__.'/audience_program_business_job_professional_eligibility.php',
        'boxes' => require __DIR__.'/audience_program_business_job_professional_boxes.php',
    ]),

];
