<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Certifications',
    'subtitle' => 'Executive Business School — Job Excellence School & Business Empire School',
    'intro' => [
        '<strong>Recognizing Your Learning, Leadership, Business Excellence & Wealth Creation Journey</strong>',
        'At Business Navachar School (BNS), certifications are more than a document—they represent your commitment to continuous learning, business excellence, leadership, innovation, wealth creation, and professional growth.',
    ],
    'intro_closing' => 'Our One-Year Executive Business School is designed to recognize every stage of your learning journey through multiple industry-oriented certifications.',
    'sections' => [
        [
            'type' => 'graduation',
            'heading' => 'Executive Business School Graduation Certificate',
            'intro' => 'Upon successful completion of the One-Year Executive Business School, participants may receive the:',
            'highlight_title' => 'Business Navachar School (BNS) Executive Business School Graduation Certificate',
            'list_heading' => 'Recognizing:',
            'checklist' => [
                'Successful Completion of the Executive Program',
                '100 Interactive Sessions',
                '200 Learning Hours',
                'Practical Business Education',
                'Leadership Development',
                'Business Excellence',
                'Wealth Creation Knowledge',
                'Business Transformation Journey',
            ],
        ],
        [
            'heading' => 'Program Completion Certificate',
            'intro' => 'Participants who successfully complete the program may receive:',
            'list_heading' => 'Executive Business Excellence Program Completion Certificate — Recognizing successful completion in:',
            'checklist' => [
                'Business Leadership',
                'Business Strategy',
                'Wealth Creation',
                'Business Growth',
                'AI & Digital Business',
                'Corporate Excellence',
                'Innovation',
                'Business Transformation',
                'And many more future-ready business competencies.',
            ],
        ],
        [
            'type' => 'skills',
            'heading' => 'Skill Development Certificates',
            'intro' => 'Participants may receive Skill Certificates in:',
            'items' => [
                'Leadership Excellence',
                'Business Strategy',
                'Wealth Creation',
                'Financial Intelligence',
                'Marketing Excellence',
                'Sales Excellence',
                'Branding',
                'Digital Marketing',
                'Artificial Intelligence (AI)',
                'Prompt Engineering',
                'Finance & Accounting',
                'Human Resource Management',
                'Business Operations',
                'SOP Development',
                'Business Automation',
                'CRM',
                'Business Analytics',
                'Corporate Governance',
                'Business Communication',
                'Innovation & Design Thinking',
                'Negotiation Skills',
                'Strategic Decision Making',
                'Export Business',
                'Franchise Management',
                'Business Scaling',
                'Business Excellence',
                'And many more.',
            ],
        ],
        [
            'type' => 'projects',
            'heading' => 'Project Completion Certificates',
            'intro' => 'Participants may receive Project Certificates for:',
            'items' => [
                'Wealth Creation Blueprint',
                'Business Strategy Project',
                'Business Growth Project',
                'AI Implementation Project',
                'Digital Marketing Project',
                'Business Automation Project',
                'SOP Development Project',
                'HR Transformation Project',
                'Finance Transformation Project',
                'Marketing Blueprint',
                'Sales Growth Blueprint',
                'Scale-Up Blueprint',
                'Investor Pitch Deck',
                'Business Valuation Project',
                'Fund Raising Strategy',
                'SME IPO Readiness Project',
                'Main Board IPO Readiness Project',
                'Corporate Governance Project',
                'Legacy Planning Project',
                'Capstone Business Excellence Project',
                'And many more practical implementation projects.',
            ],
        ],
        [
            'heading' => 'Professional Excellence Certificates',
            'intro' => 'Outstanding participants may receive:',
            'checklist' => [
                'Business Excellence Certificate',
                'Leadership Excellence Certificate',
                'Executive Leadership Certificate',
                'Innovation Excellence Certificate',
                'AI Excellence Certificate',
                'Digital Transformation Certificate',
                'Business Growth Excellence Certificate',
                'Strategic Leadership Certificate',
                'Wealth Creation Excellence Certificate',
                'Future Business Leader Certificate',
                'Corporate Leadership Certificate',
                'Employer Excellence Certificate',
                'Industry Excellence Certificate',
                'Outstanding Performer Certificate',
                'And many more.',
            ],
        ],
        [
            'heading' => 'Participation & Appreciation Certificates',
            'intro' => 'Participants may receive Participation/Appreciation Certificates by Faculties of IIM for eligible:',
            'checklist' => [
                'Executive Workshops',
                'Business Seminars',
                'Leadership Masterclasses',
                'AI & Digital Business Programs',
                'Business Growth Conferences',
                'Wealth Creation Sessions',
                'Executive Development Programs',
                'Startup & Innovation Programs',
                'Business Networking Events',
                'Corporate Learning Programs',
            ],
            'footer' => 'These certificates are awarded for eligible programs conducted under the applicable collaboration framework.',
        ],
        [
            'heading' => 'Business Excellence Awards',
            'intro' => 'Outstanding participants may receive:',
            'checklist' => [
                'Business Excellence Award',
                'Best Business Leader Award',
                'Leadership Excellence Award',
                'Wealth Creator Award',
                'Best Business Growth Award',
                'Innovation Excellence Award',
                'AI Business Innovation Award',
                'Best Strategy Award',
                'Best Business Transformation Award',
                'Best Scale-Up Business Award',
                'Outstanding Business Project Award',
                'Future CEO Award',
                'Future Entrepreneur Award',
                'Visionary Leader Award',
                'Lifetime Learning Award',
                'And many more awards based on performance, innovation, implementation, and leadership.',
            ],
        ],
        [
            'type' => 'benefits',
            'heading' => 'Value of BNS Certifications',
            'list_heading' => 'BNS Certifications help participants to:',
            'checklist' => [
                'Enhance Professional Credibility.',
                'Strengthen Personal & Corporate Branding.',
                'Demonstrate Executive Leadership Skills.',
                'Showcase Practical Business Knowledge.',
                'Highlight AI & Digital Business Expertise.',
                'Validate Business Strategy & Growth Competencies.',
                'Strengthen Business Transformation Capabilities.',
                'Build Confidence for Career Advancement.',
                'Improve Business Expansion Opportunities.',
                'Showcase Continuous Professional Development.',
                'Strengthen Networking & Industry Recognition.',
                'Support Long-Term Business & Leadership Growth.',
            ],
        ],
        [
            'heading' => 'Learning Excellence',
            'intro' => 'Our structured syllabus and learning methodology are developed with the guidance of Faculties of IIM, as per the applicable collaboration framework.',
            'footer' => 'Learning is delivered through BNS-trained faculties, business coaches, industry experts, with selected sessions by Faculties of IIM, where applicable.',
        ],
    ],
    'taglines' => [
        'Every Session Builds Knowledge.',
        'Every Project Builds Experience.',
        'Every Certificate Builds Credibility.',
        'Every Achievement Builds Leadership.',
        'Every Leader Builds a Stronger India.',
        'Learn. Lead. Grow. Scale.',
        'Create Wealth. Build Business. Reach IPO.',
        'Together Towards Viksit Bharat 2047.',
    ],
];
