<?php

return [
    'title' => 'Eligibility Criteria',
    'subtitle' => 'Business Navachar School (BNS) – Women Business School',
    'intro_heading' => 'Who Can Join?',
    'intro' => 'The Women Business School is specially designed for women who aspire to become entrepreneurs, startup founders, business owners, business leaders, financially independent professionals, and future wealth creators.',
    'intro_secondary' => 'Whether you are starting your first business, managing an existing business, or looking to develop new business skills, BNS welcomes women from all backgrounds.',
    'programs' => [
        [
            'icon' => '👩',
            'title' => 'Women Entrepreneurs',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Existing Business Owners',
                'Startup Founders',
                'Home-Based Business Owners',
                'Small Business Owners',
                'MSME Entrepreneurs',
                'Family Business Members',
                'Boutique Owners',
                'Retail Business Owners',
                'Service Business Owners',
                'Manufacturing Entrepreneurs',
                'Food & Catering Business Owners',
                'Online Business Owners',
                'E-Commerce Entrepreneurs',
                'Freelancers',
                'Consultants',
                'Social Entrepreneurs',
                'Creative Entrepreneurs',
                'House wives',
                'House Maker',
                'And many more.',
            ],
        ],
        [
            'icon' => '🚀',
            'title' => 'Aspiring Women Entrepreneurs',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Women planning to start a business.',
                'Women with innovative business ideas.',
                'Women interested in startups.',
                'Women seeking financial independence.',
                'Women looking for self-employment opportunities.',
                'Women interested in digital business.',
                'Women wanting to build a personal brand.',
                'Women interested in family business management.',
                'And many more aspiring entrepreneurs.',
            ],
        ],
        [
            'icon' => '💼',
            'title' => 'Working Women Professionals',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Corporate Professionals',
                'Bank Employees',
                'Teachers & Educators',
                'Doctors & Healthcare Professionals',
                'Lawyers',
                'Chartered Accountants',
                'Engineers',
                'IT Professionals',
                'Sales & Marketing Professionals',
                'HR Professionals',
                'Managers',
                'Consultants',
                'Government Employees',
                'Private Sector Professionals',
                'Freelancers',
                'And many more professionals.',
            ],
        ],
    ],
    'general_eligibility' => [
        'title' => 'General Eligibility',
        'intro' => 'Applicants should have:',
        'items' => [
            'Passion for Learning.',
            'Entrepreneurial Mindset.',
            'Positive Attitude.',
            'Interest in Business & Entrepreneurship.',
            'Willingness to Learn and Grow.',
            'Commitment to Attend Sessions.',
            'Readiness for Practical Learning.',
            'Leadership Potential.',
            'Teamwork & Collaboration Skills.',
            'Desire for Financial Independence.',
            'Commitment to Ethical Business Practices.',
        ],
    ],
    'no_prior_experience' => [
        'title' => 'No Prior Business Experience Required',
        'text' => 'Whether you are:',
        'items' => [
            'Starting your first business,',
            'Managing a family business,',
            'Running a home-based business,',
            'Working in a job,',
            'Planning a startup,',
            'Or simply interested in learning business,',
        ],
        'outro' => 'Business Navachar School (BNS) provides a structured learning journey to help you build confidence and practical business skills.',
    ],
    'ideal_for' => [
        'title' => 'Ideal For Women Who Want To Become',
        'items' => [
            'Entrepreneur',
            'Startup Founder',
            'Business Owner',
            'Women Business Leader',
            'CEO',
            'MSME Owner',
            'Family Business Successor',
            'Digital Entrepreneur',
            'E-Commerce Entrepreneur',
            'Social Entrepreneur',
            'Consultant',
            'Investor',
            'Wealth Creator',
            'Employer',
            'Nation Builder',
            'And many more future leadership roles.',
        ],
    ],
    'closing' => [
        'title' => '2-Year Learning Journey',
        'years' => [
            [
                'year' => 'Year 1',
                'label' => 'Women Startup School',
                'description' => 'Build a strong entrepreneurial foundation and learn how to transform ideas into successful startups.',
            ],
            [
                'year' => 'Year 2',
                'label' => 'Women Business Growth School',
                'description' => 'Learn how to grow, manage, market, systemize, and expand a business using modern business strategies, AI, digital tools, leadership, finance, and business management.',
            ],
        ],
    ],
    'program_structure' => [
        'title' => 'Program Structure',
        'items' => [
            'Duration: 2 Years',
            'Weekly: 2 Sessions | 4 Learning Hours',
            'Monthly: 8 Sessions | 16 Learning Hours',
            'Yearly: 100 Sessions | 200 Learning Hours',
            'Total Program: 200 Sessions | 400 Learning Hours',
        ],
    ],
    'journey_begin' => [
        'title' => 'Your Journey Begins Here',
        'tagline' => 'Dream → Idea → Startup → Business Growth',
    ],
    'taglines' => [
        'Empowered Women. Prosperous Families. Strong India.',
        'Learn. Launch. Grow. Lead.',
        'Together Towards Viksit Bharat 2047.',
    ],
];
