<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Events & Experiences',
    'subtitle' => 'Learning Beyond the Classroom',
    'intro' => [
        'At Business Navachar School (BNS), learning goes <strong>beyond books and classrooms</strong>. Throughout the year, students participate in inspiring events, practical workshops, competitions, business activities, and interactive experiences that help them develop <strong>confidence, creativity, leadership, and entrepreneurial skills</strong>.',
    ],
    'intro_closing' => 'Every event is designed to transform <strong>knowledge into real-world experience</strong>.',
    'sections' => [
        [
            'type' => 'compact',
            'heading' => 'Workshops',
            'intro' => 'Hands-on workshops provide students with <strong>practical knowledge and future-ready skills</strong>.',
            'list_heading' => 'Students participate in workshops on:',
            'items' => [
                'Entrepreneurship',
                'Financial Literacy',
                'Leadership Development',
                'Communication Skills',
                'Public Speaking',
                'AI & Digital Business',
                'Marketing & Branding',
                'Sales Skills',
                'Design Thinking',
                'Innovation',
                'Personality Development',
                'Goal Setting',
                'Time Management',
                'And many more practical learning topics...',
            ],
        ],
        [
            'type' => 'emoji',
            'emoji' => '🎤',
            'heading' => 'Seminars',
            'intro' => 'Interactive seminars expose students to <strong>new ideas, industry trends, and inspiring success stories</strong>.',
            'list_heading' => 'Seminars may include:',
            'items' => [
                'Business Awareness',
                'Startup Ecosystem',
                'Career Development',
                'Wealth Creation',
                'Future Skills',
                'Business Ethics',
                'Corporate Leadership',
                'Technology & Innovation',
                'Global Business Trends',
                'Nation Building',
                'And many more informative sessions...',
            ],
        ],
        [
            'type' => 'emoji',
            'emoji' => '⭐',
            'heading' => 'Masterclasses',
            'intro' => 'Special masterclasses are conducted by <strong>successful entrepreneurs, business leaders, investors, industry experts, and professionals</strong>.',
            'list_heading' => 'Students gain practical insights into:',
            'items' => [
                'Entrepreneurship',
                'Startup Growth',
                'Business Strategy',
                'Branding & Marketing',
                'Sales Excellence',
                'AI & Emerging Technologies',
                'Investment & Finance',
                'Leadership Excellence',
                'Personal Branding',
                'Corporate Success',
                'And many more advanced business concepts...',
            ],
        ],
        [
            'type' => 'featured',
            'emoji' => '🚀',
            'heading' => 'Startup Summit',
            'intro' => 'The <strong>BNS Startup Summit</strong> is a flagship event where students explore the exciting world of entrepreneurship and innovation.',
            'list_heading' => 'Highlights include:',
            'items' => [
                'Startup Idea Showcase',
                'Business Plan Presentations',
                'Investor Pitch Sessions',
                'Innovation Challenges',
                'Entrepreneur Talks',
                'Startup Networking',
                'Team Competitions',
                'Awards & Recognition',
                'And many more entrepreneurial experiences...',
            ],
        ],
        [
            'type' => 'featured',
            'emoji' => '🏆',
            'heading' => 'Annual Business Fest',
            'intro' => 'The <strong>Annual Business Fest</strong> celebrates creativity, innovation, leadership, and entrepreneurship through exciting activities and competitions.',
            'list_heading' => 'Students may participate in:',
            'items' => [
                'Business Competitions',
                'Innovation Expo',
                'Product Exhibition',
                'Marketing Challenges',
                'Business Quiz',
                'Sales Competitions',
                'Leadership Challenges',
                'Public Speaking Competitions',
                'Team-Building Activities',
                'Cultural & Networking Events',
                'Awards Ceremony',
                'And many more engaging experiences...',
            ],
        ],
        [
            'type' => 'checklist',
            'heading' => 'More Learning Opportunities',
            'list_heading' => 'Throughout the year, students may also participate in:',
            'items' => [
                'Industrial Visits',
                'Business Visits',
                'CEO & Founder Talks',
                'Innovation Labs',
                'Business Simulations',
                'Market Research Activities',
                'Community Projects',
                'Social Entrepreneurship Initiatives',
                'Leadership Camps',
                'Business Clubs',
                'Networking Events',
                'Internship & Exposure Programs (where applicable)',
                'National & International Learning Opportunities (where applicable)',
                'And many more experiential learning activities...',
            ],
        ],
    ],
    'taglines' => [
        'Every Event Inspires Learning.',
        'Every Experience Builds Confidence.',
        'Every Opportunity Shapes Future Leaders.',
        'Learn Today. Build Tomorrow. Lead Forever.',
    ],
];
