<?php

return [
    'title' => 'Eligibility Criteria',
    'subtitle' => 'Business Navachar School (BNS) – Youth Business School',
    'intro' => 'The Youth Business School is designed for college students and young individuals who aspire to become entrepreneurs, startup founders, business leaders, innovators, and future wealth creators.',
    'programs' => [
        [
            'icon' => '🎓',
            'title' => 'College Students',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Undergraduate Students',
                'Postgraduate Students',
                'Diploma Students',
                'Professional Course Students',
                'Engineering Students',
                'Medical & Healthcare Students',
                'Pharmacy Students',
                'Commerce Students',
                'Management Students',
                'Science Students',
                'Arts & Humanities Students',
                'Law Students',
                'Agriculture Students',
                'Computer & IT Students',
                'Design & Architecture Students',
                'Hotel Management Students',
                'Education Students',
                'And students from any recognized college or university.',
            ],
        ],
        [
            'icon' => '🚀',
            'title' => 'Aspiring Entrepreneurs',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Students planning to start a business.',
                'Students with innovative business ideas.',
                'Students interested in startups.',
                'Future family business leaders.',
                'Innovation enthusiasts.',
                'Youth interested in self-employment.',
                'Digital entrepreneurs.',
                'Social entrepreneurs.',
                'Freelancers.',
                'Creators and content entrepreneurs.',
                'And other aspiring entrepreneurs.',
            ],
        ],
        [
            'icon' => '💼',
            'title' => 'Young Professionals',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Fresh Graduates.',
                'Working Professionals.',
                'Startup Team Members.',
                'Business Development Executives.',
                'Sales & Marketing Professionals.',
                'Freelancers.',
                'Consultants.',
                'Self-employed Youth.',
                'And other young professionals seeking business growth.',
            ],
        ],
    ],
    'general_eligibility' => [
        'title' => 'General Eligibility',
        'intro' => 'Applicants should have:',
        'items' => [
            'Passion for Learning.',
            'Entrepreneurial Mindset.',
            'Positive Attitude.',
            'Willingness to Learn.',
            'Commitment to Attend Sessions.',
            'Interest in Business & Startups.',
            'Curiosity to Solve Real-World Problems.',
            'Readiness for Practical Learning.',
            'Teamwork & Collaboration Mindset.',
            'Desire for Continuous Growth.',
        ],
    ],
    'no_prior_experience' => [
        'title' => 'No Prior Business Experience Required',
        'text' => 'Whether you are:',
        'items' => [
            'Starting your first startup,',
            'Planning to launch a business,',
            'Preparing for your family business,',
            'Looking to become an entrepreneur,',
            'Or simply want to develop future-ready business skills,',
        ],
        'outro' => 'Business Navachar School (BNS) welcomes you.',
    ],
    'ideal_for' => [
        'title' => 'Ideal For Students Who Want To Become',
        'items' => [
            'Entrepreneur',
            'Startup Founder',
            'Business Owner',
            'CEO',
            'Business Leader',
            'Family Business Successor',
            'Innovator',
            'Investor',
            'Corporate Leader',
            'Social Entrepreneur',
            'Wealth Creator',
            'Global Entrepreneur',
            'Nation Builder',
            'And many more future leadership roles.',
        ],
    ],
    'closing' => [
        'title' => 'Your Journey Starts Here',
        'years' => [
            ['year' => 'Year 1', 'label' => 'Youth Foundation School'],
            ['year' => 'Year 2', 'label' => 'Youth Startup School'],
            ['year' => 'Year 3', 'label' => 'Youth Business Growth School (Scale-Up School)'],
        ],
        'tagline' => 'From Idea to Startup. From Startup to IPO.',
    ],
    'taglines' => [
        'Learn Today. Launch Tomorrow. Scale Forever.',
    ],
];
