<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Program Structure',
    'program_name' => '5-Year Student Business School Program',
    'subtitle' => 'From Ideas to IPO – A Complete Entrepreneurial Journey',
    'intro' => [
        'Business Navachar School (BNS) offers a structured <strong>5-Year Business Education Program</strong> designed to develop <strong>entrepreneurial thinking, financial literacy, leadership, innovation, and business excellence</strong> among school students.',
        'Our curriculum combines <strong>classroom learning</strong> with <strong>practical exposure, real-world projects, business activities, and experiential learning</strong> to prepare students for the future.',
    ],
    'plans_heading' => 'Program Structure',
    'plans' => [
        [
            'heading' => 'Weekly Learning',
            'stats' => [
                ['icon' => 'fas fa-calendar-week', 'text' => '2 Interactive Sessions'],
                ['icon' => 'fas fa-clock', 'text' => '4 Learning Hours'],
            ],
        ],
        [
            'heading' => 'Monthly Learning',
            'stats' => [
                ['icon' => 'fas fa-book', 'text' => '8 Interactive Sessions'],
                ['icon' => 'fas fa-clock', 'text' => '16 Learning Hours'],
            ],
        ],
        [
            'heading' => 'Yearly Learning',
            'stats' => [
                ['icon' => 'fas fa-check-circle', 'text' => '100 Sessions'],
                ['icon' => 'fas fa-clock', 'text' => '200 Learning Hours'],
            ],
        ],
    ],
    'five_year_plan' => [
        'heading' => 'Complete 5-Year Journey',
        'stats' => [
            ['icon' => 'fas fa-bullseye', 'text' => '500 Interactive Sessions'],
            ['icon' => 'fas fa-clock', 'text' => '1000 Learning Hours'],
        ],
        'includes' => [
            'Live Business Projects',
            'Startup Challenges',
            'Industry Exposure',
            'Business Competitions',
            'Mentorship Programs',
            'Business Visits',
            'Practical Learning',
            'Case Studies',
            'Workshops',
            'Seminars',
            'Networking Opportunities',
            'AI & Digital Learning',
            'Certifications',
            'And many more learning experiences...',
        ],
    ],
    'hours_table' => [
        'heading' => 'Learning Hours Overview',
        'columns' => ['Learning Level', 'Sessions', 'Learning Hours'],
        'rows' => [
            ['Weekly', '2', '4 Hours'],
            ['Monthly', '8', '16 Hours'],
            ['Yearly', '100', '200 Hours'],
            ['5-Year Program', '500', '1000 Hours'],
        ],
    ],
    'years_heading' => 'Year-wise Curriculum Details',
    'years' => [
        [
            'year' => 1,
            'name' => 'Idea Foundation School',
            'theme' => 'Think • Imagine • Create',
            'objective' => 'Build a strong entrepreneurial mindset and creative thinking from an early age.',
            'skills_title' => 'Students Will Learn',
            'skills' => [
                'Entrepreneurial Mindset',
                'Creativity & Innovation',
                'Design Thinking',
                'Critical Thinking',
                'Problem Solving',
                'Communication Skills',
                'Leadership Basics',
                'Team Building',
                'Financial Literacy',
                'Digital Literacy',
                'Business Idea Generation',
                'Goal Setting',
                'Time Management',
                'Personality Development',
                'Ethics & Values',
                'And many more foundational business and life skills...',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
        [
            'year' => 2,
            'name' => 'Startup School',
            'theme' => 'Learn • Build • Launch',
            'objective' => 'Transform ideas into real startup opportunities.',
            'skills_title' => 'Students Will Learn',
            'skills' => [
                'Startup Fundamentals',
                'Business Model Canvas',
                'Product Development',
                'Branding',
                'Marketing',
                'Sales Fundamentals',
                'Customer Research',
                'Business Planning',
                'Market Research',
                'Digital Business',
                'Social Media Marketing',
                'Pitch Presentation',
                'Customer Experience',
                'Startup Finance',
                'Business Validation',
                'And many more startup-building concepts and practical activities...',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
        [
            'year' => 3,
            'name' => 'Growth Business School',
            'theme' => 'Grow • Lead • Expand',
            'objective' => 'Learn how to grow and manage a successful business.',
            'skills_title' => 'Students Will Learn',
            'skills' => [
                'Business Growth Strategies',
                'Advanced Marketing',
                'Sales Mastery',
                'Accounting & Finance',
                'Human Resource Management',
                'Operations Management',
                'Customer Relationship Management',
                'AI in Business',
                'Business Automation',
                'Productivity Systems',
                'Strategic Decision Making',
                'Negotiation Skills',
                'Digital Transformation',
                'Business Analytics',
                'Performance Management',
                'And many more growth, management, and leadership skills...',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
        [
            'year' => 4,
            'name' => 'Scale-up Business School',
            'theme' => 'Scale • Systemize • Sustain',
            'objective' => 'Build systems and strategies to scale businesses successfully.',
            'skills_title' => 'Students Will Learn',
            'skills' => [
                'SOP Development',
                'Business Systems',
                'Expansion Strategy',
                'Franchise Model',
                'Funding & Investment',
                'Investor Readiness',
                'Export Business',
                'Technology Integration',
                'Corporate Structure',
                'Risk Management',
                'Business Sustainability',
                'Business Process Management',
                'Legal & Compliance Basics',
                'Strategic Partnerships',
                'Organizational Development',
                'And many more scale-up strategies, systems, and business expansion concepts...',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
        [
            'year' => 5,
            'name' => 'Corporate & IPO School',
            'theme' => 'Lead • Inspire • Build Legacy',
            'objective' => 'Prepare students to understand corporate management, wealth creation, and the IPO journey.',
            'skills_title' => 'Students Will Learn',
            'skills' => [
                'Corporate Governance',
                'Company Law Basics',
                'Board Management',
                'Corporate Leadership',
                'Investor Relations',
                'Financial Statements',
                'Stock Market Fundamentals',
                'IPO Process',
                'Business Valuation',
                'Wealth Creation',
                'Corporate Finance',
                'Mergers & Acquisitions',
                'Strategic Leadership',
                'Legacy Building',
                'Global Business Practices',
                'And many more corporate, investment, governance, and legacy-building concepts...',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
    ],
];
