<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Certification',
    'subtitle' => 'Recognizing Every Step of Your Business Learning Journey',
    'intro' => [
        'At Business Navachar School (BNS), every achievement is <strong>recognized and celebrated</strong>. Our certification framework motivates students to continuously learn, develop practical skills, complete projects, and successfully progress through each stage of the <strong>5-year program</strong>.',
    ],
    'intro_closing' => 'Each certificate reflects the student\'s <strong>dedication, learning outcomes, practical experience, and overall growth</strong>.',
    'sections' => [
        [
            'type' => 'year_certificates',
            'heading' => 'Year-wise Certificate',
            'intro' => 'At the successful completion of each academic year, students receive a <strong>Year Completion Certificate</strong> acknowledging their learning journey and academic progress.',
            'list_heading' => 'Students Receive:',
            'certificates' => [
                ['year' => 1, 'name' => 'Idea Foundation School Certificate'],
                ['year' => 2, 'name' => 'Startup School Certificate'],
                ['year' => 3, 'name' => 'Growth Business School Certificate'],
                ['year' => 4, 'name' => 'Scale-up Business School Certificate'],
                ['year' => 5, 'name' => 'Corporate & IPO School Certificate'],
            ],
            'footer' => 'Each certificate recognizes <strong>participation, learning achievements, project completion, practical exposure, and overall development</strong>.',
        ],
        [
            'type' => 'graduation',
            'heading' => 'Final Graduation Certificate',
            'intro' => 'Students who successfully complete the entire <strong>5-Year Program</strong> receive the prestigious:',
            'highlight_title' => 'Business Navachar School Graduation Certificate',
            'list_heading' => 'This certificate represents:',
            'checklist' => [
                'Successful completion of 500 Sessions',
                'Completion of 1000 Learning Hours',
                'Entrepreneurial & Business Education',
                'Leadership Development',
                'Financial Literacy',
                'Practical Business Learning',
                'Project-Based Learning',
                'Innovation & Problem-Solving Skills',
                'Overall Future-Ready Development',
            ],
        ],
        [
            'type' => 'skills',
            'heading' => 'Skill Certificates',
            'intro' => 'Students may also receive <strong>Skill Certificates</strong> for successfully completing specialized learning modules and demonstrating practical competencies.',
            'list_heading' => 'These may include:',
            'items' => [
                'Entrepreneurship Skills',
                'Leadership Skills',
                'Financial Literacy',
                'Public Speaking',
                'Communication Skills',
                'Sales & Marketing',
                'Digital Business',
                'AI for Business',
                'Innovation & Creativity',
                'Business Planning',
                'Teamwork & Collaboration',
                'Problem Solving',
                'Personality Development',
                'And many more future-ready skills...',
            ],
        ],
        [
            'type' => 'projects',
            'heading' => 'Project Certificates',
            'intro' => 'Students actively participate in <strong>practical assignments, business projects, startup simulations, innovation challenges, and entrepreneurial activities</strong> throughout the program.',
            'list_heading' => 'Project Certificates may be awarded for:',
            'items' => [
                'Startup Project',
                'Business Plan Project',
                'Innovation Challenge',
                'Product Development Project',
                'Market Research Project',
                'Business Exhibition',
                'Leadership Project',
                'Social Entrepreneurship Project',
                'AI & Digital Business Project',
                'Business Competition',
                'Community Impact Project',
                'And many more practical business projects...',
            ],
        ],
        [
            'heading' => 'Participation & Appreciation Certificates',
            'intro' => 'Students may receive <strong>Participation/Appreciation Certificates by Faculties of IIM</strong> for eligible workshops, seminars, masterclasses, training programs, and special learning sessions conducted under the applicable collaboration framework.',
            'footer' => 'These certificates are awarded for eligible programs conducted under the applicable collaboration framework.',
        ],
        [
            'type' => 'benefits',
            'heading' => 'Why BNS Certification Matters',
            'list_heading' => 'Our certification framework helps students:',
            'checklist' => [
                'Build a Strong Student Portfolio',
                'Showcase Practical Skills',
                'Demonstrate Leadership & Initiative',
                'Highlight Business & Entrepreneurial Learning',
                'Build Confidence & Credibility',
                'Prepare for Future Education & Career Opportunities',
                'Celebrate Continuous Learning & Achievement',
            ],
        ],
    ],
    'taglines' => [
        'Every Session Builds Knowledge.',
        'Every Project Builds Experience.',
        'Every Certificate Builds Confidence.',
        'Learn Today. Build Tomorrow. Lead Forever.',
    ],
];
