<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Youth Business School',
    'title' => 'Frequently Asked Questions (FAQs)',
    'parts' => [
        [
            'questions' => [
                [
                    'number' => 1,
                    'question' => 'What is Youth Business School?',
                    'answers' => [
                        'Youth Business School is a 3-Year Practical Business Education Program designed for college students who aspire to become entrepreneurs, startup founders, business leaders, innovators, and future wealth creators.',
                        'Students learn the complete journey from Idea → Startup → Business → Scale-up → Corporate → IPO through practical learning.',
                    ],
                ],
                [
                    'number' => 2,
                    'question' => 'Who can join this program?',
                    'answers' => [
                        'College Students',
                        'Undergraduate Students',
                        'Postgraduate Students',
                        'Diploma Students',
                        'Engineering Students',
                        'Commerce Students',
                        'Science Students',
                        'Arts Students',
                        'Law Students',
                        'Medical & Pharmacy Students',
                        'Management Students',
                        'Young Entrepreneurs',
                        'Startup Founders',
                        'Fresh Graduates',
                        'Family Business Successors',
                        'And many more eligible youth.',
                    ],
                ],
                [
                    'number' => 3,
                    'question' => 'What is the duration of the program?',
                    'answers' => [
                        '3 Years',
                        '300 Interactive Sessions',
                        '600 Learning Hours',
                        'Weekly 2 Sessions',
                        '4 Hours Per Week',
                        'Practical Business Learning',
                    ],
                ],
                [
                    'number' => 4,
                    'question' => 'What is the learning journey?',
                    'answers' => [
                        'Year 1 – Youth Foundation School',
                        'Year 2 – Youth Startup School',
                        'Year 3 – Youth Business Growth School (Scale-Up School)',
                        'Students progress from Idea to Startup and Startup to IPO through structured learning.',
                    ],
                ],
                [
                    'number' => 5,
                    'question' => 'What subjects will I learn?',
                    'answers' => [
                        'Entrepreneurship',
                        'Startup Development',
                        'Business Strategy',
                        'Marketing',
                        'Digital Marketing',
                        'Branding',
                        'Sales',
                        'Artificial Intelligence (AI)',
                        'Accounting',
                        'Finance',
                        'Human Resources',
                        'Leadership',
                        'Business Communication',
                        'Business Planning',
                        'Business Operations',
                        'Corporate Management',
                        'Business Funding',
                        'Investor Readiness',
                        'IPO Fundamentals',
                        'Export Business',
                        'Global Business',
                        'And many more future-ready business topics.',
                    ],
                ],
                [
                    'number' => 6,
                    'question' => 'Is the program practical or theoretical?',
                    'answers' => [
                        'The program focuses on practical learning through:',
                        'Live Business Projects',
                        'Startup Challenges',
                        'Business Case Studies',
                        'Workshops',
                        'Masterclasses',
                        'Business Simulations',
                        'Industry Visits',
                        'Mentoring',
                        'Networking Events',
                        'Capstone Projects',
                        'And many more experiential learning opportunities.',
                    ],
                ],
                [
                    'number' => 7,
                    'question' => 'Is the syllabus industry-oriented?',
                    'answers' => [
                        'Yes.',
                        'The syllabus and learning methodology are developed with the guidance of Faculties of IIM, as per the applicable collaboration framework, and are designed to meet the needs of today\'s startup and business ecosystem.',
                    ],
                ],
                [
                    'number' => 8,
                    'question' => 'Who will teach the program?',
                    'answers' => [
                        'Students learn from:',
                        'BNS-Trained Faculties',
                        'Business Coaches',
                        'Industry Experts',
                        'Entrepreneurs',
                        'Startup Mentors',
                        'Corporate Leaders',
                        'Selected sessions by Faculties of IIM, where applicable.',
                    ],
                ],
                [
                    'number' => 9,
                    'question' => 'Will I receive certificates?',
                    'answers' => [
                        'Participants may receive:',
                        'Year-wise Completion Certificates',
                        'Program Completion Certificate',
                        'Skill Certificates',
                        'Project Certificates',
                        'Leadership Certificates',
                        'Achievement Certificates',
                        'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
                    ],
                ],
                [
                    'number' => 10,
                    'question' => 'Is previous business experience required?',
                    'answers' => [
                        'No.',
                        'No prior business experience is required.',
                        'Whether you have a startup idea, want to join your family business, or simply wish to learn entrepreneurship, this program is designed for beginners as well as aspiring founders.',
                    ],
                ],
                [
                    'number' => 11,
                    'question' => 'Will I learn Artificial Intelligence (AI)?',
                    'answers' => [
                        'Yes.',
                        'Students learn:',
                        'AI Fundamentals',
                        'AI for Business',
                        'AI Productivity Tools',
                        'Prompt Engineering',
                        'AI for Marketing',
                        'AI for Sales',
                        'Business Automation',
                        'AI for Decision Making',
                        'And many more AI applications.',
                    ],
                ],
                [
                    'number' => 12,
                    'question' => 'Will I learn Digital Marketing?',
                    'answers' => [
                        'Yes.',
                        'Topics include:',
                        'Social Media Marketing',
                        'SEO',
                        'Google Business Profile',
                        'Content Marketing',
                        'Performance Marketing',
                        'YouTube Marketing',
                        'LinkedIn Marketing',
                        'E-Commerce',
                        'Online Branding',
                        'Digital Business Growth',
                        'And many more digital marketing concepts.',
                    ],
                ],
                [
                    'number' => 13,
                    'question' => 'Will there be networking opportunities?',
                    'answers' => [
                        'Yes.',
                        'Students will connect with:',
                        'Entrepreneurs',
                        'Investors',
                        'Startup Founders',
                        'Industry Experts',
                        'Business Coaches',
                        'Corporate Leaders',
                        'Mentors',
                        'Alumni',
                        'Fellow Students',
                        'And many more professionals.',
                    ],
                ],
                [
                    'number' => 14,
                    'question' => 'How will this program help my career?',
                    'answers' => [
                        'The program helps you:',
                        'Build a Startup',
                        'Develop Leadership Skills',
                        'Improve Employability',
                        'Strengthen Business Knowledge',
                        'Build Financial Intelligence',
                        'Create Professional Networks',
                        'Prepare for Corporate Leadership',
                        'Become a Future Entrepreneur',
                        'Create Employment',
                        'Build Long-Term Wealth',
                        'And many more career advantages.',
                    ],
                ],
                [
                    'number' => 15,
                    'question' => 'Why should I choose BNS?',
                    'answers' => [
                        'Because BNS provides:',
                        'Practical Business Education',
                        '3-Year Structured Learning',
                        'Idea to IPO Learning Journey',
                        'Industry-Oriented Curriculum',
                        'AI & Digital Business Learning',
                        'Startup Mentorship',
                        'Live Business Projects',
                        'Business Coaching',
                        'Professional Certifications',
                        'Learning guided through collaboration with Faculties of IIM, where applicable',
                        'Future-Ready Skills',
                        'Lifelong Learning Community',
                        'And many more opportunities for personal and professional growth.',
                    ],
                ],
            ],
            'footer' => [
                'philosophy' => [
                    'heading' => 'Still Have Questions?',
                    'intro' => 'Our Admission Team is ready to help you understand the curriculum, eligibility, certifications, admissions, and your entrepreneurial journey.',
                    'lines' => [],
                ],
                'taglines' => [
                    'Dream Big. Build Bigger.',
                    'Don\'t Chase Jobs. Create Jobs.',
                    'From Idea to Startup. From Startup to IPO.',
                    'Learn Today. Launch Tomorrow. Scale Forever.',
                ],
            ],
        ],
    ],
];
