<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Women Business School',
    'title' => 'Certifications',
    'subtitle' => 'Recognizing Your Learning, Skills, Leadership & Entrepreneurial Journey',
    'intro' => [
        'At Business Navachar School (BNS), certifications are more than a document—they recognize your <strong>entrepreneurial journey, practical learning, business skills, leadership, innovation, and commitment towards continuous growth</strong>.',
    ],
    'intro_closing' => 'Throughout the 2-Year Women Business School Program, participants have the opportunity to earn multiple professional certifications that strengthen their business profile, professional credibility, and entrepreneurial confidence.',
    'sections' => [
        [
            'type' => 'year_certificates',
            'heading' => 'Year-wise Completion Certificates',
            'intro' => 'Participants who successfully complete each academic year may receive:',
            'certificates' => [
                [
                    'year' => 1,
                    'name' => 'Women Startup School Completion Certificate',
                    'description' => 'Recognition for successfully completing the first year in:',
                    'areas' => [
                        'Entrepreneurship',
                        'Startup Development',
                        'Marketing',
                        'Branding',
                        'Digital Marketing',
                        'Artificial Intelligence (AI)',
                        'Financial Literacy',
                        'Leadership',
                        'Business Planning',
                        'And many more future-ready business skills.',
                    ],
                ],
                [
                    'year' => 2,
                    'name' => 'Women Business Growth School Completion Certificate',
                    'description' => 'Recognition for successfully completing advanced learning in:',
                    'areas' => [
                        'Business Growth',
                        'Business Strategy',
                        'Sales Excellence',
                        'Finance & Accounting',
                        'Human Resource Management',
                        'Business Operations',
                        'AI & Automation',
                        'Leadership',
                        'Business Expansion',
                        'Business Excellence',
                        'And many more advanced business concepts.',
                    ],
                ],
            ],
        ],
        [
            'type' => 'graduation',
            'heading' => 'Final Graduation Certificate',
            'intro' => 'Upon successful completion of the 2-Year Women Business School Program, participants may receive the:',
            'highlight_title' => 'Business Navachar School (BNS) – Women Business School Graduation Certificate',
            'list_heading' => 'Recognizing:',
            'checklist' => [
                'Successful Completion of the 2-Year Program.',
                '200 Interactive Sessions.',
                '400 Learning Hours.',
                'Practical Business Education.',
                'Entrepreneurial Development.',
                'Leadership Development.',
                'Business Project Completion.',
                'Commitment to Lifelong Learning.',
            ],
        ],
        [
            'type' => 'skills',
            'heading' => 'Skill Development Certificates',
            'intro' => 'Participants may receive Skill Certificates in:',
            'items' => [
                'Entrepreneurship',
                'Startup Development',
                'Business Strategy',
                'Marketing',
                'Sales',
                'Branding',
                'Digital Marketing',
                'Artificial Intelligence (AI)',
                'Prompt Engineering',
                'Finance',
                'Accounting',
                'Human Resource Management',
                'Leadership Development',
                'Business Communication',
                'Personal Branding',
                'Customer Relationship Management (CRM)',
                'Business Automation',
                'Business Analytics',
                'E-Commerce',
                'Innovation & Design Thinking',
                'And many more future-ready business skills.',
            ],
        ],
        [
            'type' => 'projects',
            'heading' => 'Project Completion Certificates',
            'intro' => 'Participants may receive Project Certificates for:',
            'items' => [
                'Startup Project',
                'Business Plan Project',
                'Product Development Project',
                'Market Research Project',
                'Branding Project',
                'Marketing Campaign Project',
                'Digital Marketing Project',
                'AI Business Application Project',
                'Business Growth Project',
                'Customer Experience Project',
                'Leadership Project',
                'Business Excellence Project',
                'Social Impact Project',
                'Capstone Business Project',
                'And many more practical business projects.',
            ],
        ],
        [
            'heading' => 'Participation & Appreciation Certificates',
            'intro' => 'Participants may receive Participation/Appreciation Certificates by Faculties of IIM for eligible:',
            'checklist' => [
                'Workshops',
                'Seminars',
                'Masterclasses',
                'Business Conferences',
                'Women Entrepreneurship Summits',
                'Startup Bootcamps',
                'Training Programs',
                'Business Networking Events',
                'Leadership Programs',
                'Special Learning Sessions',
            ],
            'footer' => 'These certificates are awarded for eligible programs conducted under the applicable collaboration framework.',
        ],
        [
            'heading' => 'Achievement & Recognition Certificates',
            'intro' => 'Outstanding participants may receive:',
            'checklist' => [
                'Best Women Entrepreneur Award',
                'Startup Excellence Award',
                'Leadership Excellence Award',
                'Innovation Excellence Award',
                'Business Growth Excellence Award',
                'Best Business Plan Award',
                'Best Business Pitch Award',
                'Digital Business Excellence Award',
                'AI Innovation Award',
                'Outstanding Project Award',
                'Best Performer Award',
                'Business Excellence Award',
                'Women Leadership Award',
                'And many more awards based on participation, innovation, leadership, and performance.',
            ],
        ],
        [
            'type' => 'benefits',
            'heading' => 'Why BNS Certifications Matter',
            'list_heading' => 'BNS certifications help participants:',
            'checklist' => [
                'Build a strong professional profile.',
                'Enhance business credibility.',
                'Showcase practical business knowledge.',
                'Demonstrate entrepreneurial and leadership skills.',
                'Strengthen personal and business branding.',
                'Highlight project-based learning.',
                'Build confidence for business growth.',
                'Support future business, career, and networking opportunities.',
                'Showcase commitment to lifelong learning and professional excellence.',
            ],
        ],
    ],
    'taglines' => [
        'Every Session Builds Knowledge.',
        'Every Project Builds Experience.',
        'Every Certificate Reflects Your Growth.',
        'Every Achievement Inspires Your Success.',
        'Dream → Idea → Startup → Business Growth',
        'Empowered Women. Prosperous Families. Strong India.',
        'Learn. Launch. Grow. Lead.',
    ],
];
