<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Program Structure',
    'subtitle' => 'Growth Batch – Business to IPO Journey',
    'tagline' => 'From Business to Brand • Brand to Corporate • Corporate to IPO',
    'stats' => [
        ['icon' => 'fas fa-chalkboard-teacher', 'text' => '100 Sessions'],
        ['icon' => 'fas fa-clock', 'text' => '200 Learning Hours'],
    ],
    'modules' => [
        [
            'heading' => 'Module 1 : Business Foundation & Entrepreneurial Mindset (Sessions 1–10)',
            'topics' => [
                '1. Entrepreneurial Mindset',
                '2. Vision, Mission & Goal Setting',
                '3. Business Opportunity Identification',
                '4. Business Model Innovation',
                '5. Business Model Canvas',
                '6. Business Planning',
                '7. Design Thinking',
                '8. Business Ethics',
                '9. Leadership Mindset',
                '10. Business Launch Blueprint',
            ],
        ],
        [
            'heading' => 'Module 2 : Marketing, Branding & Sales (Sessions 11–20)',
            'topics' => [
                '11. Marketing Fundamentals',
                '12. Market Research',
                '13. Consumer Psychology',
                '14. Branding Strategy',
                '15. Product Positioning',
                '16. Sales Strategy',
                '17. Customer Relationship Management (CRM)',
                '18. Customer Experience',
                '19. Business Networking',
                '20. Personal Branding',
            ],
        ],
        [
            'heading' => 'Module 3 : Digital Marketing & Business Growth (Sessions 21–30)',
            'topics' => [
                '21. Digital Marketing Fundamentals',
                '22. Social Media Marketing',
                '23. Facebook & Instagram Marketing',
                '24. YouTube Marketing',
                '25. LinkedIn Marketing',
                '26. Google Business Profile',
                '27. Search Engine Optimization (SEO)',
                '28. Content Marketing',
                '29. Performance Marketing & Analytics',
                '30. E-Commerce & Online Business',
            ],
        ],
        [
            'heading' => 'Module 4 : AI & Future Business (Sessions 31–40)',
            'topics' => [
                '31. Introduction to Artificial Intelligence (AI)',
                '32. AI for Business Growth',
                '33. Generative AI Tools',
                '34. Prompt Engineering',
                '35. AI for Marketing',
                '36. AI for Sales',
                '37. AI for Customer Support',
                '38. Business Automation using AI',
                '39. AI Productivity Tools',
                '40. Future Technologies & Business Trends',
            ],
        ],
        [
            'heading' => 'Module 5 : Accounting, Finance & Wealth Creation (Sessions 41–50)',
            'topics' => [
                '41. Business Accounting',
                '42. Bookkeeping',
                '43. Profit & Loss Statement',
                '44. Balance Sheet',
                '45. Cash Flow Management',
                '46. Costing & Pricing',
                '47. Budgeting',
                '48. Taxation Basics',
                '49. Financial Planning',
                '50. Wealth Creation & Investment',
            ],
        ],
        [
            'heading' => 'Module 6 : HR, Recruitment & Leadership (Sessions 51–60)',
            'topics' => [
                '51. Human Resource Management',
                '52. Organization Structure',
                '53. Recruitment Strategy',
                '54. Interview & Selection',
                '55. Employee Onboarding',
                '56. Team Training & Development',
                '57. Performance Management',
                '58. Leadership Development',
                '59. Team Building',
                '60. Company Culture',
            ],
        ],
        [
            'heading' => 'Module 7 : Operations, Systems & Scale-up (Sessions 61–70)',
            'topics' => [
                '61. SOP Development',
                '62. Business Systems',
                '63. Process Improvement',
                '64. Quality Management',
                '65. Business Automation',
                '66. Business Analytics',
                '67. Risk Management',
                '68. Franchise Business Model',
                '69. Business Expansion Strategy',
                '70. Business Diversification',
            ],
        ],
        [
            'heading' => 'Module 8 : Funding & Corporate Management (Sessions 71–80)',
            'topics' => [
                '71. Bootstrapping',
                '72. Bank Finance',
                '73. Government Schemes',
                '74. Angel Investors',
                '75. Venture Capital',
                '76. Private Equity',
                '77. Business Valuation',
                '78. Corporate Governance',
                '79. Company Law & Compliance',
                '80. Board of Directors',
            ],
        ],
        [
            'heading' => 'Module 9 : National to Global Business (Sessions 81–90)',
            'topics' => [
                '81. Export Business',
                '82. International Marketing',
                '83. Global Branding',
                '84. International Business Strategy',
                '85. Cross-Border Business',
                '86. Business Ecosystem Development',
                '87. Holding Company Concept',
                '88. Multi-Brand Business Strategy',
                '89. Building a Business Chain',
                '90. Building a Global Business Empire',
            ],
        ],
        [
            'heading' => 'Module 10 : Corporate to IPO Journey (Sessions 91–100)',
            'topics' => [
                '91. Startup to Corporate Journey',
                '92. Corporate Strategy',
                '93. Investor Relations',
                '94. Fundraising Strategy',
                '95. SME IPO',
                '96. Main Board IPO',
                '97. IPO Process',
                '98. Life After IPO',
                '99. Billion-Dollar Business Roadmap',
                '100. Vision 2047 – From Entrepreneur to Global Business Leader',
            ],
        ],
    ],
    'key_areas_heading' => 'Key Learning Areas',
    'key_areas_intro' => 'Participants will gain practical knowledge in:',
    'key_areas' => [
        'Entrepreneurship',
        'Business Strategy',
        'Marketing',
        'Branding',
        'Sales',
        'Digital Marketing',
        'Social Media Marketing',
        'SEO',
        'Google Business Profile',
        'E-Commerce',
        'Artificial Intelligence (AI)',
        'Prompt Engineering',
        'Business Automation',
        'Accounting',
        'Finance',
        'Taxation',
        'Human Resource Management',
        'Recruitment',
        'Team Training',
        'Leadership',
        'Operations Management',
        'SOP Development',
        'Customer Relationship Management',
        'Business Analytics',
        'Business Funding',
        'Corporate Governance',
        'Company Law',
        'Export Business',
        'International Business',
        'Business Valuation',
        'Investor Readiness',
        'IPO Journey',
        'Wealth Creation',
        'Legacy Building',
        'And many more practical business concepts, case studies, workshops, masterclasses, projects, and real-world business experiences.',
    ],
    'taglines' => [
        'Learn Business. Build Brands. Scale Companies. Create Wealth. Go IPO.',
        'Learn. Grow. Scale. Lead. Prosper.',
    ],
];
