<?php

return [
    [
        'key' => 'vision',
        'label' => 'Vision',
        'icon' => 'fas fa-eye',
        'description' => 'Women Business School vision — empowering women entrepreneurs, building businesses & strengthening India.',
        'action' => 'modal',
        'modal' => 'vision',
        'modal_cta' => 'Read Vision',
    ],
    [
        'key' => 'mission',
        'label' => 'Mission',
        'icon' => 'fas fa-bullseye',
        'description' => 'Empowering women to build businesses, create wealth & transform society.',
        'action' => 'modal',
        'modal' => 'mission',
        'modal_cta' => 'Read Mission',
    ],
    [
        'key' => 'vision_2047',
        'label' => 'Vision 2047',
        'icon' => 'fas fa-flag',
        'description' => 'Empowering women, building businesses & transforming India towards Viksit Bharat 2047.',
        'action' => 'modal',
        'modal' => 'vision_2047',
        'modal_id' => 'bnsVision2047Modal',
        'modal_cta' => 'Read Vision 2047',
    ],
    [
        'key' => 'eligibility',
        'label' => 'Eligibility Criteria',
        'icon' => 'fas fa-user-check',
        'description' => 'Women entrepreneurs, aspiring founders & professionals — who can join the Women Business School.',
        'action' => 'modal',
        'modal' => 'eligibility',
        'modal_id' => 'bnsEligibilityModal',
        'modal_cta' => 'View Eligibility',
    ],
    [
        'key' => 'core_values',
        'label' => 'Core Values',
        'icon' => 'fas fa-gem',
        'description' => '16 values guiding every women learner — entrepreneurship, leadership & empowerment.',
        'action' => 'modal',
        'modal' => 'core_values',
        'modal_id' => 'bnsCoreValuesModal',
        'modal_cta' => 'Read Core Values',
    ],
    [
        'key' => 'founder_message',
        'label' => "Founder's Message",
        'icon' => 'fas fa-quote-left',
        'description' => 'A personal message from Dr. Mehul Rupani to women entrepreneurs, dreamers & changemakers.',
        'action' => 'modal',
        'modal' => 'founder_message',
        'modal_id' => 'bnsFounderMessageModal',
        'modal_cta' => 'Read Message',
    ],
    [
        'key' => 'why_bns',
        'label' => 'Why Choose BNS?',
        'icon' => 'fas fa-star',
        'description' => 'Why women choose BNS — 2-year program, practical learning, mentorship & growth.',
        'action' => 'modal',
        'modal' => 'why_bns',
        'modal_id' => 'bnsWhyBnsModal',
        'modal_cta' => 'Discover Why',
    ],
    [
        'key' => 'why_business_education',
        'label' => 'Why Business Education?',
        'icon' => 'fas fa-graduation-cap',
        'description' => 'Why business education matters for women — entrepreneurship, leadership & wealth creation.',
        'action' => 'modal',
        'modal' => 'why_business_education',
        'modal_id' => 'bnsWhyBusinessEducationModal',
        'modal_cta' => 'Read More',
    ],
    [
        'key' => 'prosperity_mission',
        'label' => 'Prosperity Mission',
        'icon' => 'fas fa-landmark',
        'description' => "India's Prosperity Mission — empowering women, strengthening families & building Viksit Bharat 2047.",
        'action' => 'modal',
        'modal' => 'prosperity_mission',
        'modal_id' => 'bnsProsperityMissionModal',
        'modal_cta' => 'Read Mission',
    ],
    [
        'key' => 'program_structure',
        'label' => 'Program Structure',
        'icon' => 'fas fa-sitemap',
        'description' => '2-Year Women Business School — Startup School & Business Growth School.',
        'action' => 'modal',
        'modal' => 'program_structure',
        'modal_id' => 'bnsProgramStructureModal',
        'modal_cta' => 'View Structure',
    ],
    [
        'key' => 'certification',
        'label' => 'Certification',
        'icon' => 'fas fa-certificate',
        'description' => 'Year-wise, skill & project certificates recognizing your entrepreneurial journey.',
        'action' => 'modal',
        'modal' => 'certification',
        'modal_id' => 'bnsCertificationModal',
        'modal_cta' => 'View Certificates',
    ],
    [
        'key' => 'faqs',
        'label' => 'FAQs',
        'icon' => 'fas fa-question-circle',
        'description' => 'Frequently asked questions — program, eligibility, learning & certification.',
        'action' => 'modal',
        'modal' => 'faqs',
        'modal_id' => 'bnsFaqsModal',
        'modal_cta' => 'Read FAQs',
    ],
];
