<?php

return [
    [
        'key' => 'vision',
        'label' => 'Vision',
        'icon' => 'fas fa-eye',
        'description' => 'Job Excellence School & Business Empire School — vision for professionals and business owners.',
        'action' => 'modal',
        'modal' => 'vision',
        'modal_cta' => 'Read Vision',
    ],
    [
        'key' => 'mission',
        'label' => 'Mission',
        'icon' => 'fas fa-bullseye',
        'description' => 'Job Excellence School & Business Empire School — mission for professionals and business owners.',
        'action' => 'modal',
        'modal' => 'mission',
        'modal_cta' => 'Read Mission',
    ],
    [
        'key' => 'vision_2047',
        'label' => 'Vision 2047',
        'icon' => 'fas fa-flag',
        'description' => 'BNS commitment to Viksit Bharat 2047 — strengthening businesses, empowering professionals, building India.',
        'action' => 'modal',
        'modal' => 'vision_2047',
        'modal_id' => 'bnsVision2047Modal',
        'modal_cta' => 'Read Vision 2047',
    ],
    [
        'key' => 'eligibility',
        'label' => 'Eligibility Criteria',
        'icon' => 'fas fa-user-check',
        'description' => 'Job Excellence School & Business Empire School — who can join each one-year executive program.',
        'action' => 'modal',
        'modal' => 'eligibility',
        'modal_id' => 'bnsEligibilityModal',
        'modal_cta' => 'View Eligibility',
    ],
    [
        'key' => 'core_values',
        'label' => 'Core Values',
        'icon' => 'fas fa-gem',
        'description' => 'Values that guide BNS learners — learn, innovate, grow sustainably, and lead responsibly.',
        'action' => 'modal',
        'modal' => 'core_values',
        'modal_id' => 'bnsCoreValuesModal',
        'modal_cta' => 'Read Core Values',
    ],
    [
        'key' => 'founder_message',
        'label' => "Founder's Message",
        'icon' => 'fas fa-quote-left',
        'description' => 'A personal message from Dr. Mehul Rupani for Job Excellence School & Business Empire School.',
        'action' => 'modal',
        'modal' => 'founder_message',
        'modal_id' => 'bnsFounderMessageModal',
        'modal_cta' => 'Read Message',
    ],
    [
        'key' => 'why_bns',
        'label' => 'Why BNS?',
        'icon' => 'fas fa-star',
        'description' => 'Why professionals & business owners choose BNS — executive learning, AI, coaching & growth.',
        'action' => 'modal',
        'modal' => 'why_bns',
        'modal_id' => 'bnsWhyBnsModal',
        'modal_cta' => 'Discover Why',
    ],
    [
        'key' => 'why_business_education',
        'label' => 'Why Business Education?',
        'icon' => 'fas fa-graduation-cap',
        'description' => 'Why business education matters — mindset, leadership, finance, innovation & career growth.',
        'action' => 'modal',
        'modal' => 'why_business_education',
        'modal_id' => 'bnsWhyBusinessEducationModal',
        'modal_cta' => 'Read More',
    ],
    [
        'key' => 'prosperity_mission',
        'label' => 'Prosperity Vision',
        'icon' => 'fas fa-landmark',
        'description' => "India's Prosperity Vision — empowering professionals, strengthening businesses & Viksit Bharat 2047.",
        'action' => 'modal',
        'modal' => 'prosperity_mission',
        'modal_id' => 'bnsProsperityMissionModal',
        'modal_cta' => 'Read Vision',
    ],
    [
        'key' => 'program_structure',
        'label' => 'Program Structure',
        'icon' => 'fas fa-sitemap',
        'description' => 'Wealth Creation to IPO Mastery — 100 sessions, 12 modules, from wealth foundation to legacy & global business.',
        'action' => 'modal',
        'modal' => 'program_structure',
        'modal_id' => 'bnsProgramStructureModal',
        'modal_cta' => 'View Syllabus',
    ],
    [
        'key' => 'certification',
        'label' => 'Certification',
        'icon' => 'fas fa-certificate',
        'description' => 'Executive Business School certifications — graduation, skills, projects, excellence awards & Faculties of IIM recognition.',
        'action' => 'modal',
        'modal' => 'certification',
        'modal_id' => 'bnsCertificationModal',
        'modal_cta' => 'View Certificates',
    ],
    [
        'key' => 'faqs',
        'label' => 'FAQs',
        'icon' => 'fas fa-question-circle',
        'description' => '20 FAQs — eligibility, learning model, AI, wealth creation, IPO, certifications & outcomes.',
        'action' => 'modal',
        'modal' => 'faqs',
        'modal_id' => 'bnsFaqsModal',
        'modal_cta' => 'Read FAQs',
    ],
];
