<?php

return [
    'eyebrow' => 'School Students',
    'title' => 'Frequently Asked Questions (FAQs)',
    'parts' => [
        [
            'heading' => 'Part 1 – General Questions (Q1–Q10)',
            'questions' => [
                [
                    'number' => 1,
                    'question' => 'What is Business Navachar School (BNS)?',
                    'answers' => [
                        'A structured Business Education Program for school students.',
                        'Develops entrepreneurial mindset.',
                        'Builds leadership and communication skills.',
                        'Teaches financial literacy and wealth awareness.',
                        'Focuses on innovation, creativity, and problem-solving.',
                        'Provides practical, project-based learning.',
                        'Prepares students for future careers and businesses.',
                        'Builds confidence and real-world skills.',
                        'And many more future-ready competencies.',
                    ],
                ],
                [
                    'number' => 2,
                    'question' => 'Why was BNS established?',
                    'answers' => [
                        'To bridge the gap between traditional education and business education.',
                        'To prepare students for the future economy.',
                        'To develop entrepreneurial thinking from an early age.',
                        'To teach practical life skills.',
                        'To promote financial literacy.',
                        'To encourage innovation and creativity.',
                        'To build future leaders and job creators.',
                        'To contribute to Viksit Bharat 2047.',
                    ],
                ],
                [
                    'number' => 3,
                    'question' => 'What makes BNS different from traditional schools?',
                    'answers' => [
                        'Practical learning instead of only theory.',
                        'Business-focused education.',
                        'Project-based learning.',
                        'Activity-based learning.',
                        'Startup exposure.',
                        'Industry interaction.',
                        'Leadership development.',
                        'Business simulations.',
                        'AI and digital business awareness.',
                        'Learning beyond textbooks.',
                        'And many more practical experiences.',
                    ],
                ],
                [
                    'number' => 4,
                    'question' => 'Who can join BNS?',
                    'answers' => [
                        'School students from eligible grades.',
                        'Students from any education board.',
                        'Students with or without business knowledge.',
                        'Curious learners.',
                        'Future entrepreneurs.',
                        'Future professionals.',
                        'Future business leaders.',
                        'Anyone willing to learn and grow.',
                    ],
                ],
                [
                    'number' => 5,
                    'question' => 'Is BNS a full-time school or an additional learning program?',
                    'answers' => [
                        'It is an additional learning program.',
                        'Students continue their regular schooling.',
                        'Conducted through weekly sessions.',
                        'Complements academic education.',
                        'Focuses on practical business learning.',
                        'Enhances future-ready skills.',
                    ],
                ],
                [
                    'number' => 6,
                    'question' => 'Why should school students learn business?',
                    'answers' => [
                        'To understand how businesses work.',
                        'To develop entrepreneurial thinking.',
                        'To improve financial literacy.',
                        'To solve real-world problems.',
                        'To build leadership skills.',
                        'To improve communication.',
                        'To make better decisions.',
                        'To prepare for future careers.',
                        'To become confident individuals.',
                        'And many more lifelong benefits.',
                    ],
                ],
                [
                    'number' => 7,
                    'question' => 'Is business education useful for every student?',
                    'answers' => [
                        'Yes, regardless of career choice.',
                        'Helpful for entrepreneurs.',
                        'Useful for doctors.',
                        'Useful for engineers.',
                        'Useful for lawyers.',
                        'Useful for scientists.',
                        'Useful for artists.',
                        'Useful for corporate professionals.',
                        'Useful for family business successors.',
                        'Builds essential life skills for everyone.',
                    ],
                ],
                [
                    'number' => 8,
                    'question' => 'What is the vision of BNS?',
                    'answers' => [
                        'To build future entrepreneurs.',
                        'To nurture innovators.',
                        'To develop business leaders.',
                        'To promote ethical leadership.',
                        'To create financially aware citizens.',
                        'To inspire innovation.',
                        'To create job creators.',
                        'To support Viksit Bharat 2047.',
                        'To contribute to India\'s prosperity.',
                    ],
                ],
                [
                    'number' => 9,
                    'question' => 'What is India\'s Prosperity Mission?',
                    'answers' => [
                        'Empower young minds.',
                        'Promote entrepreneurship.',
                        'Build financial literacy.',
                        'Encourage innovation.',
                        'Develop leadership.',
                        'Create employment opportunities.',
                        'Strengthen India\'s economy.',
                        'Build responsible citizens.',
                        'Support Viksit Bharat 2047.',
                    ],
                ],
                [
                    'number' => 10,
                    'question' => 'Why should students start business education at an early age?',
                    'answers' => [
                        'Develop entrepreneurial thinking early.',
                        'Build confidence.',
                        'Improve creativity.',
                        'Learn financial discipline.',
                        'Strengthen leadership skills.',
                        'Build communication skills.',
                        'Develop problem-solving ability.',
                        'Gain practical experience.',
                        'Stay ahead of future opportunities.',
                        'Build lifelong success habits.',
                        'And many more future-ready advantages.',
                    ],
                ],
            ],
        ],
        [
            'heading' => 'Part 2 – Program & Curriculum (Q11–Q20)',
            'questions' => [
                [
                    'number' => 11,
                    'question' => 'What is the duration of the program?',
                    'answers' => [
                        '5-Year Structured Business Education Program.',
                        'Weekly learning model.',
                        'Practical and project-based curriculum.',
                        '500 Interactive Sessions.',
                        '1000 Learning Hours.',
                        'Continuous skill development throughout the journey.',
                    ],
                ],
                [
                    'number' => 12,
                    'question' => 'How many years does the program include?',
                    'answers' => [
                        'Year 1: Idea Foundation School',
                        'Year 2: Startup School',
                        'Year 3: Growth Business School',
                        'Year 4: Scale-up Business School',
                        'Year 5: Corporate & IPO School',
                    ],
                ],
                [
                    'number' => 13,
                    'question' => 'How many sessions are conducted every week?',
                    'answers' => [
                        '2 Interactive Sessions every week.',
                        '4 Learning Hours per week.',
                        'Practical classroom learning.',
                        'Activities and discussions.',
                        'Business case studies.',
                        'Team-based learning.',
                        'And many more engaging learning experiences.',
                    ],
                ],
                [
                    'number' => 14,
                    'question' => 'How many learning hours are provided every year?',
                    'answers' => [
                        '100 Interactive Sessions annually.',
                        '200 Learning Hours every year.',
                        'Practical assignments.',
                        'Workshops and seminars.',
                        'Business competitions.',
                        'Startup activities.',
                        'Industry exposure.',
                        'And many more experiential learning opportunities.',
                    ],
                ],
                [
                    'number' => 15,
                    'question' => 'What is taught in Year 1 – Idea Foundation School?',
                    'answers' => [
                        'Entrepreneurial Mindset.',
                        'Creativity & Innovation.',
                        'Design Thinking.',
                        'Communication Skills.',
                        'Leadership Basics.',
                        'Financial Literacy.',
                        'Problem Solving.',
                        'Personality Development.',
                        'Goal Setting.',
                        'Teamwork.',
                        'Ethics & Values.',
                        'And many more foundational business and life skills.',
                    ],
                ],
                [
                    'number' => 16,
                    'question' => 'What is taught in Year 2 – Startup School?',
                    'answers' => [
                        'Startup Fundamentals.',
                        'Business Model Canvas.',
                        'Product Development.',
                        'Branding.',
                        'Marketing.',
                        'Sales Fundamentals.',
                        'Customer Research.',
                        'Business Planning.',
                        'Digital Business.',
                        'Pitch Presentation.',
                        'Business Validation.',
                        'And many more startup-building concepts.',
                    ],
                ],
                [
                    'number' => 17,
                    'question' => 'What is taught in Year 3 – Growth Business School?',
                    'answers' => [
                        'Business Growth Strategies.',
                        'Sales & Marketing.',
                        'Accounting & Finance.',
                        'Human Resource Management.',
                        'Operations Management.',
                        'Customer Relationship Management.',
                        'AI in Business.',
                        'Business Automation.',
                        'Strategic Decision Making.',
                        'Business Analytics.',
                        'Leadership Development.',
                        'And many more business growth concepts.',
                    ],
                ],
                [
                    'number' => 18,
                    'question' => 'What is taught in Year 4 – Scale-up Business School?',
                    'answers' => [
                        'Business Expansion.',
                        'SOP Development.',
                        'Business Systems.',
                        'Franchise Model.',
                        'Funding & Investment.',
                        'Technology Integration.',
                        'Export Business.',
                        'Corporate Structure.',
                        'Risk Management.',
                        'Business Sustainability.',
                        'Strategic Partnerships.',
                        'And many more scale-up and expansion strategies.',
                    ],
                ],
                [
                    'number' => 19,
                    'question' => 'What is taught in Year 5 – Corporate & IPO School?',
                    'answers' => [
                        'Corporate Governance.',
                        'Company Law Basics.',
                        'Corporate Leadership.',
                        'Investor Relations.',
                        'Financial Statements.',
                        'Stock Market Fundamentals.',
                        'IPO Process.',
                        'Business Valuation.',
                        'Wealth Creation.',
                        'Global Business Practices.',
                        'Legacy Building.',
                        'And many more corporate and IPO-related concepts.',
                    ],
                ],
                [
                    'number' => 20,
                    'question' => 'Will the curriculum be updated regularly?',
                    'answers' => [
                        'Yes, absolutely.',
                        'Curriculum is reviewed periodically.',
                        'Updated with industry trends.',
                        'Includes AI and emerging technologies.',
                        'Covers startup ecosystem developments.',
                        'Incorporates new business practices.',
                        'Focuses on future-ready skills.',
                        'Includes expert recommendations.',
                        'Ensures relevance for the changing global economy.',
                        'And many more improvements based on innovation and industry needs.',
                    ],
                ],
            ],
        ],
        [
            'heading' => 'Part 3 – Learning Methodology (Q21–Q30)',
            'questions' => [
                [
                    'number' => 21,
                    'question' => 'How do students learn at BNS?',
                    'answers' => [
                        'Activity-Based Learning.',
                        'Project-Based Learning.',
                        'Experiential Learning.',
                        'Interactive Classroom Sessions.',
                        'Business Simulations.',
                        'Case Studies.',
                        'Workshops & Seminars.',
                        'Industry Exposure.',
                        'Team Activities.',
                        'And many more practical learning methods.',
                    ],
                ],
                [
                    'number' => 22,
                    'question' => 'Is the learning practical or theoretical?',
                    'answers' => [
                        'Practical learning is the primary focus.',
                        'Theory is explained with real-life examples.',
                        'Hands-on activities.',
                        'Live business projects.',
                        'Business games.',
                        'Startup simulations.',
                        'Real-world problem solving.',
                        'And many more experiential learning experiences.',
                    ],
                ],
                [
                    'number' => 23,
                    'question' => 'Will students work on real projects?',
                    'answers' => [
                        'Yes.',
                        'Startup Projects.',
                        'Business Plan Development.',
                        'Product Development.',
                        'Market Research Projects.',
                        'Branding Projects.',
                        'Innovation Challenges.',
                        'Team Projects.',
                        'Community Projects.',
                        'And many more practical assignments.',
                    ],
                ],
                [
                    'number' => 24,
                    'question' => 'Are business competitions organized?',
                    'answers' => [
                        'Yes.',
                        'Business Plan Competitions.',
                        'Startup Challenges.',
                        'Innovation Contests.',
                        'Marketing Competitions.',
                        'Sales Challenges.',
                        'Business Quiz.',
                        'Product Presentation Competitions.',
                        'Leadership Challenges.',
                        'And many more competitive learning events.',
                    ],
                ],
                [
                    'number' => 25,
                    'question' => 'Are industrial visits included?',
                    'answers' => [
                        'Yes, wherever applicable.',
                        'Factory Visits.',
                        'Startup Visits.',
                        'Corporate Visits.',
                        'Business Visits.',
                        'Manufacturing Units.',
                        'Retail Businesses.',
                        'Service Industries.',
                        'Innovation Centres.',
                        'And many more industry exposure opportunities.',
                    ],
                ],
                [
                    'number' => 26,
                    'question' => 'Will students interact with entrepreneurs?',
                    'answers' => [
                        'Yes.',
                        'Successful Entrepreneurs.',
                        'Startup Founders.',
                        'Business Leaders.',
                        'Industry Experts.',
                        'Investors.',
                        'CEOs.',
                        'Business Mentors.',
                        'Corporate Professionals.',
                        'And many more inspiring personalities.',
                    ],
                ],
                [
                    'number' => 27,
                    'question' => 'Are workshops and seminars conducted regularly?',
                    'answers' => [
                        'Yes.',
                        'Entrepreneurship Workshops.',
                        'Leadership Workshops.',
                        'Financial Literacy Sessions.',
                        'AI & Technology Workshops.',
                        'Communication Skills.',
                        'Public Speaking.',
                        'Personality Development.',
                        'Business Seminars.',
                        'Masterclasses.',
                        'And many more knowledge-building events.',
                    ],
                ],
                [
                    'number' => 28,
                    'question' => 'Does BNS include AI and digital business learning?',
                    'answers' => [
                        'Yes.',
                        'Artificial Intelligence Basics.',
                        'AI for Business.',
                        'Digital Marketing.',
                        'Digital Entrepreneurship.',
                        'Social Media Business.',
                        'Business Automation.',
                        'Emerging Technologies.',
                        'Future Skills.',
                        'And many more digital business concepts.',
                    ],
                ],
                [
                    'number' => 29,
                    'question' => 'How are students assessed?',
                    'answers' => [
                        'Continuous Assessment.',
                        'Project Evaluation.',
                        'Practical Performance.',
                        'Presentations.',
                        'Team Activities.',
                        'Assignments.',
                        'Case Study Analysis.',
                        'Participation.',
                        'Innovation Challenges.',
                        'Skill Development.',
                        'Portfolio Assessment.',
                        'And many more evaluation methods.',
                    ],
                ],
                [
                    'number' => 30,
                    'question' => 'What skills will students develop?',
                    'answers' => [
                        'Entrepreneurial Mindset.',
                        'Leadership Skills.',
                        'Financial Literacy.',
                        'Communication Skills.',
                        'Public Speaking.',
                        'Creativity & Innovation.',
                        'Critical Thinking.',
                        'Problem Solving.',
                        'Decision Making.',
                        'Teamwork.',
                        'Marketing & Sales Skills.',
                        'Business Planning.',
                        'AI & Digital Skills.',
                        'Personality Development.',
                        'Confidence Building.',
                        'Ethical Values.',
                        'And many more future-ready competencies.',
                    ],
                ],
            ],
            'footer' => [
                'philosophy' => [
                    'heading' => 'Our Learning Philosophy',
                    'intro' => 'At BNS, students don\'t just learn...',
                    'lines' => [
                        'They Think.',
                        'They Create.',
                        'They Innovate.',
                        'They Lead.',
                        'They Build.',
                        'They Grow.',
                        'They Succeed.',
                    ],
                ],
                'taglines' => [
                    'Learning by Doing.',
                    'Dream Big. Build Bigger.',
                    'Don\'t Chase Jobs. Create Jobs.',
                    'Learn Today. Build Tomorrow. Lead Forever.',
                ],
            ],
        ],
        [
            'heading' => 'Part 4 – Admission & Eligibility (Q31–Q40)',
            'questions' => [
                [
                    'number' => 31,
                    'question' => 'Who is eligible for admission?',
                    'answers' => [
                        'School students meeting the prescribed eligibility criteria.',
                        'Students from recognized schools.',
                        'Students from any education board.',
                        'Students interested in entrepreneurship and business.',
                        'Students willing to learn practical life skills.',
                        'And many more eligible learners as per the admission guidelines.',
                    ],
                ],
                [
                    'number' => 32,
                    'question' => 'Is there an entrance test?',
                    'answers' => [
                        'Admission process may include an entrance test, interaction, interview, aptitude assessment, or orientation, depending on the program and admission policy.',
                        'The objective is to understand the student\'s interest and learning potential.',
                        'Details are shared during the admission process.',
                    ],
                ],
                [
                    'number' => 33,
                    'question' => 'What documents are required?',
                    'answers' => [
                        'Admission Application Form.',
                        'Passport Size Photographs.',
                        'Birth Date Proof.',
                        'School ID Card (if applicable).',
                        'Previous Academic Record (if applicable).',
                        'Parent/Guardian ID Proof.',
                        'Address Proof.',
                        'Any other documents as required by BNS.',
                    ],
                ],
                [
                    'number' => 34,
                    'question' => 'Can students from any school join?',
                    'answers' => [
                        'Yes.',
                        'Students from State Board schools.',
                        'CBSE schools.',
                        'ICSE schools.',
                        'International schools.',
                        'Other recognized education boards.',
                        'Homeschooling students (subject to policy).',
                        'And other eligible institutions.',
                    ],
                ],
                [
                    'number' => 35,
                    'question' => 'Are seats limited?',
                    'answers' => [
                        'Yes.',
                        'Limited seats are available in each batch.',
                        'Admissions are offered on a first-come, first-served basis or as per the admission policy.',
                        'Early registration is recommended.',
                    ],
                ],
                [
                    'number' => 36,
                    'question' => 'Is there an age criterion?',
                    'answers' => [
                        'Yes.',
                        'Admission is based on the program\'s age and class eligibility criteria.',
                        'Different batches may have different age groups.',
                        'Please refer to the latest admission guidelines.',
                    ],
                ],
                [
                    'number' => 37,
                    'question' => 'How can I apply for admission?',
                    'answers' => [
                        'Fill out the online or offline application form.',
                        'Submit the required documents.',
                        'Complete the admission process.',
                        'Attend counselling or orientation (if applicable).',
                        'Pay the applicable admission fees.',
                        'Receive admission confirmation.',
                    ],
                ],
                [
                    'number' => 38,
                    'question' => 'Is online admission available?',
                    'answers' => [
                        'Yes.',
                        'Online application facility is available.',
                        'Students can submit forms digitally.',
                        'Upload required documents online.',
                        'Complete the admission process conveniently.',
                        'Online support is available for assistance.',
                    ],
                ],
                [
                    'number' => 39,
                    'question' => 'Can I visit the campus before admission?',
                    'answers' => [
                        'Yes.',
                        'Students and parents are welcome to visit the campus.',
                        'Attend an information session.',
                        'Meet the admission team.',
                        'Understand the learning environment.',
                        'Explore the facilities.',
                        'Prior appointment may be required.',
                    ],
                ],
                [
                    'number' => 40,
                    'question' => 'Is counselling available before admission?',
                    'answers' => [
                        'Yes.',
                        'Career counselling.',
                        'Program guidance.',
                        'Parent counselling.',
                        'Student counselling.',
                        'Admission guidance.',
                        'Course selection support.',
                        'Future career planning.',
                        'Personalized assistance from the BNS team.',
                    ],
                ],
            ],
            'footer' => [
                'admission_heading' => 'Admission Made Simple',
                'steps' => [
                    'Check Eligibility',
                    'Submit Application',
                    'Complete Documentation',
                    'Attend Counselling / Orientation (if applicable)',
                    'Confirm Admission',
                    'Begin Your Business Learning Journey',
                ],
                'highlight' => 'Limited Seats. Unlimited Opportunities.',
                'taglines' => [
                    'Dream Big. Build Bigger.',
                    'Don\'t Chase Jobs. Create Jobs.',
                    'Learn Today. Build Tomorrow. Lead Forever.',
                ],
            ],
        ],
        [
            'heading' => 'Part 5 – Certification & Student Growth (Q41–Q50)',
            'questions' => [
                [
                    'number' => 41,
                    'question' => 'Will students receive certificates?',
                    'answers' => [
                        'Yes.',
                        'Year-wise Completion Certificates.',
                        'Skill Certificates.',
                        'Project Certificates.',
                        'Participation Certificates.',
                        'Achievement Certificates.',
                        'Final Graduation Certificate.',
                        'Participation / Appreciation Certificates by Faculties of IIM for selected programs, workshops, seminars, masterclasses, or events, as applicable.',
                        'And many more recognitions as per the program structure.',
                    ],
                ],
                [
                    'number' => 42,
                    'question' => 'Is there a certificate after every year?',
                    'answers' => [
                        'Yes.',
                        'Students who successfully complete each academic year receive a Year Completion Certificate.',
                        'The certificate recognizes learning, participation, projects, assignments, and overall performance.',
                        'Awarded as per the BNS certification policy.',
                    ],
                ],
                [
                    'number' => 43,
                    'question' => 'What is the Final Graduation Certificate?',
                    'answers' => [
                        'Awarded upon successful completion of the 5-Year BNS Program.',
                        'Recognizes completion of 500 Interactive Sessions.',
                        'Recognizes completion of 1000 Learning Hours.',
                        'Recognizes the Entrepreneurial & Business Education Journey.',
                        'Recognizes Practical Learning Experience.',
                        'Recognizes Leadership Development.',
                        'Recognizes Business Projects & Activities.',
                        'Represents successful graduation from Business Navachar School.',
                    ],
                ],
                [
                    'number' => 44,
                    'question' => 'Are Skill Certificates provided?',
                    'answers' => [
                        'Yes.',
                        'Entrepreneurship Skills.',
                        'Leadership Skills.',
                        'Financial Literacy.',
                        'Communication Skills.',
                        'Public Speaking.',
                        'AI & Digital Skills.',
                        'Marketing & Sales.',
                        'Business Planning.',
                        'Innovation & Creativity.',
                        'Personality Development.',
                        'Teamwork & Collaboration.',
                        'And many more skill-based certifications, wherever applicable.',
                    ],
                ],
                [
                    'number' => 45,
                    'question' => 'Are Project Certificates awarded?',
                    'answers' => [
                        'Yes.',
                        'Startup Projects.',
                        'Business Plan Projects.',
                        'Innovation Projects.',
                        'Product Development Projects.',
                        'Market Research Projects.',
                        'Leadership Projects.',
                        'Social Entrepreneurship Projects.',
                        'AI & Digital Business Projects.',
                        'Business Competition Projects.',
                        'Community Impact Projects.',
                        'And many more project recognitions.',
                    ],
                ],
                [
                    'number' => 46,
                    'question' => 'Will students build a Business Portfolio?',
                    'answers' => [
                        'Yes.',
                        'Every student is encouraged to build a professional Business Portfolio throughout the program.',
                        'Business Ideas Portfolio.',
                        'Startup Portfolio.',
                        'Innovation Portfolio.',
                        'Business Plan Portfolio.',
                        'Presentation Portfolio.',
                        'Project Portfolio.',
                        'Leadership Portfolio.',
                        'Achievement Portfolio.',
                        'Certificate Portfolio.',
                        'And many more records showcasing the student\'s learning journey.',
                    ],
                ],
                [
                    'number' => 47,
                    'question' => 'What career opportunities can BNS create?',
                    'answers' => [
                        'Entrepreneur.',
                        'Startup Founder.',
                        'Family Business Leader.',
                        'Business Professional.',
                        'Corporate Leader.',
                        'CEO.',
                        'Business Consultant.',
                        'Investor.',
                        'Innovator.',
                        'Wealth Creator.',
                        'Social Entrepreneur.',
                        'Nation Builder.',
                        'And many more future career pathways.',
                    ],
                ],
                [
                    'number' => 48,
                    'question' => 'How does BNS prepare students for the future?',
                    'answers' => [
                        'Entrepreneurial Mindset.',
                        'Leadership Development.',
                        'Financial Literacy.',
                        'Business Knowledge.',
                        'AI & Digital Readiness.',
                        'Innovation & Creativity.',
                        'Critical Thinking.',
                        'Problem Solving.',
                        'Decision Making.',
                        'Communication Skills.',
                        'Teamwork & Collaboration.',
                        'Practical Learning Experience.',
                        'Future-Ready Competencies.',
                        'And many more lifelong skills.',
                    ],
                ],
                [
                    'number' => 49,
                    'question' => 'Why should parents choose BNS?',
                    'answers' => [
                        'Future-Ready Education.',
                        'Entrepreneurial Mindset.',
                        'Leadership Development.',
                        'Financial Literacy.',
                        'Personality Development.',
                        'Practical Learning.',
                        'Real Business Exposure.',
                        'Confidence Building.',
                        'Ethical Values.',
                        'Career Readiness.',
                        'Industry Interaction.',
                        'Holistic Development.',
                        'And many more long-term benefits.',
                    ],
                ],
                [
                    'number' => 50,
                    'question' => 'How can I get more information or contact the BNS team?',
                    'answers' => [
                        'Visit the Official Website.',
                        'Download the Brochure.',
                        'Contact the Admission Team.',
                        'Book a Counselling Session.',
                        'Attend an Orientation Program.',
                        'Visit the Campus.',
                        'Connect via Phone, Email or WhatsApp.',
                        'Follow Official Social Media Platforms.',
                        'Stay updated with Events & Workshops.',
                        'And many more support services.',
                    ],
                ],
            ],
            'footer' => [
                'certification_notice' => [
                    'heading' => 'Certification Recognition',
                    'text' => 'Students may receive <strong>Participation / Appreciation Certificates by Faculties of IIM</strong> for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
                ],
                'taglines' => [
                    'Every Session Builds Knowledge.',
                    'Every Project Builds Experience.',
                    'Every Certificate Builds Confidence.',
                    'Dream Big. Build Bigger.',
                    'Don\'t Chase Jobs. Create Jobs.',
                    'Learn Today. Build Tomorrow. Lead Forever.',
                ],
            ],
        ],
    ],
    'program_snapshot' => [
        'after_part_index' => 1,
        'heading' => 'Program Snapshot',
        'rows' => [
            ['label' => 'Duration', 'value' => '5 Years'],
            ['label' => 'Weekly', 'value' => '2 Sessions | 4 Hours'],
            ['label' => 'Monthly', 'value' => '8 Sessions | 16 Hours'],
            ['label' => 'Yearly', 'value' => '100 Sessions | 200 Hours'],
            ['label' => 'Total Program', 'value' => '500 Sessions | 1000 Learning Hours'],
        ],
    ],
    'belief_heading' => 'Our Belief',
    'taglines' => [
        'Dream Big. Build Bigger.',
        'Ideas Create the Future.',
        'Don\'t Chase Jobs. Create Jobs.',
        'Learn Today. Build Tomorrow. Lead Forever.',
    ],
];
