<?php

return [
    'title' => 'Eligibility Criteria',
    'subtitle' => 'Business Navachar School (BNS)',
    'tracks' => [
        [
            'school_name' => 'Job Excellence School',
            'subtitle' => 'For Job Professionals | One-Year Executive Business Program',
            'intro_heading' => 'Who Can Join?',
            'intro' => 'The Job Excellence School is designed for working professionals who aspire to enhance their leadership, management, business, AI, and future-ready skills to accelerate their careers and professional growth.',
            'programs' => [
                [
                    'icon' => '💼',
                    'title' => 'Working Professionals',
                    'candidates_label' => 'Eligible Participants',
                    'candidates' => [
                        'Private Sector Employees',
                        'Government Employees',
                        'Corporate Professionals',
                        'Managers',
                        'Team Leaders',
                        'Supervisors',
                        'Engineers',
                        'Doctors & Healthcare Professionals',
                        'Chartered Accountants',
                        'Company Secretaries',
                        'Lawyers',
                        'Bank Employees',
                        'Insurance Professionals',
                        'Sales Professionals',
                        'Marketing Professionals',
                        'HR Professionals',
                        'Finance Professionals',
                        'IT Professionals',
                        'Teachers & Educators',
                        'Consultants',
                        'Freelancers',
                        'Startup Employees',
                        'MSME Professionals',
                        'And many more.',
                    ],
                ],
            ],
            'general_eligibility' => [
                'title' => 'General Eligibility',
                'intro' => 'Applicants should have:',
                'items' => [
                    'Passion for Learning.',
                    'Professional Work Experience (Preferred).',
                    'Leadership Potential.',
                    'Positive Attitude.',
                    'Willingness to Learn.',
                    'Interest in Business & Management.',
                    'Commitment to Attend Sessions.',
                    'Readiness for Practical Learning.',
                    'Growth Mindset.',
                    'Ethical Professional Values.',
                ],
            ],
            'ideal_for' => [
                'title' => 'Ideal For Professionals Who Want To Become',
                'items' => [
                    'Team Leader',
                    'Department Head',
                    'Business Leader',
                    'Senior Manager',
                    'Corporate Executive',
                    'CEO',
                    'CXO',
                    'Entrepreneur',
                    'Startup Founder',
                    'Business Consultant',
                    'Corporate Trainer',
                    'Industry Leader',
                    'And many more leadership roles.',
                ],
            ],
            'program_structure' => [
                'title' => 'Program Structure',
                'items' => [
                    'Duration: 1 Year',
                    'Weekly: 2 Sessions | 4 Learning Hours',
                    'Monthly: 8 Sessions | 16 Learning Hours',
                    'Yearly: 100 Sessions | 200 Learning Hours',
                ],
            ],
            'journey_begin' => [
                'title' => 'Your Journey Begins Here',
                'tagline' => 'Professional → Leader → Business Thinker → Industry Expert',
            ],
            'taglines' => [
                'Learn. Lead. Excel. Grow.',
            ],
        ],
        [
            'school_name' => 'Business Empire School',
            'subtitle' => 'For Business Owners | One-Year Executive Business Growth Program',
            'intro_heading' => 'Who Can Join?',
            'intro' => 'The Business Empire School is designed for entrepreneurs and business owners who want to strengthen, scale, systemize, and grow their businesses through practical business education.',
            'programs' => [
                [
                    'icon' => '🏢',
                    'title' => 'Business Owners',
                    'candidates_label' => 'Eligible Participants',
                    'candidates' => [
                        'MSME Owners',
                        'Startup Founders',
                        'Family Business Owners',
                        'Manufacturers',
                        'Wholesalers',
                        'Retailers',
                        'Traders',
                        'Service Business Owners',
                        'Exporters',
                        'Importers',
                        'E-Commerce Business Owners',
                        'Franchise Owners',
                        'Restaurant & Café Owners',
                        'Hotel & Hospitality Business Owners',
                        'Healthcare Business Owners',
                        'Education Entrepreneurs',
                        'Construction & Real Estate Business Owners',
                        'Digital Business Owners',
                        'Consultants',
                        'Agency Owners',
                        'And many more.',
                    ],
                ],
                [
                    'icon' => '🚀',
                    'title' => 'Aspiring Business Leaders',
                    'candidates_label' => 'Eligible Participants',
                    'candidates' => [
                        'Entrepreneurs planning business expansion.',
                        'Second-generation family business members.',
                        'Startup founders preparing for growth.',
                        'Business partners.',
                        'Directors of companies.',
                        'Professionals transitioning into business.',
                        'And many more.',
                    ],
                ],
            ],
            'general_eligibility' => [
                'title' => 'General Eligibility',
                'intro' => 'Applicants should have:',
                'items' => [
                    'Passion for Business Growth.',
                    'Entrepreneurial Mindset.',
                    'Positive Attitude.',
                    'Willingness to Learn.',
                    'Commitment to Attend Sessions.',
                    'Interest in Innovation & Technology.',
                    'Leadership Potential.',
                    'Readiness for Practical Implementation.',
                    'Ethical Business Values.',
                    'Vision for Long-Term Growth.',
                ],
            ],
            'ideal_for' => [
                'title' => 'Ideal For Business Owners Who Want To Become',
                'items' => [
                    'Business Leader',
                    'Industry Leader',
                    'CEO',
                    'Managing Director',
                    'Growth Entrepreneur',
                    'Corporate Business Owner',
                    'Export Business Leader',
                    'Investor',
                    'Business Mentor',
                    'Employer',
                    'Wealth Creator',
                    'Nation Builder',
                    'And many more leadership roles.',
                ],
            ],
            'program_structure' => [
                'title' => 'Program Structure',
                'items' => [
                    'Duration: 1 Year',
                    'Weekly: 2 Sessions | 4 Learning Hours',
                    'Monthly: 8 Sessions | 16 Learning Hours',
                    'Yearly: 100 Sessions | 200 Learning Hours',
                ],
            ],
            'journey_begin' => [
                'title' => 'Your Journey Begins Here',
                'tagline' => 'Business → Growth → Scale → Business Excellence',
            ],
            'taglines' => [
                'Grow Stronger. Scale Smarter. Lead the Future.',
            ],
        ],
    ],
];
