<?php

return [
    'eyebrow' => 'Growth Batch',
    'title' => "India's Prosperity Mission",
    'subtitle' => 'Empowering People. Strengthening Businesses. Building a Prosperous India.',
    'intro' => [
        'India\'s prosperity depends on <strong>strong entrepreneurs, skilled professionals, empowered women, innovative youth, and sustainable businesses</strong>.',
        'At Business Navachar School (BNS), our mission is to empower <strong>Business Owners, Job Professionals, Women Entrepreneurs, and Youth</strong> with <strong>practical business education, entrepreneurial thinking, leadership, innovation, and future-ready skills</strong> that contribute to <strong>economic growth and the vision of Viksit Bharat 2047</strong>.',
    ],
    'points_heading' => 'Our Mission for a Prosperous India',
    'points' => [
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Empower entrepreneurs to build successful and sustainable businesses.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Help MSMEs, startups, and family businesses grow and scale.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Develop business leaders with global thinking and Indian values.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Strengthen leadership, management, and decision-making capabilities.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Promote innovation, creativity, and problem-solving.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Build financial literacy and wealth creation capabilities.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Prepare individuals for the AI-driven and digital economy.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Encourage ethical, responsible, and value-based business practices.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Support women entrepreneurship and financial independence.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Inspire youth to become startup founders, innovators, and job creators.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Generate employment through entrepreneurship and business expansion.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Create a nationwide ecosystem of entrepreneurs, professionals, mentors, investors, and business leaders.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Promote lifelong learning through practical business education.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Contribute to India\'s economic development through innovation, enterprise, and business excellence.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Build globally competitive businesses that proudly represent India.'],
    ],
    'commitment_heading' => 'Our Learning Commitment',
    'commitment_points' => [
        'Practical Business Education',
        'Industry-Oriented Learning',
        'Live Case Studies',
        'Business Projects',
        'Workshops & Masterclasses',
        'Business Coaching & Mentoring',
        'Syllabus and Learning Methodology developed with the guidance of Faculties of IIM, as per the applicable collaboration framework.',
        'Learning through BNS-trained faculties, business coaches, industry experts, with selected sessions by Faculties of IIM, where applicable.',
        'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
    ],
    'vision_heading' => 'Our Vision for India',
    'vision_lines' => [
        'When People Learn, Businesses Grow.',
        'When Businesses Grow, Employment Increases.',
        'When Employment Increases, Families Prosper.',
        'When Families Prosper, India Becomes Stronger.',
        'When India Becomes Stronger, We Move Closer to Viksit Bharat 2047.',
    ],
    'belief_heading' => 'Our Belief',
    'belief_star_lines' => [
        'Empower People.',
        'Transform Businesses.',
        'Create Employment.',
        'Drive Innovation.',
        'Build Prosperity.',
        'Strengthen India.',
    ],
    'taglines' => [
        'Prosperous Businesses. Prosperous India.',
        'Learn. Grow. Scale. Lead.',
        'Together Towards Viksit Bharat 2047.',
    ],
];
