<?php

return [
    'eyebrow' => 'Business Navachar School (BNS) – Youth Business School',
    'title' => "India's Prosperity Vision",
    'subtitle' => 'Empowering Young Minds. Building Startups. Creating a Prosperous India.',
    'intro' => [
        'India\'s greatest strength is its <strong>youth</strong>. The dreams, ideas, innovations, and leadership of today\'s college students will shape the economy of tomorrow.',
        'At Business Navachar School (BNS), we believe that a prosperous India will be built by <strong>young entrepreneurs, innovators, startup founders, business leaders, and professionals</strong> who create opportunities, generate employment, and solve real-world problems.',
        'Our vision is to empower every young learner with <strong>practical business education</strong> so they can transform <strong>Ideas into Startups, Startups into Successful Businesses, Businesses into Corporates, and Corporates into IPO-ready Enterprises</strong>.',
    ],
    'points_heading' => 'Our Vision for a Prosperous India',
    'points' => [
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Inspire youth to become entrepreneurs instead of only job seekers.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Transform innovative ideas into successful startups.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Build globally competitive businesses with Indian values.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Promote innovation, research, creativity, and problem-solving.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Develop future-ready leaders with entrepreneurial thinking.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Strengthen financial literacy and wealth creation capabilities.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Prepare youth for the AI-driven and digital economy.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Build startups that create employment and economic opportunities.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Encourage ethical leadership and responsible entrepreneurship.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Support MSMEs, startups, family businesses, and innovation-driven enterprises.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Develop business leaders capable of building companies from Idea to IPO.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Provide practical business education through a structured syllabus and learning methodology developed with the guidance of Faculties of IIM, as per the applicable collaboration framework.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Deliver learning through BNS-trained faculties, business coaches, industry experts, with selected sessions by Faculties of IIM, where applicable.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Recognize excellence through Program Completion Certificates, Skill Certificates, Project Certificates, and Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Build a nationwide ecosystem of young entrepreneurs, mentors, investors, innovators, and business leaders.'],
        ['icon' => 'fas fa-flag', 'title' => '🇮🇳 Contribute to the vision of Viksit Bharat 2047 through entrepreneurship, innovation, business excellence, and employment generation.'],
    ],
    'become_heading' => 'Our Dream for Every Youth',
    'become_points' => [
        'Build a Startup.',
        'Create Employment.',
        'Generate Wealth.',
        'Solve Real Problems.',
        'Lead with Integrity.',
        'Innovate Continuously.',
        'Scale Businesses Globally.',
        'Contribute to India\'s Growth.',
        'Build a Lasting Legacy.',
    ],
    'belief_heading' => 'Our Belief',
    'belief_lines' => [
        'When Youth Innovate, Startups Grow.',
        'When Startups Grow, Businesses Scale.',
        'When Businesses Scale, Employment Increases.',
        'When Employment Increases, India Prospers.',
        'When India Prospers, We Achieve Viksit Bharat 2047.',
    ],
    'taglines' => [
        'Dream Big. Build Bigger.',
        'Ideas Create Startups. Startups Create Prosperity.',
        'From Idea to IPO.',
        'Young Minds. Strong Nation. Prosperous India.',
        'Learn Today. Launch Tomorrow. Scale Forever.',
    ],
];
