<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Program Structure',
    'subtitle' => 'Youth Business School — 3-Year Business Education Program',
    'tagline' => 'From Idea to Startup • Startup to Scale-up • Scale-up to IPO',
    'stats' => [
        ['icon' => 'fas fa-calendar-alt', 'text' => 'Duration: 3 Years'],
        ['icon' => 'fas fa-chalkboard-teacher', 'text' => 'Sessions: 300 Sessions'],
        ['icon' => 'fas fa-clock', 'text' => 'Learning Hours: 600 Hours'],
    ],
    'hours_table' => [
        'heading' => 'Learning Schedule',
        'columns' => ['Period', 'Sessions', 'Learning Hours'],
        'rows' => [
            ['Weekly', '2 Sessions', '4 Hours'],
            ['Monthly', '8 Sessions', '16 Hours'],
            ['Yearly', '100 Sessions', '200 Hours'],
        ],
    ],
    'years_heading' => 'Year-wise Curriculum',
    'years' => [
        [
            'year' => 1,
            'name' => 'Youth Foundation School',
            'theme' => 'Build the Entrepreneur Within',
            'skills_title' => 'Learning Areas',
            'skills' => [
                'Entrepreneurial Mindset',
                'Startup Mindset',
                'Business Opportunity Identification',
                'Design Thinking',
                'Creativity & Innovation',
                'Problem Solving',
                'Critical Thinking',
                'Business Communication',
                'Public Speaking',
                'Personality Development',
                'Leadership Development',
                'Goal Setting',
                'Time Management',
                'Business Ethics',
                'Financial Literacy',
                'Business Mathematics',
                'Digital Literacy',
                'Business Planning',
                'Business Model Canvas',
                'Customer Psychology',
                'Marketing Fundamentals',
                'Sales Fundamentals',
                'Branding Basics',
                'Personal Branding',
                'Networking Skills',
                'Negotiation Skills',
                'Team Building',
                'Artificial Intelligence (AI)',
                'Digital Tools',
                'Business Case Studies',
                'Live Projects',
                'Workshops',
                'Industrial Visits',
                'Startup Visits',
                'Business Competitions',
                'Innovation Challenges',
                'Presentation Skills',
                'Business Research',
                'And many more practical business and life skills.',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
        [
            'year' => 2,
            'name' => 'Youth Startup School',
            'theme' => 'Transform Ideas into Successful Startups',
            'skills_title' => 'Learning Areas',
            'skills' => [
                'Startup Development',
                'Product Development',
                'Service Innovation',
                'Market Research',
                'Customer Validation',
                'Business Validation',
                'Lean Startup Methodology',
                'Branding Strategy',
                'Marketing Strategy',
                'Sales Mastery',
                'Digital Marketing',
                'Social Media Marketing',
                'SEO',
                'Content Marketing',
                'Performance Marketing',
                'Google Business Profile',
                'E-Commerce',
                'Website Development Basics',
                'AI for Business',
                'Prompt Engineering',
                'Business Automation',
                'Accounting',
                'Finance',
                'Budgeting',
                'Cash Flow',
                'Taxation Basics',
                'Human Resource Management',
                'Recruitment',
                'Team Training',
                'Team Leadership',
                'Operations Management',
                'SOP Development',
                'CRM',
                'Legal Basics',
                'Intellectual Property',
                'Startup Funding',
                'Angel Investors',
                'Venture Capital',
                'Pitch Deck Preparation',
                'Business Pitching',
                'Mentoring',
                'Business Networking',
                'Startup Projects',
                'Masterclasses',
                'Business Simulations',
                'Case Studies',
                'And many more startup-building concepts.',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
        [
            'year' => 3,
            'name' => 'Youth Business Growth School (Scale-Up School)',
            'theme' => 'Scale Business • Build Corporate • Prepare for IPO',
            'skills_title' => 'Learning Areas',
            'skills' => [
                'Business Growth Strategy',
                'Business Scaling',
                'Multi-Branch Expansion',
                'Franchise Business',
                'Licensing',
                'Distribution Network',
                'Export Business',
                'International Business',
                'Corporate Management',
                'Corporate Governance',
                'Board Management',
                'Strategic Leadership',
                'Business Analytics',
                'Data-Driven Decision Making',
                'AI for Business Growth',
                'Advanced Digital Marketing',
                'Business Finance',
                'Business Valuation',
                'Wealth Creation',
                'Investor Relations',
                'Fund Raising',
                'Private Equity',
                'Corporate Structuring',
                'Holding Company Concept',
                'Family Business Management',
                'Mergers & Acquisitions',
                'Strategic Partnerships',
                'Risk Management',
                'ESG & Sustainability',
                'Company Law Basics',
                'SME IPO',
                'Main Board IPO',
                'IPO Readiness',
                'Business Excellence',
                'Legacy Building',
                'Global Business Strategy',
                'Business Transformation',
                'Leadership Excellence',
                'Business Consulting',
                'Innovation Management',
                'Capstone Business Project',
                'Business Portfolio Development',
                'Industry Mentoring',
                'And many more advanced business, corporate, and IPO-related concepts.',
            ],
            'hours' => '200 Hours',
            'sessions' => '100',
        ],
    ],
    'practical_model' => [
        'heading' => 'Learning Methodology',
        'includes_heading' => 'Students learn through:',
        'items' => [
            'Structured Curriculum',
            'Practical Learning',
            'Live Business Projects',
            'Startup Challenges',
            'Business Simulations',
            'Case Studies',
            'Workshops',
            'Masterclasses',
            'Industry Visits',
            'Business Visits',
            'Business Coaching',
            'Mentoring',
            'Group Discussions',
            'Presentations',
            'AI-Based Learning',
            'Networking Events',
            'Hackathons',
            'Innovation Labs',
            'Business Plan Competitions',
            'Entrepreneurship Camps',
            'Industry Interaction',
            'And many more experiential learning opportunities.',
        ],
    ],
    'certification' => [
        'heading' => 'Certification',
        'includes_heading' => 'Participants may receive:',
        'items' => [
            'Year-wise Completion Certificates',
            'Program Completion Certificate',
            'Skill Certificates',
            'Project Certificates',
            'Achievement Certificates',
            'Leadership Certificates',
            'Startup Excellence Certificates',
            'Business Excellence Certificates',
            'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
            'And many more recognitions based on participation, performance, and achievement.',
        ],
    ],
    'outcome' => [
        'heading' => 'Outcome After 3 Years',
        'includes_heading' => 'Participants will be able to:',
        'items' => [
            'Build Innovative Startups',
            'Grow Sustainable Businesses',
            'Lead High-Performance Teams',
            'Develop Strong Business Systems',
            'Master Marketing & Sales',
            'Apply AI in Business',
            'Raise Business Funding',
            'Scale Businesses Nationally & Globally',
            'Understand Corporate Management',
            'Prepare for the IPO Journey',
            'Create Employment',
            'Build Wealth with Values',
            'Become Entrepreneurs, Business Leaders, and Nation Builders',
            'And many more future-ready capabilities.',
        ],
    ],
    'taglines' => [
        'From Idea to Startup.',
        'From Startup to Scale-up.',
        'From Scale-up to IPO.',
        'Learn Today. Launch Tomorrow. Scale Forever.',
    ],
];
