<?php

return [
    'eyebrow' => 'Business Navachar School (BNS)',
    'title' => 'Program Structure',
    'subtitle' => 'Women Business School — 2-Year Business Education Program',
    'tagline' => 'From Dream to Startup • Startup to Business Growth',
    'stats' => [
        ['icon' => 'fas fa-calendar-alt', 'text' => 'Duration: 2 Years'],
        ['icon' => 'fas fa-chalkboard-teacher', 'text' => 'Sessions: 200 Sessions'],
        ['icon' => 'fas fa-clock', 'text' => 'Learning Hours: 400 Hours'],
    ],
    'hours_table' => [
        'heading' => 'Learning Schedule',
        'columns' => ['Period', 'Sessions', 'Learning Hours'],
        'rows' => [
            ['Weekly', '2 Sessions', '4 Learning Hours'],
            ['Monthly', '8 Sessions', '16 Learning Hours'],
            ['Yearly', '100 Sessions', '200 Learning Hours'],
        ],
    ],
    'years_heading' => 'Year-wise Curriculum',
    'years' => [
        [
            'year' => 1,
            'name' => 'Women Startup School',
            'theme' => 'Transform Your Dream into a Successful Startup',
            'modules' => [
                [
                    'heading' => 'Module 1 – Entrepreneurial Mindset',
                    'topics' => [
                        'Entrepreneurial Mindset',
                        'Business Mindset',
                        'Self Confidence',
                        'Leadership Development',
                        'Goal Setting',
                        'Time Management',
                        'Success Habits',
                        'Positive Thinking',
                        'Decision Making',
                        'Problem Solving',
                        'Creative Thinking',
                        'Design Thinking',
                        'Business Ethics',
                        'Communication Skills',
                        'Public Speaking',
                        'Personal Branding',
                        'Networking Skills',
                        'Negotiation Skills',
                        'Emotional Intelligence',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 2 – Business Foundation',
                    'topics' => [
                        'Business Idea Generation',
                        'Opportunity Identification',
                        'Market Research',
                        'Customer Psychology',
                        'Business Model Canvas',
                        'Product Development',
                        'Service Innovation',
                        'Value Proposition',
                        'Business Planning',
                        'Startup Planning',
                        'Business Registration',
                        'Legal Basics',
                        'Intellectual Property',
                        'Risk Management',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 3 – Marketing & Branding',
                    'topics' => [
                        'Marketing Fundamentals',
                        'Sales Fundamentals',
                        'Branding',
                        'Brand Positioning',
                        'Personal Branding',
                        'Business Branding',
                        'Customer Acquisition',
                        'Customer Retention',
                        'CRM',
                        'Business Promotion',
                        'Advertising',
                        'Public Relations',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 4 – Digital Business',
                    'topics' => [
                        'Digital Marketing',
                        'Social Media Marketing',
                        'Instagram Business',
                        'Facebook Marketing',
                        'LinkedIn Marketing',
                        'WhatsApp Business',
                        'Google Business Profile',
                        'Website Basics',
                        'E-Commerce',
                        'Online Selling',
                        'Content Marketing',
                        'SEO Basics',
                        'AI for Business',
                        'Prompt Engineering',
                        'Business Automation',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 5 – Financial Foundation',
                    'topics' => [
                        'Financial Literacy',
                        'Accounting Basics',
                        'Budgeting',
                        'Costing',
                        'Pricing',
                        'Cash Flow',
                        'Banking',
                        'UPI & Digital Payments',
                        'GST Awareness',
                        'Tax Basics',
                        'Profit Planning',
                        'Wealth Creation',
                        'Investment Basics',
                        'And many more.',
                    ],
                ],
            ],
            'practical_learning' => [
                'heading' => 'Practical Learning',
                'items' => [
                    'Live Business Projects',
                    'Startup Challenges',
                    'Business Case Studies',
                    'Business Visits',
                    'Workshops',
                    'Masterclasses',
                    'Business Simulations',
                    'Mentoring',
                    'Presentations',
                    'Business Pitch',
                    'And many more.',
                ],
            ],
        ],
        [
            'year' => 2,
            'name' => 'Women Business Growth School',
            'theme' => 'Build, Manage & Scale Your Business',
            'modules' => [
                [
                    'heading' => 'Module 1 – Business Growth',
                    'topics' => [
                        'Business Growth Strategy',
                        'Business Expansion',
                        'Scaling Business',
                        'Franchise Model',
                        'Distribution Network',
                        'Partnership Models',
                        'Business Diversification',
                        'Market Expansion',
                        'Export Basics',
                        'International Business',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 2 – Business Management',
                    'topics' => [
                        'Operations Management',
                        'SOP Development',
                        'Business Systems',
                        'HR Management',
                        'Recruitment',
                        'Team Building',
                        'Team Training',
                        'Performance Management',
                        'Customer Service',
                        'Quality Management',
                        'Productivity Improvement',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 3 – Advanced Marketing',
                    'topics' => [
                        'Advanced Sales',
                        'Advanced Branding',
                        'Business Growth Marketing',
                        'Performance Marketing',
                        'Google Ads',
                        'Meta Ads',
                        'Influencer Marketing',
                        'Video Marketing',
                        'YouTube Marketing',
                        'AI Marketing',
                        'Marketing Analytics',
                        'Customer Experience',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 4 – Finance & Business Excellence',
                    'topics' => [
                        'Advanced Accounting',
                        'Financial Planning',
                        'Business Finance',
                        'Working Capital',
                        'Fund Raising',
                        'Business Valuation',
                        'Investor Readiness',
                        'Angel Investors',
                        'Venture Capital Awareness',
                        'Business Growth Finance',
                        'Wealth Management',
                        'And many more.',
                    ],
                ],
                [
                    'heading' => 'Module 5 – Leadership & Future Business',
                    'topics' => [
                        'Advanced Leadership',
                        'Strategic Thinking',
                        'AI in Business',
                        'Business Analytics',
                        'Data-Driven Decision Making',
                        'Innovation Management',
                        'Change Management',
                        'Corporate Readiness',
                        'Sustainability',
                        'Women Leadership',
                        'Family Business Management',
                        'Business Consulting',
                        'Capstone Business Project',
                        'Legacy Building',
                        'And many more.',
                    ],
                ],
            ],
        ],
    ],
    'practical_model' => [
        'heading' => 'Learning Methodology',
        'includes_heading' => 'Participants will learn through:',
        'items' => [
            'Practical Business Learning',
            'Live Business Projects',
            'Case Studies',
            'Workshops',
            'Masterclasses',
            'Business Coaching',
            'Mentoring',
            'Group Discussions',
            'Business Simulations',
            'Industrial Visits',
            'Startup Visits',
            'Networking Events',
            'AI-Based Learning',
            'Business Plan Competitions',
            'Product Demonstrations',
            'Market Surveys',
            'Pitch Presentations',
            'Role Plays',
            'Panel Discussions',
            'Guest Expert Sessions',
            'Assignments',
            'Assessments',
            'And many more experiential learning activities.',
        ],
    ],
    'certification' => [
        'heading' => 'Professional Certifications',
        'includes_heading' => 'Participants may receive:',
        'items' => [
            'Year 1 – Women Startup School Completion Certificate',
            'Year 2 – Women Business Growth School Completion Certificate',
            'BNS Women Business School Graduation Certificate',
            'Skill Development Certificates',
            'Project Completion Certificates',
            'Leadership Certificates',
            'Business Excellence Certificates',
            'Digital Marketing Certificates',
            'AI Skill Certificates',
            'Startup Project Certificates',
            'Business Growth Project Certificates',
            'Participation/Appreciation Certificates by Faculties of IIM for eligible workshops, seminars, masterclasses, training programs, or events conducted under the applicable collaboration framework.',
            'And many more recognitions based on learning, projects, participation, and performance.',
        ],
    ],
    'outcome' => [
        'heading' => 'Program Outcomes',
        'includes_heading' => 'After completing the 2-Year Women Business School, participants will be able to:',
        'items' => [
            'Start a New Business',
            'Grow an Existing Business',
            'Build a Strong Brand',
            'Master Sales & Marketing',
            'Use AI for Business Growth',
            'Manage Finance & Accounts',
            'Build High-Performance Teams',
            'Scale Business Operations',
            'Increase Profitability',
            'Become Financially Independent',
            'Create Employment Opportunities',
            'Lead with Confidence',
            'Build Sustainable Businesses',
            'Become Women Business Leaders',
            'Contribute towards Viksit Bharat 2047',
            'And many more future-ready entrepreneurial capabilities.',
        ],
    ],
    'taglines' => [
        'Dream → Idea → Startup → Business Growth',
        'Empowered Women. Prosperous Families. Strong India.',
        'Learn. Launch. Grow. Lead.',
    ],
];
