<?php

return [
    'subtitle' => 'Business Navachar School (BNS)',
    'programs' => [
        [
            'number' => 1,
            'icon' => '🏢',
            'title' => 'Business Owners',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Existing Business Owners',
                'MSME Owners',
                'Startup Founders',
                'Small Business Owners',
                'Retail Business Owners',
                'Manufacturing Business Owners',
                'Service Business Owners',
                'Traders & Distributors',
                'Family Business Successors',
                'Franchise Owners',
                'Home-Based Business Owners',
                'Professionals Running Their Own Business',
                'Aspiring Entrepreneurs',
                'And other eligible business professionals.',
            ],
        ],
        [
            'number' => 2,
            'icon' => '💼',
            'title' => 'Job Professionals',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Private Sector Employees',
                'Government Employees',
                'Corporate Professionals',
                'Team Leaders',
                'Managers',
                'Senior Executives',
                'Working Professionals',
                'Freelancers',
                'Consultants',
                'Engineers',
                'Doctors',
                'Chartered Accountants',
                'Company Secretaries',
                'Lawyers',
                'Architects',
                'IT Professionals',
                'Sales & Marketing Professionals',
                'Banking & Finance Professionals',
                'HR Professionals',
                'And other working professionals.',
            ],
        ],
        [
            'number' => 3,
            'icon' => '👩',
            'title' => 'Women Entrepreneurs',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'Existing Women Business Owners',
                'Homepreneurs',
                'Housewives Planning to Start a Business',
                'Women Startup Founders',
                'Working Women',
                'Freelancers',
                'Self-Employed Women',
                'Women Professionals',
                'Family Business Successors',
                'Women Running Online Businesses',
                'Boutique Owners',
                'Food Business Owners',
                'Beauty & Wellness Entrepreneurs',
                'Creative Entrepreneurs',
                'Social Entrepreneurs',
                'And other aspiring women entrepreneurs.',
            ],
        ],
        [
            'number' => 4,
            'icon' => '🚀',
            'title' => 'Youth Startup',
            'candidates_label' => 'Eligible Participants',
            'candidates' => [
                'College Students',
                'Recent Graduates',
                'Aspiring Entrepreneurs',
                'Startup Founders',
                'Innovation Enthusiasts',
                'Young Professionals',
                'Family Business Successors',
                'Youth Interested in Entrepreneurship',
                'Students Planning to Launch a Startup',
                'Freelancers',
                'Creators',
                'Digital Entrepreneurs',
                'And other aspiring startup founders.',
            ],
        ],
    ],
    'general_eligibility' => [
        'title' => 'General Eligibility',
        'items' => [
            'Passion to Learn and Grow.',
            'Entrepreneurial Mindset.',
            'Positive Attitude.',
            'Commitment to Attend Sessions.',
            'Willingness to Apply Learning.',
            'Interest in Business, Innovation & Leadership.',
            'Readiness for Practical Learning.',
            'Openness to Networking and Collaboration.',
            'Commitment to Ethical Business Practices.',
            'Growth Mindset and Continuous Learning.',
        ],
    ],
    'no_prior_experience' => [
        'title' => 'No Prior Business Experience Required',
        'text' => 'Whether you are starting your first business, growing an existing business, building your career, or launching a startup, Business Navachar School (BNS) welcomes learners who are committed to learning, innovation, and growth.',
    ],
    'taglines' => [
        'Learn. Grow. Scale. Lead.',
        'Empowering Entrepreneurs. Transforming Businesses. Building India.',
    ],
];
