<?php

/**
 * Important phrases auto-emphasized site-wide when not already wrapped in <strong>.
 * Longest phrases are applied first to avoid partial overlaps.
 */
return [
    'phrases' => [
        'Participation & Appreciation Certificates by Faculties of IIM',
        'Participation/Appreciation Certificates by Faculties of IIM',
        'Participation & Appreciation Certificates',
        'Participation/Appreciation Certificate',
        'Entrepreneurship Development Institute of India',
        'Business Navachar School',
        'Business Navachar Schools',
        'Nation Building',
        'nation-building',
        'Business Coach',
        'Business Coaches',
        'Introduction Session',
        'Confirm Admission',
        'Viksit Bharat 2047',
        'Business Learning Ecosystem',
        'wealth creation',
        'financial independence',
        'entrepreneurial ecosystem',
        'globally competitive entrepreneurs',
        'Business Navachar School (BNS)',
        'India\'s Practical Weekly Business School',
        'Practical Weekly Business School',
        'India\'s Weekly Business School',
        'Business Owners & Business Professionals',
        'Business Owners',
        'Job Professionals',
        'Business Education',
        'practical business education',
        'real-world business success',
        'Developed India',
        'entrepreneurial thinking',
        'College Youth',
        'School Students',
        'Knowledge • Innovation • Prosperity',
        'Idea → Startup → Growth → Scale-up → Corporate → IPO',
        'Idea → Startup → Business → Growth → Scale → Corporate → Funding → IPO',
        'Double Your Income, Double Your Balance Sheet',
        'Level Next Digital Business School',
        'Women Entrepreneurship School',
        'Junior Business School',
        'Youth Business School',
        'Job Excellence School',
        'Business Empire School',
        'Faculties of IIM',
        'Faculties of EDII',
        'Faculties of IITs',
        'entrepreneurial mindset',
        'financial literacy',
        'future-ready education',
        'traditional education',
        'world-class entrepreneurship education',
        'Balance Sheet Double',
        'Income Double',
        'Paper Pe Vyapar',
        'Job Creator',
        'Job Seeker',
        'job creators',
        'job seekers',
        'Startup Founders',
        'Business Leaders',
        'Women Entrepreneurs',
        'Wealth Creators',
        'Artificial Intelligence (AI)',
        'Artificial Intelligence',
        'Practical Learning',
        'Weekly Business School',
        'Business ABCD to IPO Journey',
        'BNS Trained Business Coaches',
        'Unicorn Entrepreneurs',
        'Viksit Bharat',
    ],
];
