<?php

return [
    'title' => 'Four Types of Business Schools',
    'intro' => 'Compare Contribution, Gold, Platinum, and Diamond membership benefits.',
    'headers' => [
        'Features',
        '🤝 Contribution Business School',
        '🥇 Gold Business School',
        '👑 Platinum Business School',
        '💎 Diamond Business School',
    ],
    'rows' => [
        ['Yearly Fees', '₹8,000 / ₹10,000 + GST', '₹17,000 + GST', '₹30,000 + GST', '₹60,000 + GST'],
        ['Venue', 'Sponsor & Venue Partner Supported', 'School / College Auditorium', 'Premium Educational Auditorium', 'Luxury Hotels / Premium Auditoriums'],
        ['Learning Hours', 'Up to 100 Sessions / 200 Hours', 'Up to 100 Sessions / 200 Hours', 'Up to 100 Sessions / 200+ Hours', 'Up to 100 Sessions / 200+ Hours'],
        ['Learning Environment', 'Standard Classroom', 'Better Learning Environment', 'Premium Learning Environment', 'Executive Learning Experience'],
        ['Batch Type', 'Standard Batch', 'Golden Batch', 'Premium Batch', 'Executive Batch (Highly Limited Seats)'],
        ['Business Coaches', 'BNS Trained Business Coaches', 'Senior Business Coaches', 'Advanced Business Mentors', 'Personal Business Mentors'],
        ['Academic Guidance', 'Faculties of IIM', 'Faculties of IIM', 'Faculties of IIM', 'Faculties of IIM'],
        ['Practical Learning', '✅', '✅', '✅', '✅'],
        ['Worksheets & Assignments', 'Standard', 'Advanced', 'Premium', 'Executive'],
        ['Business Case Studies', 'Standard', 'Advanced', 'Live Business Case Studies', 'Premium Business Case Studies'],
        ['Business Simulation Activities', '—', '—', '✅', '✅'],
        ['Industry Visits', '—', '—', 'Included', 'Premium Industry Visits'],
        ['Guest Speaker Sessions', '—', 'Monthly', 'Premium', 'CEO & Founder Sessions'],
        ['Business Growth Workshops', '—', 'Included', 'Advanced', 'Executive Level'],
        ['Networking', 'Standard', 'Better', 'Premium', 'VIP Business Networking'],
        ['Community Membership', 'Standard', 'Gold', 'Platinum', 'Diamond Leadership Circle'],
        ['AI Business Tools', 'Basic', 'Basic', 'Advanced', 'Premium'],
        ['Business Mentoring', 'Group', 'Group', 'Advanced', 'Personal 1-to-1'],
        ['Business Review', '—', '—', 'Monthly', 'Monthly 1-to-1 Review'],
        ['Business Profile Listing', '—', 'Included', 'Featured on Website', 'Premium Featured Listing'],
        ['Business Promotion', '—', '—', 'Included', 'Premium Branding & Promotion'],
        ['Learning Kit', 'Digital Study Material', 'Advanced Resources', 'Premium Learning Kit', 'Executive Learning Kit'],
        ['Leadership Workshops', '—', '—', 'Included', 'Executive Leadership Programs'],
        ['Investor Connect', '—', '—', '—', 'Included'],
        ['Startup Pitch Opportunities', '—', '—', '—', 'Included'],
        ['Media & Social Media Recognition', '—', '—', 'Limited', 'Premium Recognition'],
        ['Certificate', 'Participation & Appreciation Certificate', 'Gold Certificate', 'Platinum Certificate', 'Diamond Certificate'],
    ],
];
