<?php

return [

    'page' => [
        'title' => 'Upcoming Events',
        'subtitle' => 'Business Navachar School – Events & Inauguration',
        'label' => 'Events',
        'intro' => 'Join our Introduction Sessions and Grand Inauguration Ceremony in Santacruz, Mumbai. Limited seats available — register now to learn, network, and grow with expert guidance.',
        'spotlight_title' => 'Upcoming Events',
        'spotlight_intro' => 'Choose your preferred date. A focused learning experience for youth, women, job professionals, and business owners.',
    ],

    'events' => [
        [
            'type' => 'introduction',
            'spotlight' => true,
            'session_number' => 1,
            'title' => 'Introduction Session 1',
            'date' => '12 July 2026 (Sunday)',
            'time' => '7:00 PM – 8:30 PM',
            'starts_at' => '2026-07-12 19:00:00',
            'ends_at' => '2026-07-12 20:30:00',
            'timezone' => 'Asia/Kolkata',
            'venue' => 'Santacruz, Mumbai',
            'location_full' => 'Shree Vardhaman Sthanakwasi Jain Shravak Sangh Santacruz West, Smt K D Mehta Dharmasthanak, M D Mehta Chowk, P M Road, Near Hi Life Mall, Santacruz West, Mumbai 400054',
            'maps_url' => 'https://maps.app.goo.gl/Ve33LZjacUg2eB9H7',
            'category' => 'Introduction Session',
            'audience' => 'Youth • Women • Job Professionals • Business Owners',
            'guest_faculty' => 'BNS Team',
            'benefits' => [
                'Practical Business Learning',
                'Career & Business Guidance',
                'Networking Opportunity',
                'Participation Certificate',
                'Business Growth Roadmap',
                'Startup & Innovation Guidance',
                'Financial Growth Strategies',
                'One-to-One Expert Interaction',
            ],
            'seats' => 'Limited Seats Available',
            'cta' => ['label' => 'Register Now', 'route' => 'register'],
        ],
        [
            'type' => 'introduction',
            'spotlight' => true,
            'session_number' => 2,
            'title' => 'Introduction Session 2',
            'date' => '08 August 2026 (Saturday)',
            'time' => '7:15 PM – 8:30 PM',
            'starts_at' => '2026-08-08 19:15:00',
            'ends_at' => '2026-08-08 20:30:00',
            'timezone' => 'Asia/Kolkata',
            'venue' => 'Santacruz, Mumbai',
            'location_full' => 'Shree Vardhaman Sthanakwasi Jain Shravak Sangh Santacruz West, Smt K D Mehta Dharmasthanak, M D Mehta Chowk, P M Road, Near Hi Life Mall, Santacruz West, Mumbai 400054',
            'maps_url' => 'https://maps.app.goo.gl/Ve33LZjacUg2eB9H7',
            'category' => 'Introduction Session',
            'audience' => 'Youth • Women • Job Professionals • Business Owners',
            'guest_faculty' => 'BNS Team',
            'benefits' => [
                'Practical Business Learning',
                'Career & Business Guidance',
                'Networking Opportunity',
                'Participation Certificate',
                'Business Growth Roadmap',
                'Startup & Innovation Guidance',
                'Financial Growth Strategies',
                'One-to-One Expert Interaction',
            ],
            'seats' => 'Limited Seats Available',
            'cta' => ['label' => 'Register Now', 'route' => 'register'],
        ],
        [
            'type' => 'introduction',
            'spotlight' => true,
            'session_number' => 3,
            'title' => 'Introduction Session 3',
            'date' => '09 August 2026 (Sunday)',
            'time' => '2:30 PM – 4:30 PM',
            'starts_at' => '2026-08-09 14:30:00',
            'ends_at' => '2026-08-09 16:30:00',
            'timezone' => 'Asia/Kolkata',
            'venue' => 'Santacruz, Mumbai',
            'location_full' => 'Shree Vardhaman Sthanakwasi Jain Shravak Sangh Santacruz West, Smt K D Mehta Dharmasthanak, M D Mehta Chowk, P M Road, Near Hi Life Mall, Santacruz West, Mumbai 400054',
            'maps_url' => 'https://maps.app.goo.gl/Ve33LZjacUg2eB9H7',
            'category' => 'Introduction Session',
            'audience' => 'Youth • Women • Job Professionals • Business Owners',
            'guest_faculty' => 'BNS Team',
            'benefits' => [
                'Practical Business Learning',
                'Career & Business Guidance',
                'Networking Opportunity',
                'Participation Certificate',
                'Business Growth Roadmap',
                'Startup & Innovation Guidance',
                'Financial Growth Strategies',
                'One-to-One Expert Interaction',
            ],
            'seats' => 'Limited Seats Available',
            'cta' => ['label' => 'Register Now', 'route' => 'register'],
        ],
        [
            'type' => 'introduction',
            'spotlight' => true,
            'session_number' => 4,
            'title' => 'Introduction Session 4',
            'date' => '22 August 2026 (Saturday)',
            'time' => '7:00 PM – 8:30 PM',
            'starts_at' => '2026-08-22 19:00:00',
            'ends_at' => '2026-08-22 20:30:00',
            'timezone' => 'Asia/Kolkata',
            'venue' => 'Santacruz, Mumbai',
            'location_full' => 'Shree Vardhaman Sthanakwasi Jain Shravak Sangh Santacruz West, Smt K D Mehta Dharmasthanak, M D Mehta Chowk, P M Road, Near Hi Life Mall, Santacruz West, Mumbai 400054',
            'maps_url' => 'https://maps.app.goo.gl/Ve33LZjacUg2eB9H7',
            'category' => 'Introduction Session',
            'audience' => 'Youth • Women • Job Professionals • Business Owners',
            'guest_faculty' => 'BNS Team',
            'benefits' => [
                'Practical Business Learning',
                'Career & Business Guidance',
                'Networking Opportunity',
                'Participation Certificate',
                'Business Growth Roadmap',
                'Startup & Innovation Guidance',
                'Financial Growth Strategies',
                'One-to-One Expert Interaction',
            ],
            'seats' => 'Limited Seats Available',
            'cta' => ['label' => 'Register Now', 'route' => 'register'],
        ],
        [
            'type' => 'inauguration',
            'spotlight' => true,
            'title' => 'Business Navachar School – Santacruz Jain Upashrya',
            'tagline' => 'Grand Inauguration Ceremony',
            'date' => '16 August 2026 (Sunday)',
            'time' => '9:30 AM – 11:30 AM',
            'venue' => 'Santacruz, Mumbai',
            'category' => 'First Business Navachar School Launch & Inauguration',
            'audience' => 'Youth • Women • Job Professionals • Business Owners',
            'guest_faculty' => 'Faculties of IIM Trained Business Coaches',
            'highlights' => [
                'Grand Inauguration of the First Business Navachar School',
                'Beginning of the One-Year Business Learning Journey',
                '100 Structured Sessions',
                '200 Hours of Practical Business Education',
                'Business ABCD to IPO Learning Framework',
                'Networking with Entrepreneurs & Professionals',
                'Practical Business & Financial Growth Strategies',
                'Participation Appreciation Certificate',
            ],
            'seats' => 'Limited Seats Available',
            'cta' => ['label' => 'Register Now', 'route' => 'register'],
        ],
    ],

    'calendar' => [
        'title' => 'Event Calendar',
        'month' => '',
        'columns' => [],
        'rows' => [],
    ],

    'categories' => [],

    'cta' => [
        'title' => 'Ready to Learn, Network & Grow?',
        'text' => 'Reserve your seat today and become part of India\'s prosperity movement.',
        'button' => ['label' => 'Register Now', 'route' => 'register'],
    ],

];
