<?php

return [

    'hero' => [
        'sub_title' => 'Business Navachar School',
        'title' => 'Learn Business.',
        'title_lines' => ['Build Wealth.', 'Create Impact.'],
        'text' => 'A structured business learning ecosystem designed to transform individuals into entrepreneurs and build a prosperous India.',
        'support_line' => '“Education of Prosperity to Eliminate Poverty.”',
        'video_url' => 'https://www.youtube.com/watch?v=Get7rqXYrbQ',
        'video_label' => 'Introduction Video',

        'ctas' => [
            [
                'label' => 'Admission Now',
                'icon' => '🚀',
                'style' => 'primary',
                'type' => 'route',
                'route' => 'register',
            ],
            [
                'label' => 'Introduction Video',
                'icon' => '▶️',
                'style' => 'secondary',
                'type' => 'video',
                'url' => 'https://www.youtube.com/watch?v=Get7rqXYrbQ',
            ],
            [
                'label' => 'WhatsApp Us',
                'icon' => '📲',
                'style' => 'whatsapp',
                'type' => 'whatsapp',
            ],
        ],

        'primary_ctas' => [
            ['label' => 'Book Your Spot Now', 'icon' => '🚀', 'type' => 'route', 'route' => 'register'],
            ['label' => 'Register Now', 'icon' => '🎯', 'type' => 'route', 'route' => 'register'],
            ['label' => 'Book Your Free Introduction Session', 'icon' => '📞', 'type' => 'route', 'route' => 'admissions.page', 'params' => ['introduction-session']],
            ['label' => 'Reserve Your Seat', 'icon' => '📅', 'type' => 'route', 'route' => 'register'],
            ['label' => 'Join Business Navachar School', 'icon' => '🎓', 'type' => 'route', 'route' => 'register'],
            ['label' => 'Join the Prosperity Movement', 'icon' => '🌟', 'type' => 'route', 'route' => 'about.prosperity-mission'],
            ['label' => 'Start Your Business Learning Journey', 'icon' => '💼', 'type' => 'route', 'route' => 'admissions.index'],
            ['label' => 'Enroll Today', 'icon' => '📋', 'type' => 'route', 'route' => 'register'],
        ],

        'secondary_ctas' => [
            ['label' => 'Introduction Video', 'icon' => '▶️', 'type' => 'video', 'url' => 'https://www.youtube.com/watch?v=Get7rqXYrbQ'],
            ['label' => 'Download Prospectus', 'icon' => '📄', 'type' => 'route', 'route' => 'admissions.page', 'params' => ['download-prospectus']],
            ['label' => 'Explore Syllabus', 'icon' => '📚', 'type' => 'route', 'route' => 'syllabus'],
            ['label' => 'View Upcoming Sessions', 'icon' => '📅', 'type' => 'route', 'route' => 'admissions.page', 'params' => ['introduction-session']],
            ['label' => 'Meet Our Mentors', 'icon' => '🎓', 'type' => 'route', 'route' => 'about.faculty'],
            ['label' => 'Why BNS?', 'icon' => '❓', 'type' => 'route', 'route' => 'about.why'],
            ['label' => 'Chat on WhatsApp', 'icon' => '💬', 'type' => 'whatsapp'],
        ],
    ],

    'hero_highlights' => [
        'India\'s Weekly Business School',
        'Academic Collaboration with Faculties of IIM',
        '540 Animated Business Learning Videos',
        '2 Sessions Every Week • 200 Learning Hours / Year',
        'Idea → Startup → Business → Growth → IPO',
        'School Student • Growth Batch • College Youth • Women Batch • Business & Job Professional Batch',
        'Innovation Today. Prosperity Tomorrow.',
        'Together Towards Viksit Bharat 2047',
    ],

    'hero_banner' => [
        'image' => 'hero_slide_1',
        'alt' => 'Business Navachar School — weekly business education for every Indian',
    ],

    'hero_slides' => [
        [
            'image' => 'hero_slide_1',
            'alt' => "Don't just SAIL... SCALE — Business Navachar School",
        ],
        [
            'image' => 'hero_slide_2',
            'alt' => 'Develop Ability to Grab Every Opportunity — Business Navachar School',
        ],
        [
            'image' => 'hero_slide_3',
            'alt' => 'Business Education for Every Indian — Learn Prosperity at BNS',
        ],
        [
            'image' => 'hero_slide_4',
            'alt' => 'Business Navachar School — Innovation Today. Prosperity Tomorrow.',
        ],
    ],

    'audience_section' => [
        'tagline' => 'Business Navachar School',
        'title' => 'Are you',
        'subtitle' => 'Select your path — structured Weekly Business School programs for every stage of life.',
        'ownership_note' => 'Business Navachar School is owned and managed by BNS E-TECH PRIVATE LIMITED.',
        'cards' => [
            [
                'icon' => '👧',
                'label' => 'School Student',
                'card_title_top' => 'SCHOOL',
                'card_title_main' => 'Student',
                'card_image' => 'audience_school_student',
                'image_url' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'School students learning together',
                'card_theme' => ['bg' => '#4a0e1c', 'accent' => '#ffb08f'],
                'desc' => 'Std 6 to Std 11 — build entrepreneurial foundations early.',
                'register_hash' => 'student-school',
                'program_slug' => 'school-student',
                'dedicated_page' => true,
                'eligibility_title' => 'Youth Startup',
                'contact_category' => 'Student',
                'contact_program' => 'School Students Program',
            ],
            [
                'icon' => '🎓',
                'label' => 'College Youth',
                'card_title_top' => 'COLLEGE',
                'card_title_main' => 'Youth',
                'card_image' => 'audience_college_youth',
                'image_url' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'College youth in campus learning',
                'card_theme' => ['bg' => '#1a2f4d', 'accent' => '#fbbf24'],
                'desc' => 'Undergraduate & postgraduate — from job seeker to job creator.',
                'register_hash' => 'college-youth',
                'program_slug' => 'college-youth',
                'dedicated_page' => true,
                'admission_register_hash' => 'youth-school',
                'eligibility_title' => 'Youth Startup',
                'contact_category' => 'College Student',
                'contact_program' => 'College Students Program',
            ],
            [
                'icon' => '👩',
                'label' => 'Women Batch',
                'card_title_top' => 'WOMEN',
                'card_title_main' => 'Batch',
                'card_image' => 'audience_job_business',
                'image_url' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'Women entrepreneurs learning together',
                'card_theme' => ['bg' => '#4a0e1c', 'accent' => '#ffb08f'],
                'desc' => 'For women entrepreneurs, homepreneurs & aspiring business leaders.',
                'register_hash' => 'job-business-batch',
                'program_slug' => 'women-batch',
                'dedicated_page' => true,
                'eligibility_title' => 'Women Entrepreneurs',
                'contact_category' => 'Women Entrepreneur',
                'contact_program' => 'Women Entrepreneurs Program',
            ],
            [
                'icon' => '💼',
                'label' => 'Business & Job Professional Batch',
                'card_title_top' => 'BUSINESS & JOB',
                'card_title_main' => 'Professional',
                'card_image' => 'audience_business_job_professional',
                'image_url' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'Business owners and professionals in a meeting',
                'card_theme' => ['bg' => '#1e3a5f', 'accent' => '#60a5fa'],
                'desc' => 'Job Excellence School for professionals & Business Empire School for owners.',
                'register_hash' => 'business-job-professional-batch',
                'program_slug' => 'business-job-professional-batch',
                'dedicated_page' => true,
                'eligibility_title' => 'Business Owners',
                'contact_category' => 'Business Owner',
                'contact_program' => 'Business and Job Professional Batch Program',
            ],
            [
                'icon' => '📈',
                'label' => 'Growth Batch',
                'card_title_top' => 'GROWTH',
                'card_title_main' => 'Batch',
                'card_image' => 'audience_growth_batch',
                'image_url' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=900&q=80',
                'image_alt' => 'Business growth and leadership',
                'card_theme' => ['bg' => '#2d1b33', 'accent' => '#f4a8a0'],
                'desc' => 'Business to IPO Journey — grow, lead & scale with practical business learning.',
                'register_hash' => 'growth-batch',
                'program_slug' => 'growth-batch',
                'dedicated_page' => true,
                'admission_register_hash' => 'business-growth-school',
                'eligibility_title' => 'Business Owners',
                'contact_category' => 'Business Owner',
                'contact_program' => 'Business Owners & Business Professionals Program',
            ],
        ],
    ],

    'sticky_cta' => [
        'enabled' => true,
        'hide_on_routes' => ['register', 'pay-now', 'attendance', 'payment.success', 'payment.failure', 'payment.checkout'],
        'intro_session' => [
            'program_label' => 'Business Navachar School',
            'contact_program' => 'School Students Program',
            'contact_category' => 'Other',
        ],
        'inquiry' => [
            'button_label' => 'Inquiry Now',
            'intro' => 'Share your question and our Admission Team will contact you with program details, eligibility, fees, and next steps.',
            'program_label' => 'Business Navachar School',
            'contact_program' => 'School Students Program',
            'contact_category' => 'Other',
        ],
        'buttons' => [
            [
                'label' => 'Admission Now (BNS)',
                'url' => '/register',
                'style' => 'outline',
            ],
            [
                'label' => 'Introduction Session Admission Now',
                'style' => 'primary',
            ],
        ],
    ],

];
