<?php

return [

    'featured_page' => [
        'title' => 'Featured Programs',
        'subtitle' => 'Practical Business Education for Every Stage of Life',
        'label' => 'Programs',
        'intro' => [
            'Business Navachar School (BNS) offers five structured Weekly Business School Programs designed to meet the learning needs of school students, growth learners, college youth, women entrepreneurs, and business & job professionals.',
        ],
        'programs' => [
            [
                'slug' => 'school-student',
                'icon' => '👧',
                'title' => 'School Student Program',
                'audience' => 'Std 6 to Std 11',
                'summary' => 'Build a strong foundation in business and entrepreneurship from an early age.',
                'learn_heading' => 'Students Learn:',
                'learn_items' => [
                    'Entrepreneurial Mindset',
                    'Financial Literacy',
                    'Communication Skills',
                    'Leadership Development',
                    'Business Fundamentals',
                    'Innovation & Creativity',
                    'Marketing Basics',
                    'Business Projects',
                ],
                'goal' => 'Transform Students into Future Entrepreneurs & Business Leaders.',
                'duration' => '5-Year Weekly Business Leadership Journey',
            ],
            [
                'slug' => 'college-youth',
                'icon' => '🎓',
                'title' => 'College Youth Program',
                'audience' => 'Undergraduate & Postgraduate Students',
                'summary' => 'Prepare for the future with practical business knowledge alongside academic education.',
                'learn_heading' => 'Students Learn:',
                'learn_items' => [
                    'Startup Development',
                    'Business Models',
                    'Sales & Marketing',
                    'Digital Business',
                    'Branding',
                    'Finance & Investment Basics',
                    'Business Strategy',
                    'Scale-Up Framework',
                ],
                'goal' => 'Transform Job Seekers into Job Creators.',
                'duration' => '3-Year Business Learning Journey',
            ],
            [
                'slug' => 'women-batch',
                'icon' => '👩',
                'title' => 'Women Batch',
                'audience' => 'Women Entrepreneurs, Homepreneurs & Aspiring Business Leaders',
                'summary' => 'Build confidence, grow your business, and achieve financial independence with practical entrepreneurship education.',
                'learn_heading' => 'Participants Learn:',
                'learn_items' => [
                    'Leadership & Team Management',
                    'Business Growth & Sales Systems',
                    'Marketing, Branding & Digital Business',
                    'Finance, Profitability & Valuation',
                    'Operations, SOPs & Automation',
                    'AI for Business & Productivity',
                    'Funding & Investor Readiness',
                    'Entrepreneurship & Scale-Up Strategy',
                ],
                'goal' => 'Empowered Women. Strong Businesses. Prosperous Families.',
                'duration' => '2-Year Women Business School',
            ],
            [
                'slug' => 'business-job-professional-batch',
                'icon' => '💼',
                'title' => 'Business & Job Professional Batch',
                'audience' => 'Business Owners, MSMEs, Startup Founders & Job Professionals',
                'summary' => 'One-Year Executive Programs — Job Excellence School for professionals & Business Empire School for owners.',
                'learn_heading' => 'Participants Learn:',
                'learn_items' => [
                    'Business Strategy & Growth',
                    'Leadership & Management',
                    'Marketing, Sales & Branding',
                    'Digital Marketing & AI',
                    'Finance, Accounting & Funding',
                    'HR, Operations & Business Systems',
                    'Corporate Governance & Scale-Up',
                    'Career & Business Excellence',
                ],
                'goal' => 'Learn. Lead. Excel. Grow. Prosper.',
                'duration' => 'One-Year Executive Program | Job Excellence School • Business Empire School',
            ],
            [
                'slug' => 'growth-batch',
                'icon' => '📈',
                'title' => 'Growth Batch',
                'audience' => 'Business Owners, Job Professional, Women Entrepreneurs & Youth Startups',
                'summary' => 'Business to IPO Journey — grow, lead, scale, and systemize your business with practical learning.',
                'learn_heading' => 'Participants Learn:',
                'learn_items' => [
                    'Business Strategy & Growth',
                    'Marketing, Sales & Branding',
                    'Digital Marketing & AI',
                    'Finance, Accounting & Funding',
                    'HR, Leadership & Operations',
                    'Corporate Governance & IPO Readiness',
                    'Business Systems & Automation',
                    'Global Business Expansion',
                ],
                'goal' => 'Learn. Grow. Scale. Lead. Go IPO.',
                'duration' => '100 Sessions | 200 Learning Hours',
            ],
        ],
        'benefits' => [
            'title' => 'Common Benefits for All Programs',
            'items' => [
                'Weekly 4-Hour Structured Learning',
                'Practical Business Education',
                'Live Projects & Case Studies',
                'Expert Mentorship',
                'Industry Exposure',
                'Business Networking',
                'Digital Learning Resources',
                'Academic Collaboration with Faculties of IIM',
                'Participation & Appreciation Certificates by Faculties of IIM (for eligible participants)',
            ],
        ],
        'closing' => [
            'headline' => 'One Mission • Five Programs • Unlimited Opportunities',
            'brand' => 'Business Navachar School',
            'subtitle' => 'Business Education for Every Indian',
            'tagline' => 'Learn Prosperity • Create Prosperity • Build a Developed India',
        ],
    ],

];
